Repository vaadin/web-components, pull requests merged in 2021-09, with the labels that each got.

#2427 fix: reflect tree grid level in a tree column toggle
  packages/vaadin-grid/src/vaadin-grid-tree-column.js
  packages/vaadin-grid/test/tree-toggle.test.js
Labels: target/21.0

#2282 refactor!: update select to use new structure
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/alignment-label.png
  packages/select/package.json
  packages/select/src/vaadin-select-text-field.js
  packages/select/src/vaadin-select-value-button.js
  packages/select/src/vaadin-select.d.ts
  packages/select/src/vaadin-select.js
  packages/select/test/accessibility.test.js
  packages/select/test/not-animated-styles.js
  packages/select/test/renderer.test.js
  packages/select/test/scrollable-viewport.test.js
  packages/select/test/select.test.js
  packages/select/test/template.test.js
  packages/select/test/visual/lumo/screenshots/select/baseline/align-center.png
  packages/select/test/visual/lumo/screenshots/select/baseline/align-right.png
  packages/select/test/visual/lumo/screenshots/select/baseline/focus-ring.png
  packages/select/test/visual/lumo/screenshots/select/baseline/placeholder.png
  packages/select/test/visual/lumo/screenshots/select/baseline/value.png
  packages/select/test/visual/lumo/select.test.js
  packages/select/test/visual/material/screenshots/select/baseline/basic.png
  packages/select/test/visual/material/screenshots/select/baseline/disabled.png
  packages/select/test/visual/material/screenshots/select/baseline/error-message.png
  packages/select/test/visual/material/screenshots/select/baseline/focus-ring.png
  packages/select/test/visual/material/screenshots/select/baseline/helper-text.png
  packages/select/test/visual/material/screenshots/select/baseline/label.png
  packages/select/test/visual/material/screenshots/select/baseline/placeholder.png
  packages/select/test/visual/material/screenshots/select/baseline/prefix.png
  packages/select/test/visual/material/screenshots/select/baseline/readonly.png
  packages/select/test/visual/material/screenshots/select/baseline/required.png
  packages/select/test/visual/material/screenshots/select/baseline/value.png
  packages/select/test/visual/material/select.test.js
  packages/select/theme/lumo/vaadin-select-styles.js
  packages/select/theme/lumo/vaadin-select.js
  packages/select/theme/material/vaadin-select-styles.js
  packages/select/theme/material/vaadin-select.js
  packages/vaadin-custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label.png
  packages/vaadin-custom-field/test/visual/material/screenshots/custom-field/baseline/alignment-label.png
  packages/vaadin-grid-pro/src/vaadin-grid-pro-edit-select.js
  packages/vaadin-grid-pro/test/edit-column-type.test.js
  packages/vaadin-grid-pro/test/visual/material/screenshots/grid-pro/baseline/edit-column-select.png
  packages/vaadin-grid-pro/theme/lumo/vaadin-grid-pro-edit-select-styles.js
  packages/vaadin-grid-pro/theme/material/vaadin-grid-pro-edit-select-styles.js
Labels: a11y, a11y phase 1

#2426 fix: do not override custom helper component ID
  packages/field-base/src/field-aria-mixin.js
  packages/field-base/src/helper-text-mixin.js
  packages/field-base/test/field-aria-mixin.test.js
  packages/field-base/test/helper-text-mixin.test.js
Labels: a11y, a11y phase 1

#2439 test: move grid sorting visual tests inside the right describe block
  packages/vaadin-grid/test/visual/lumo/grid.test.js
  packages/vaadin-grid/test/visual/lumo/screenshots/grid/baseline/rtl-sorting-initial.png
  packages/vaadin-grid/test/visual/lumo/screenshots/grid/baseline/rtl-sorting-multi-asc-asc.png
  packages/vaadin-grid/test/visual/lumo/screenshots/grid/baseline/rtl-sorting-multi-asc-desc.png
  packages/vaadin-grid/test/visual/lumo/screenshots/grid/baseline/rtl-sorting-single-asc.png
  packages/vaadin-grid/test/visual/lumo/screenshots/grid/baseline/rtl-sorting-single-desc.png
  packages/vaadin-grid/test/visual/material/grid.test.js
  packages/vaadin-grid/test/visual/material/screenshots/grid/baseline/rtl-sorting-initial.png
  packages/vaadin-grid/test/visual/material/screenshots/grid/baseline/rtl-sorting-multi-asc-asc.png
  packages/vaadin-grid/test/visual/material/screenshots/grid/baseline/rtl-sorting-multi-asc-desc.png
  packages/vaadin-grid/test/visual/material/screenshots/grid/baseline/rtl-sorting-single-asc.png
  packages/vaadin-grid/test/visual/material/screenshots/grid/baseline/rtl-sorting-single-desc.png
Labels: target/21.0

#2445 feat: add SlotStylesMixin for injecting styles
  packages/field-base/index.d.ts
  packages/field-base/index.js
  packages/field-base/src/slot-styles-mixin.d.ts
  packages/field-base/src/slot-styles-mixin.js
  packages/field-base/test/slot-styles-mixin.test.js
Labels: a11y, a11y phase 1

#2453 fix: hide native controls, handle RTL styles
  packages/number-field/src/vaadin-number-field.d.ts
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/test/visual/common.js
  packages/number-field/test/visual/lumo/number-field.test.js
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/focus-ring.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-controls.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-error-message.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-helper-text.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-label.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-placeholder.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-prefix.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-required.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-suffix.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-theme-align-right.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-value.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-controls.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-error-message.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-helper-text.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-label.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-placeholder.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-prefix.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-required.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-suffix.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-theme-align-right.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-value.png
  packages/number-field/test/visual/material/number-field.test.js
  packages/number-field/test/visual/material/screenshots/number-field/baseline/focus-ring.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-controls.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-error-message.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-helper-text.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-label.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-placeholder.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-prefix.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-required.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-suffix.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/ltr-value.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-controls.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-error-message.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-helper-text.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-label.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-placeholder.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-prefix.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-required.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-suffix.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/rtl-value.png
  packages/vaadin-lumo-styles/typography.js
  packages/vaadin-material-styles/typography.js
Labels: a11y, a11y phase 1

#2410 fix: don't create unnecessary virtualizer elements on size change
  packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js
  packages/vaadin-virtual-list/test/virtualizer.test.js
Labels: target/21.0

#2477 chore: fix issues with the release notes script
  scripts/generateReleaseNotes.js
Labels: target/21.0

#2475 fix: use lumo iconset with vaadin-icon
  packages/vaadin-lumo-styles/icons.js
Labels: target/21.0

#2467 refactor!: move combo-box items to light DOM
  packages/vaadin-combo-box/src/vaadin-combo-box-data-provider-mixin.js
  packages/vaadin-combo-box/src/vaadin-combo-box-dropdown-wrapper.js
  packages/vaadin-combo-box/src/vaadin-combo-box-dropdown.js
  packages/vaadin-combo-box/src/vaadin-combo-box-item.js
  packages/vaadin-combo-box/src/vaadin-combo-box-light.js
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/src/vaadin-combo-box-overlay.js
  packages/vaadin-combo-box/src/vaadin-combo-box-scroller.js
  packages/vaadin-combo-box/src/vaadin-combo-box.js
  packages/vaadin-combo-box/test/aria.test.js
  packages/vaadin-combo-box/test/basic.test.js
  packages/vaadin-combo-box/test/combo-box-light.test.js
  packages/vaadin-combo-box/test/dialog.test.js
  packages/vaadin-combo-box/test/dropdown.test.js
  packages/vaadin-combo-box/test/filtering.test.js
  packages/vaadin-combo-box/test/helpers.js
  packages/vaadin-combo-box/test/lazy-loading.test.js
  packages/vaadin-combo-box/test/object-values.test.js
  packages/vaadin-combo-box/test/overlay-position.test.js
  packages/vaadin-combo-box/test/scrolling.test.js
  packages/vaadin-combo-box/test/selecting-items.test.js
  packages/vaadin-combo-box/test/toggling-dropdown.test.js
Labels: a11y

#2503 chore: fix most of sonar code style warnings
  index.html
  packages/vaadin-combo-box/src/vaadin-combo-box-data-provider-mixin.js
  packages/vaadin-grid/src/vaadin-grid-selection-column.js
  packages/vaadin-grid/test/drag-and-drop.test.js
  packages/vaadin-grid/test/row-height.test.js
  packages/vaadin-menu-bar/test/sub-menu.test.js
  packages/vaadin-split-layout/src/vaadin-split-layout.js
  packages/vaadin-upload/test/common.js
  scripts/generateReleaseNotes.js
Labels: internal

#2514 chore: bump playwright to latest alpha
  package.json
  yarn.lock
Labels: internal

#2511 fix: set disabled on lazily added focusElement
  packages/field-base/src/delegate-focus-mixin.js
  packages/field-base/test/delegate-focus-mixin.test.js
Labels: a11y

#2521 test: use snapshots to cover button states
  packages/button/test/button.test.js
  packages/button/test/dom/__snapshots__/button.test.snap.js
  packages/button/test/dom/button.test.js
Labels: internal

#2520 chore: add dev pages for new input fields
  dev/email-field.html
  dev/number-field.html
  dev/password-field.html
  dev/text-area.html
Labels: internal

#2496 refactor!: update combo-box to use slotted input
  packages/vaadin-combo-box/package.json
  packages/vaadin-combo-box/src/interfaces.d.ts
  packages/vaadin-combo-box/src/vaadin-combo-box-light.d.ts
  packages/vaadin-combo-box/src/vaadin-combo-box-light.js
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.d.ts
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/src/vaadin-combo-box.d.ts
  packages/vaadin-combo-box/src/vaadin-combo-box.js
  packages/vaadin-combo-box/test/aria.test.js
  packages/vaadin-combo-box/test/basic.test.js
  packages/vaadin-combo-box/test/combo-box-light.test.js
  packages/vaadin-combo-box/test/form-input.test.js
  packages/vaadin-combo-box/test/helpers.js
  packages/vaadin-combo-box/test/item-renderer.test.js
  packages/vaadin-combo-box/test/keyboard.test.js
  packages/vaadin-combo-box/test/lazy-loading.test.js
  packages/vaadin-combo-box/test/overlay-position.test.js
  packages/vaadin-combo-box/test/scrolling.test.js
  packages/vaadin-combo-box/test/selecting-items.test.js
  packages/vaadin-combo-box/test/toggling-dropdown.test.js
  packages/vaadin-combo-box/test/typings/combo-box.types.ts
  packages/vaadin-combo-box/test/visual/common.js
  packages/vaadin-combo-box/test/visual/lumo/combo-box.test.js
  packages/vaadin-combo-box/test/visual/lumo/screenshots/combo-box/baseline/clear-button.png
  packages/vaadin-combo-box/test/visual/lumo/screenshots/combo-box/baseline/focus-ring.png
  packages/vaadin-combo-box/test/visual/lumo/screenshots/combo-box/baseline/placeholder.png
  packages/vaadin-combo-box/test/visual/lumo/screenshots/combo-box/baseline/value.png
  packages/vaadin-combo-box/test/visual/material/combo-box.test.js
  packages/vaadin-combo-box/test/visual/material/screenshots/combo-box/baseline/focus-ring.png
  packages/vaadin-combo-box/theme/lumo/vaadin-combo-box-styles.js
  packages/vaadin-combo-box/theme/lumo/vaadin-combo-box.js
  packages/vaadin-combo-box/theme/material/vaadin-combo-box-styles.js
  packages/vaadin-combo-box/theme/material/vaadin-combo-box.js
  packages/vaadin-custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label-helper-text.png
  packages/vaadin-time-picker/test/dropdown.test.js
Labels: a11y

#2545 chore: open dev page listing by default
  dev/index.html
  package.json
  web-dev-server.config.js
Labels: internal

#2552 fix: add logic and styles to ensure correct overlay appearance
  packages/vaadin-combo-box/test/overlay-position.test.js
  packages/vaadin-combo-box/test/visual/common.js
  packages/vaadin-combo-box/test/visual/lumo/combo-box.test.js
  packages/vaadin-combo-box/test/visual/lumo/screenshots/combo-box/baseline/opened.png
  packages/vaadin-combo-box/test/visual/material/combo-box.test.js
  packages/vaadin-combo-box/test/visual/material/screenshots/combo-box/baseline/opened.png
  packages/vaadin-combo-box/theme/lumo/vaadin-combo-box-dropdown-styles.js
  packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js
  packages/vaadin-overlay/test/position-target.test.js
Labels: a11y

#2555 chore: add date and time pickers dev pages
  dev/date-picker.html
  dev/date-time-picker.html
  dev/time-picker.html
Labels: internal

#2558 fix: display drop label as disabled when max files reached
  packages/vaadin-upload/src/vaadin-upload.d.ts
  packages/vaadin-upload/src/vaadin-upload.js
  packages/vaadin-upload/test/adding-files.test.js
  packages/vaadin-upload/test/visual/lumo/screenshots/upload/baseline/state-max-files-reached.png
  packages/vaadin-upload/test/visual/lumo/upload.test.js
  packages/vaadin-upload/test/visual/material/screenshots/upload/baseline/state-max-files-reached.png
  packages/vaadin-upload/test/visual/material/upload.test.js
  packages/vaadin-upload/theme/lumo/vaadin-upload-styles.js
  packages/vaadin-upload/theme/material/vaadin-upload-styles.js
Labels: target/21.0

#2562 chore: add checkbox dev page
  dev/checkbox.html
Labels: internal

#2532 refactor!: update date-picker to use slotted input
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-error-message.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label-error-message.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label-helper-text.png
  packages/vaadin-custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-error-message.png
  packages/vaadin-custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label-error-message.png
  packages/vaadin-date-picker/LICENSE
  packages/vaadin-date-picker/package.json
  packages/vaadin-date-picker/src/vaadin-date-picker-light.d.ts
  packages/vaadin-date-picker/src/vaadin-date-picker-light.js
  packages/vaadin-date-picker/src/vaadin-date-picker-mixin.d.ts
  packages/vaadin-date-picker/src/vaadin-date-picker-mixin.js
  packages/vaadin-date-picker/src/vaadin-date-picker-text-field.js
  packages/vaadin-date-picker/src/vaadin-date-picker.d.ts
  packages/vaadin-date-picker/src/vaadin-date-picker.js
  packages/vaadin-date-picker/test/basic.test.js
  packages/vaadin-date-picker/test/custom-input.test.js
  packages/vaadin-date-picker/test/dialog.test.js
  packages/vaadin-date-picker/test/dropdown.test.js
  packages/vaadin-date-picker/test/form-input.test.js
  packages/vaadin-date-picker/test/keyboard-input.test.js
  packages/vaadin-date-picker/test/keyboard-navigation.test.js
  packages/vaadin-date-picker/test/theme-propagation.test.js
  packages/vaadin-date-picker/test/typings/date-picker.types.ts
  packages/vaadin-date-picker/test/wai-aria.test.js
  packages/vaadin-date-picker/theme/lumo/vaadin-date-picker-styles.js
  packages/vaadin-date-picker/theme/lumo/vaadin-date-picker-text-field-styles.js
  packages/vaadin-date-picker/theme/lumo/vaadin-date-picker-text-field.js
  packages/vaadin-date-picker/theme/lumo/vaadin-date-picker.js
  packages/vaadin-date-picker/theme/material/vaadin-date-picker-styles.js
  packages/vaadin-date-picker/theme/material/vaadin-date-picker-text-field.js
  packages/vaadin-date-picker/theme/material/vaadin-date-picker.js
  packages/vaadin-date-time-picker/src/vaadin-date-time-picker-custom-field.js
  packages/vaadin-date-time-picker/src/vaadin-date-time-picker-date-picker.js
  packages/vaadin-date-time-picker/src/vaadin-date-time-picker-date-text-field.js
  packages/vaadin-date-time-picker/src/vaadin-date-time-picker.d.ts
  packages/vaadin-date-time-picker/src/vaadin-date-time-picker.js
  packages/vaadin-date-time-picker/test/basic.test.js
  packages/vaadin-date-time-picker/test/properties.test.js
  packages/vaadin-date-time-picker/test/visual/lumo/screenshots/date-time-picker/baseline/placeholder.png
  packages/vaadin-date-time-picker/test/visual/lumo/screenshots/date-time-picker/baseline/value.png
  packages/vaadin-date-time-picker/theme/lumo/vaadin-date-time-picker-styles.js
Labels: a11y

#2569 refactor: restructure input field shared styles
  packages/email-field/theme/lumo/vaadin-email-field-styles.js
  packages/email-field/theme/material/vaadin-email-field-styles.js
  packages/field-base/package.json
  packages/field-base/src/styles/clear-button-styles.d.ts
  packages/field-base/src/styles/clear-button-styles.js
  packages/field-base/src/styles/field-shared-styles.d.ts
  packages/field-base/src/styles/field-shared-styles.js
  packages/field-base/src/styles/input-field-container-styles.d.ts
  packages/field-base/src/styles/input-field-container-styles.js
  packages/field-base/src/styles/input-field-shared-styles.d.ts
  packages/field-base/src/styles/input-field-shared-styles.js
  packages/number-field/package.json
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/theme/lumo/vaadin-number-field-styles.js
  packages/number-field/theme/material/vaadin-number-field-styles.js
  packages/password-field/theme/lumo/vaadin-password-field-styles.js
  packages/password-field/theme/material/vaadin-password-field-styles.js
  packages/select/package.json
  packages/select/src/vaadin-select.js
  packages/select/theme/lumo/vaadin-select-styles.js
  packages/select/theme/material/vaadin-select-styles.js
  packages/text-area/package.json
  packages/text-area/src/vaadin-text-area.js
  packages/text-area/theme/lumo/vaadin-text-area-styles.js
  packages/text-area/theme/material/vaadin-text-area-styles.js
  packages/text-field/src/vaadin-input-field-shared-styles.js
  packages/text-field/src/vaadin-text-field.js
  packages/text-field/test/visual/lumo/vaadin-text-field.js
  packages/text-field/test/visual/material/vaadin-text-field.js
  packages/text-field/theme/lumo/vaadin-text-field-styles.js
  packages/text-field/theme/material/vaadin-text-field-styles.js
  packages/vaadin-combo-box/package.json
  packages/vaadin-combo-box/src/vaadin-combo-box.d.ts
  packages/vaadin-combo-box/src/vaadin-combo-box.js
  packages/vaadin-combo-box/theme/lumo/vaadin-combo-box-styles.js
  packages/vaadin-combo-box/theme/material/vaadin-combo-box-styles.js
  packages/vaadin-date-picker/package.json
  packages/vaadin-date-picker/src/vaadin-date-picker.js
  packages/vaadin-date-picker/theme/lumo/vaadin-date-picker-styles.js
  packages/vaadin-date-picker/theme/material/vaadin-date-picker-styles.js
  packages/vaadin-lumo-styles/mixins/helper.d.ts
  packages/vaadin-lumo-styles/mixins/helper.js
  packages/vaadin-lumo-styles/mixins/input-field-shared.d.ts
  packages/vaadin-lumo-styles/mixins/input-field-shared.js
  packages/vaadin-material-styles/mixins/helper.d.ts
  packages/vaadin-material-styles/mixins/helper.js
  packages/vaadin-material-styles/mixins/input-field-shared.d.ts
  packages/vaadin-material-styles/mixins/input-field-shared.js
Labels: a11y

#2580 refactor: use separate fields to store unique IDs
  packages/field-base/src/helper-text-mixin.js
  packages/field-base/src/input-slot-mixin.js
  packages/field-base/src/label-mixin.js
  packages/field-base/src/text-area-slot-mixin.js
  packages/field-base/src/validate-mixin.js
  packages/field-base/test/helper-text-mixin.test.js
  packages/field-base/test/input-slot-mixin.test.js
  packages/field-base/test/label-mixin.test.js
  packages/field-base/test/text-area-slot-mixin.test.js
  packages/field-base/test/validate-mixin.test.js
  packages/select/src/vaadin-select.js
  packages/select/test/accessibility.test.js
Labels: a11y

#2582 fix: set ARIA attributes properly, add tests
  packages/vaadin-combo-box/src/vaadin-combo-box.js
  packages/vaadin-combo-box/test/aria.test.js
  packages/vaadin-date-picker/src/vaadin-date-picker.js
  packages/vaadin-date-picker/test/wai-aria.test.js
Labels: a11y

#2590 fix: replace selection polyfill in quill to handle Safari selection issues
  packages/vaadin-rich-text-editor/test/basic.test.js
  packages/vaadin-rich-text-editor/vendor/vaadin-quill.js
  packages/vaadin-rich-text-editor/vendor/vaadin-quill.min.js.map
Labels: target/20.0, target/21.0

#2595 feat: use Lumo icons in number-field controls
  packages/integer-field/test/visual/lumo/screenshots/integer-field/baseline/controls.png
  packages/integer-field/test/visual/lumo/screenshots/integer-field/baseline/value.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/ltr-controls.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/rtl-controls.png
  packages/number-field/theme/lumo/vaadin-number-field-styles.js
Labels: theme

#2604 test: skip flaky formatting test in Firefox
  packages/vaadin-rich-text-editor/test/basic.test.js
Labels: target/20.0, target/21.0

#2602 fix: use correct type for ariaLabel property
  package.json
  packages/app-layout/src/vaadin-drawer-toggle.d.ts
  packages/crud/src/vaadin-crud-edit-column.d.ts
  packages/vaadin-dialog/src/vaadin-dialog.d.ts
  packages/vaadin-dialog/src/vaadin-dialog.js
  packages/vaadin-dialog/test/dialog.test.js
  yarn.lock
Labels: target/21.0

#2639 fix: ignore slotted inputs in custom-field
  packages/custom-field/src/vaadin-custom-field.js
  packages/custom-field/test/custom-field.test.js
  packages/vaadin-custom-field/src/vaadin-custom-field-mixin.js
  packages/vaadin-custom-field/test/basic.test.js
  packages/vaadin-date-time-picker/src/vaadin-date-time-picker-custom-field.js
  web-test-runner.config.js
Labels: a11y

#2663 fix: clear combo-box value on esc
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/test/keyboard.test.js
Labels: a11y

#2680 chore: update and cleanup dependencies
  packages/custom-field/package.json
  packages/radio-group/package.json
Labels: internal

#2641 refactor!: make radio-group use new mixins
  packages/radio-group/package.json
  packages/radio-group/src/vaadin-radio-group.d.ts
  packages/radio-group/src/vaadin-radio-group.js
  packages/radio-group/test/radio-group-keyboard-navigation.test.js
  packages/radio-group/test/radio-group.test.js
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/helper-text.png
  packages/radio-group/theme/lumo/vaadin-radio-group-styles.js
  packages/radio-group/theme/material/vaadin-radio-group-styles.js
  packages/vaadin-overlay/test/focus-trap.test.js
Labels: a11y
