Repository vaadin/web-components, pull requests merged in 2021-12, with the labels that each got.

#3136 chore: update README with instructions to bump to v24
  README.md
Labels: internal

#3137 chore: update components npm badges in README
  README.md
Labels: internal

#3142 fix: update date picker observer to mind the new structure
  packages/field-highlighter/src/fields/vaadin-date-picker-observer.js
  packages/field-highlighter/test/field-components.test.js
Labels: target/22.0

#3135 refactor!: update confirm-dialog to make styling easier
  dev/confirm-dialog.html
  packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js
  packages/confirm-dialog/src/vaadin-confirm-dialog.d.ts
  packages/confirm-dialog/src/vaadin-confirm-dialog.js
  packages/confirm-dialog/test/confirm-dialog.test.js
  packages/confirm-dialog/test/visual/lumo/confirm-dialog.test.js
  packages/confirm-dialog/test/visual/lumo/screenshots/confirm-dialog/baseline/basic.png
  packages/confirm-dialog/test/visual/lumo/screenshots/confirm-dialog/baseline/cancel-reject.png
  packages/confirm-dialog/test/visual/lumo/screenshots/confirm-dialog/baseline/cancel.png
  packages/confirm-dialog/test/visual/lumo/screenshots/confirm-dialog/baseline/reject.png
  packages/confirm-dialog/test/visual/material/confirm-dialog.test.js
  packages/confirm-dialog/test/visual/material/screenshots/confirm-dialog/baseline/basic.png
  packages/confirm-dialog/test/visual/material/screenshots/confirm-dialog/baseline/cancel-reject.png
  packages/confirm-dialog/test/visual/material/screenshots/confirm-dialog/baseline/cancel.png
  packages/confirm-dialog/test/visual/material/screenshots/confirm-dialog/baseline/reject.png
  packages/confirm-dialog/theme/lumo/vaadin-confirm-dialog-styles.js
  packages/confirm-dialog/theme/material/vaadin-confirm-dialog-styles.js
  packages/crud/test/crud.test.js
  packages/vaadin-overlay/src/vaadin-overlay.js
Labels: a11y

#3143 fix: set hidden attribute on the error message when field is valid
  packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
  packages/field-base/src/field-mixin.js
  packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js
  packages/message-input/test/dom/__snapshots__/message-input.test.snap.js
  packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
  packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
  packages/select/test/dom/__snapshots__/select.test.snap.js
  packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
  packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
Labels: target/22.0

#3146 refactor!: make vaadin-crud-edit extend vaadin-button
  packages/crud/src/vaadin-crud-edit.d.ts
  packages/crud/src/vaadin-crud-edit.js
  packages/crud/test/visual/lumo/crud.test.js
  packages/crud/test/visual/lumo/screenshots/crud/baseline/edit-button-focus.png
  packages/crud/test/visual/material/crud.test.js
  packages/crud/test/visual/material/screenshots/crud/baseline/edit-button-focus.png
  packages/crud/theme/lumo/vaadin-crud-styles.js
  packages/crud/theme/material/vaadin-crud-styles.js
Labels: a11y

#3153 fix: remove generated pickers when adding custom pickers
  packages/date-time-picker/src/vaadin-date-time-picker.js
  packages/date-time-picker/test/basic.test.js
Labels: target/22.0

#3156 feat: add focus-ring attribute to vaadin-upload-file
  packages/upload/src/vaadin-upload-file.js
  packages/upload/src/vaadin-upload.js
  packages/upload/test/file.test.js
  packages/upload/theme/lumo/vaadin-upload-styles.js
  packages/upload/theme/material/vaadin-upload-styles.js
Labels: a11y

#3158 fix: workaround Safari/VoiceOver menu navigation
  packages/context-menu/theme/lumo/vaadin-context-menu-styles.js
Labels: target/22.0

#3167 refactor!: make reveal button extend vaadin-button
  packages/password-field/package.json
  packages/password-field/src/vaadin-password-field-button.js
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
  packages/password-field/test/password-field.test.js
  packages/password-field/theme/lumo/vaadin-password-field-button-styles.js
  packages/password-field/theme/lumo/vaadin-password-field-styles.js
  packages/password-field/theme/lumo/vaadin-password-field.js
  packages/password-field/theme/material/vaadin-password-field-button-styles.js
  packages/password-field/theme/material/vaadin-password-field-styles.js
  packages/password-field/theme/material/vaadin-password-field.js
Labels: a11y

#3166 chore: update Stylelint to v14, use postcss-lit
  .stylelintrc
  package.json
  packages/progress-bar/theme/lumo/vaadin-progress-bar-styles.js
  packages/rich-text-editor/src/vaadin-rich-text-editor-styles.js
  packages/rich-text-editor/src/vaadin-rich-text-editor-toolbar-styles.js
  yarn.lock
Labels: internal

#2395 feat: trap focus within app-layout drawer when opening in overlay
  packages/app-layout/src/vaadin-app-layout.d.ts
  packages/app-layout/src/vaadin-app-layout.js
  packages/app-layout/test/app-layout.test.js
  packages/app-layout/test/dom/__snapshots__/app-layout.test.snap.js
  packages/app-layout/test/dom/app-layout.test.js
  packages/app-layout/test/keyboard-navigation.test.js
  packages/app-layout/test/typings/app-layout.types.ts
Labels: a11y, a11y phase 2

#3178 refactor: move SlotController to component-base
  packages/component-base/index.d.ts
  packages/component-base/index.js
  packages/component-base/src/slot-controller.d.ts
  packages/component-base/src/slot-controller.js
  packages/field-base/src/input-controller.d.ts
  packages/field-base/src/input-controller.js
  packages/field-base/src/slot-controller.d.ts
  packages/field-base/src/slot-controller.js
  packages/field-base/src/text-area-controller.d.ts
  packages/field-base/src/text-area-controller.js
Labels: a11y

#3182 fix: prevent double error message announcement when using NVDA
  packages/checkbox-group/test/checkbox-group.test.js
  packages/combo-box/test/aria.test.js
  packages/custom-field/test/custom-field.test.js
  packages/date-picker/test/wai-aria.test.js
  packages/date-time-picker/test/aria.test.js
  packages/field-base/src/field-mixin.js
  packages/field-base/test/field-mixin.test.js
  packages/radio-group/test/radio-group.test.js
  packages/time-picker/test/aria.test.js
Labels: target/22.0

#3165 fix: enable input into autoOpenDisabled date picker on mobile
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/keyboard-input.test.js
Labels: target/22.0

#3193 refactor: add observer logic to SlotController
  packages/component-base/src/slot-controller.d.ts
  packages/component-base/src/slot-controller.js
  packages/component-base/test/slot-controller.test.js
Labels: a11y, target/22.0

#3195 refactor: remove iron-resizable-behavior from combo-box
  packages/combo-box/package.json
  packages/combo-box/src/vaadin-combo-box-dropdown.js
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/combo-box-light.test.js
  packages/combo-box/test/filtering.test.js
Labels: target/22.0

#3181 refactor: update LabelMixin to use SlotController
  packages/checkbox/src/vaadin-checkbox.js
  packages/checkbox/test/checkbox.test.js
  packages/combo-box/src/vaadin-combo-box.js
  packages/component-base/src/slot-controller.d.ts
  packages/component-base/src/slot-controller.js
  packages/date-picker/src/vaadin-date-picker.js
  packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
  packages/field-base/src/field-mixin.d.ts
  packages/field-base/src/field-mixin.js
  packages/field-base/src/label-controller.d.ts
  packages/field-base/src/label-controller.js
  packages/field-base/src/label-mixin.d.ts
  packages/field-base/src/label-mixin.js
  packages/field-base/src/labelled-input-controller.js
  packages/field-base/src/slot-label-mixin.js
  packages/field-base/test/label-mixin.test.js
  packages/field-base/test/labelled-input-controller.test.js
  packages/field-base/test/slot-label-mixin.test.js
  packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js
  packages/message-input/test/dom/__snapshots__/message-input.test.snap.js
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
  packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
  packages/radio-group/src/vaadin-radio-button.js
  packages/radio-group/test/radio-button.test.js
  packages/select/test/dom/__snapshots__/select.test.snap.js
  packages/text-area/src/vaadin-text-area.js
  packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
  packages/text-field/src/vaadin-text-field.js
  packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
  packages/time-picker/src/vaadin-time-picker.js
Labels: a11y

#3223 chore: update JSDoc to extend correct classes
  packages/time-picker/src/vaadin-time-picker-dropdown.js
  packages/time-picker/src/vaadin-time-picker-scroller.js
Labels: target/22.0

#3224 refactor: update time-picker theme files imports
  packages/time-picker/theme/lumo/vaadin-time-picker.js
  packages/time-picker/theme/material/vaadin-time-picker.js
Labels: target/22.0

#3225 test: do not use font-size for hiding blinking caret
  packages/combo-box/test/visual/common.js
  packages/login/test/visual/common.js
  packages/number-field/test/visual/common.js
Labels: target/22.0

#3226 fix: do not override i18n with hardcoded aria-label
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/password-field.test.js
Labels: a11y, target/22.0
