Repository vaadin/web-components, pull requests merged in 2021-05, with the labels that each got.

#300 chore: add version to release notes [skip ci]
  scripts/generateReleaseNotes.js
Labels: target/20.0

#301 docs: fix time-picker `step` property API docs [skip ci]
  packages/vaadin-date-time-picker/src/vaadin-date-time-picker.js
  packages/vaadin-time-picker/src/vaadin-time-picker.js
Labels: target/20.0

#318 chore: add scripts to generate all icons
  README.md
  package.json
  packages/vaadin-icons/gulpfile.js
  packages/vaadin-icons/iconset.js
  packages/vaadin-icons/package.json
  packages/vaadin-lumo-styles/font-icons.js
  packages/vaadin-lumo-styles/gulpfile.js
  packages/vaadin-lumo-styles/package.json
  packages/vaadin-material-styles/font-icons.js
  packages/vaadin-material-styles/gulpfile.js
  packages/vaadin-material-styles/package.json
  packages/vaadin-rich-text-editor/gulpfile.js
  packages/vaadin-rich-text-editor/package.json
  packages/vaadin-rich-text-editor/src/vaadin-rich-text-editor-icons.js
  yarn.lock
Labels: no-polymer, target/20.0

#339 chore: bump gulp-svgmin, update icons
  packages/vaadin-lumo-styles/gulpfile.js
  packages/vaadin-lumo-styles/icons/svg/clock.svg
  packages/vaadin-lumo-styles/icons/svg/download.svg
  packages/vaadin-lumo-styles/icons/svg/edit.svg
  packages/vaadin-lumo-styles/icons/svg/phone.svg
  packages/vaadin-lumo-styles/package.json
  packages/vaadin-material-styles/gulpfile.js
  packages/vaadin-material-styles/icons/svg/eye-disabled.svg
  packages/vaadin-material-styles/package.json
  yarn.lock
Labels: target/20.0

#299 feat!: remove polymer template api from vaadin-combo-box
  packages/vaadin-combo-box/src/vaadin-combo-box-item.js
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.d.ts
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/src/vaadin-combo-box.d.ts
  packages/vaadin-combo-box/src/vaadin-combo-box.js
  packages/vaadin-combo-box/test/combo-box-light.test.js
  packages/vaadin-combo-box/test/dropdown.test.js
  packages/vaadin-combo-box/test/fixtures/mock-combo-box-light-template-wrapper.js
  packages/vaadin-combo-box/test/fixtures/mock-combo-box-template-wrapper.js
  packages/vaadin-combo-box/test/item-renderer.test.js
  packages/vaadin-combo-box/test/item-template.test.js
  packages/vaadin-combo-box/test/toggling-dropdown.test.js
  packages/vaadin-template-renderer/src/vaadin-template-renderer-templatizer.js
  packages/vaadin-template-renderer/src/vaadin-template-renderer.js
  packages/vaadin-template-renderer/test/list.test.js
  packages/vaadin-template-renderer/test/vaadin-template-renderer.test.js
  packages/vaadin-template-renderer/test/x-component-host.js
  packages/vaadin-template-renderer/test/x-component.js
  packages/vaadin-template-renderer/test/x-list-host.js
  packages/vaadin-template-renderer/test/x-list.js
Labels: no-polymer

#358 fix: clear the content when removing the renderer in vaadin-overlay
  packages/vaadin-overlay/src/vaadin-overlay.js
  packages/vaadin-overlay/test/renderer.test.js
Labels: bug

#353 feat!: remove polymer template api from vaadin-select
  packages/vaadin-custom-field/package.json
  packages/vaadin-custom-field/test/visual/lumo/custom-field.test.js
  packages/vaadin-custom-field/test/visual/material/custom-field.test.js
  packages/vaadin-overlay/src/vaadin-overlay.js
  packages/vaadin-overlay/test/renderer.test.js
  packages/vaadin-select/package.json
  packages/vaadin-select/src/vaadin-select.d.ts
  packages/vaadin-select/src/vaadin-select.js
  packages/vaadin-select/test/renderer.test.js
  packages/vaadin-select/test/template.test.js
Labels: no-polymer

#361 fix: clear notification card when removing renderer
  packages/vaadin-notification/src/vaadin-notification.js
  packages/vaadin-notification/test/renderer.test.js
Labels: bug

#345 feat!: remove polymer template api from vaadin-notification
  packages/vaadin-notification/package.json
  packages/vaadin-notification/src/vaadin-notification.d.ts
  packages/vaadin-notification/src/vaadin-notification.js
  packages/vaadin-notification/test/animation.test.js
  packages/vaadin-notification/test/multiple.test.js
  packages/vaadin-notification/test/notification.test.js
  packages/vaadin-notification/test/renderer.test.js
  packages/vaadin-notification/test/styling.test.js
  packages/vaadin-notification/test/template.test.js
Labels: no-polymer

#371 fix: vaadin-message-list items property docs
  packages/vaadin-messages/src/vaadin-message-list.d.ts
  packages/vaadin-messages/src/vaadin-message-list.js
Labels: target/20.0

#364 feat!: remove polymer template api from vaadin-context-menu
  packages/vaadin-context-menu/package.json
  packages/vaadin-context-menu/src/vaadin-context-menu-overlay.js
  packages/vaadin-context-menu/src/vaadin-context-menu.d.ts
  packages/vaadin-context-menu/src/vaadin-context-menu.js
  packages/vaadin-context-menu/src/vaadin-contextmenu-items-mixin.d.ts
  packages/vaadin-context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/vaadin-context-menu/test/context.test.js
  packages/vaadin-context-menu/test/integration.test.js
  packages/vaadin-context-menu/test/items.test.js
  packages/vaadin-context-menu/test/overlay.test.js
  packages/vaadin-context-menu/test/properties.test.js
  packages/vaadin-context-menu/test/renderer.test.js
  packages/vaadin-context-menu/test/selection.test.js
  packages/vaadin-context-menu/test/template.test.js
  packages/vaadin-context-menu/test/touch.test.js
  packages/vaadin-context-menu/test/visual/lumo/context-menu.test.js
  packages/vaadin-context-menu/test/visual/material/context-menu.test.js
Labels: no-polymer

#379 fix: don't throw when renderer is set before adding to DOM
  packages/vaadin-notification/src/vaadin-notification.js
  packages/vaadin-notification/test/renderer.test.js
Labels: no-polymer, target/20.0

#380 fix: remove ID attribute from notification card
  packages/vaadin-notification/src/vaadin-notification.js
  packages/vaadin-notification/test/notification.test.js
Labels: target/20.0

#397 fix: Make dataprovider filtering case-insensitive (#1007)
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/test/lazy-loading.test.js
  web-test-runner.config.js
Labels: target/20.0

#388 feat: support rendering slotted templates for template renderer
  packages/vaadin-template-renderer/src/vaadin-template-renderer.js
  packages/vaadin-template-renderer/test/fixtures/mock-component-host.js
  packages/vaadin-template-renderer/test/fixtures/mock-component-slotted-host.js
  packages/vaadin-template-renderer/test/fixtures/mock-component.js
  packages/vaadin-template-renderer/test/fixtures/mock-list-host.js
  packages/vaadin-template-renderer/test/fixtures/mock-list.js
  packages/vaadin-template-renderer/test/list.test.js
  packages/vaadin-template-renderer/test/observer.test.js
  packages/vaadin-template-renderer/test/vaadin-template-renderer.test.js
Labels: no-polymer

#396 chore: add a `transferIssues` script [skip ci]
  .env.dist
  package.json
  scripts/transferIssues.js
  yarn.lock
Labels: internal

#406 chore: node12 compat fix for the transferIssues script [skip ci]
  scripts/transferIssues.js
Labels: internal

#1573 chore: do not disable repo isses by the transfer script [skip ci]
  scripts/transferIssues.js
Labels: internal

#1595 chore: skip open PRs in `transferIssues` script [skip ci]
  scripts/transferIssues.js
Labels: internal

#1959 fix: virtual list styles
  packages/vaadin-virtual-list/src/vaadin-virtual-list.js
  packages/vaadin-virtual-list/test/virtual-list.test.js
Labels: no-polymer

#362 feat: add vaadin-icon and vaadin-iconset
  packages/vaadin-icon/README.md
  packages/vaadin-icon/package.json
  packages/vaadin-icon/src/vaadin-icon-svg.d.ts
  packages/vaadin-icon/src/vaadin-icon-svg.js
  packages/vaadin-icon/src/vaadin-icon.d.ts
  packages/vaadin-icon/src/vaadin-icon.js
  packages/vaadin-icon/src/vaadin-iconset.d.ts
  packages/vaadin-icon/src/vaadin-iconset.js
  packages/vaadin-icon/test/.eslintrc.json
  packages/vaadin-icon/test/icon.test.js
  packages/vaadin-icon/test/iconset.test.js
  packages/vaadin-icon/test/typings/icon.types.ts
  packages/vaadin-icon/test/typings/iconset.types.ts
  packages/vaadin-icon/theme/lumo/vaadin-icon-styles.js
  packages/vaadin-icon/theme/lumo/vaadin-icon.js
  packages/vaadin-icon/theme/material/vaadin-icon-styles.js
  packages/vaadin-icon/theme/material/vaadin-icon.js
  packages/vaadin-icon/vaadin-icon.d.ts
  packages/vaadin-icon/vaadin-icon.js
  packages/vaadin-icon/vaadin-iconset.d.ts
  packages/vaadin-icon/vaadin-iconset.js
  web-test-runner.config.js
  wtr-utils.js
Labels: no-polymer

#1960 fix: disable grid section focus target in interaction mode
  package.json
  packages/vaadin-grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/vaadin-grid/test/keyboard-navigation.test.js
Labels: target/20.0

#1975 chore: add a `transferFlowIssues` script [skip ci]
  scripts/transferFlowIssues.js
Labels: internal

#1978 fix: update the structure of hidden rows
  packages/vaadin-grid/src/vaadin-grid.js
  packages/vaadin-grid/test/column.test.js
Labels: bug, no-polymer

#1995 feat: add first/last visible index APIs to virtual list
  packages/vaadin-virtual-list/src/vaadin-virtual-list.d.ts
  packages/vaadin-virtual-list/src/vaadin-virtual-list.js
  packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js
  packages/vaadin-virtual-list/src/virtualizer.js
  packages/vaadin-virtual-list/test/typings/virtual-list.types.ts
  packages/vaadin-virtual-list/test/unlimited-size.test.js
  packages/vaadin-virtual-list/test/virtual-list.test.js
Labels: no-polymer

#1997 fix: add missing app-layout dependency
  packages/vaadin-app-layout/package.json
Labels: target/20.0

#1999 test: fix version regex to allow RC
  packages/vaadin-accordion/test/accordion.test.js
  packages/vaadin-app-layout/test/app-layout.test.js
  packages/vaadin-avatar/test/avatar-group.test.js
  packages/vaadin-avatar/test/avatar.test.js
  packages/vaadin-board/test/basic.test.js
  packages/vaadin-button/test/button.test.js
  packages/vaadin-charts/test/chart-element.test.js
  packages/vaadin-confirm-dialog/test/confirm-dialog.test.js
  packages/vaadin-cookie-consent/test/cookie-consent.test.js
  packages/vaadin-date-time-picker/test/basic.test.js
  packages/vaadin-details/test/details.test.js
  packages/vaadin-dialog/test/dialog.test.js
  packages/vaadin-icon/test/icon.test.js
  packages/vaadin-item/test/item.test.js
  packages/vaadin-login/test/login-form.test.js
  packages/vaadin-menu-bar/test/menu-bar.test.js
  packages/vaadin-messages/test/message-input.test.js
  packages/vaadin-messages/test/message-list.test.js
  packages/vaadin-messages/test/message.test.js
  packages/vaadin-ordered-layout/test/horizontal-layout.js
  packages/vaadin-ordered-layout/test/scroller.test.js
  packages/vaadin-ordered-layout/test/vertical-layout.test.js
  packages/vaadin-progress-bar/test/progress-bar.test.js
  packages/vaadin-tabs/test/tabs.test.js
Labels: target/20.0

#2002 fix: make sure rows are generated to an emptied grid with heightByRows
  packages/vaadin-grid/src/vaadin-grid-styles.js
  packages/vaadin-grid/test/resizing.test.js
Labels: no-polymer

#1967 ref!: convert internal grid templates to renderers
  packages/vaadin-grid/src/vaadin-grid-column.d.ts
  packages/vaadin-grid/src/vaadin-grid-column.js
  packages/vaadin-grid/src/vaadin-grid-filter-column.d.ts
  packages/vaadin-grid/src/vaadin-grid-filter-column.js
  packages/vaadin-grid/src/vaadin-grid-selection-column.d.ts
  packages/vaadin-grid/src/vaadin-grid-selection-column.js
  packages/vaadin-grid/src/vaadin-grid-sort-column.d.ts
  packages/vaadin-grid/src/vaadin-grid-sort-column.js
  packages/vaadin-grid/src/vaadin-grid-tree-column.d.ts
  packages/vaadin-grid/src/vaadin-grid-tree-column.js
  packages/vaadin-grid/src/vaadin-grid.js
  packages/vaadin-grid/test/filtering.test.js
  packages/vaadin-grid/test/renderers.test.js
  packages/vaadin-grid/test/selection.test.js
  packages/vaadin-grid/test/sorting.test.js
  packages/vaadin-grid/test/tree-toggle.test.js
Labels: no-polymer

#1989 fix: include missing icons to Lumo icon sets
  packages/vaadin-lumo-styles/gulpfile.js
  packages/vaadin-lumo-styles/iconset.js
  packages/vaadin-lumo-styles/package.json
  packages/vaadin-lumo-styles/vaadin-iconset.js
Labels: no-polymer

#1984 test: add Lumo and Material visual tests
  .github/workflows/lumo.yml
  .github/workflows/material.yml
  packages/vaadin-lumo-styles/test/.eslintrc.json
  packages/vaadin-lumo-styles/test/glyphs.json
  packages/vaadin-lumo-styles/test/visual/font-icons.test.js
  packages/vaadin-lumo-styles/test/visual/iron-iconset-svg.test.js
  packages/vaadin-lumo-styles/test/visual/screenshots/baseline/font-icons.png
  packages/vaadin-lumo-styles/test/visual/screenshots/baseline/iron-iconset-svg.png
  packages/vaadin-lumo-styles/test/visual/screenshots/baseline/vaadin-iconset.png
  packages/vaadin-lumo-styles/test/visual/vaadin-iconset.test.js
  packages/vaadin-material-styles/gulpfile.js
  packages/vaadin-material-styles/test/.eslintrc.json
  packages/vaadin-material-styles/test/glyphs.json
  packages/vaadin-material-styles/test/visual/font-icons.test.js
  packages/vaadin-material-styles/test/visual/screenshots/baseline/font-icons.png
  wtr-utils.js
Labels: no-polymer

#2055 fix: compute final renderers even dependencies are undefined
  packages/vaadin-grid/src/vaadin-grid-column.js
Labels: no-polymer

#2053 fix: keep image aspect ratio
  packages/vaadin-avatar/src/vaadin-avatar.js
  packages/vaadin-avatar/test/visual/lumo/avatar.test.js
  packages/vaadin-avatar/test/visual/lumo/screenshots/avatar/baseline/aspect-ratio.png
  packages/vaadin-avatar/test/visual/material/avatar.test.js
  packages/vaadin-avatar/test/visual/material/screenshots/avatar/baseline/aspect-ratio.png
Labels: target/20.0

#1987 fix: remove overflow: hidden from RTE
  packages/vaadin-rich-text-editor/src/vaadin-rich-text-editor.js
Labels: target/20.0

#2057 test: add visual tests for vaadin-icons
  packages/vaadin-icons/test/.eslintrc.json
  packages/vaadin-icons/test/visual/iron-iconset-svg.test.js
  packages/vaadin-icons/test/visual/screenshots/baseline/iron-iconset-svg.png
  wtr-utils.js
Labels: no-polymer

#2059 feat: add vaadin-iconset to vaadin-icons
  packages/vaadin-app-layout/package.json
  packages/vaadin-confirm-dialog/package.json
  packages/vaadin-icons/gulpfile.js
  packages/vaadin-icons/package.json
  packages/vaadin-icons/test/visual/screenshots/baseline/vaadin-iconset.png
  packages/vaadin-icons/test/visual/vaadin-iconset.test.js
  packages/vaadin-icons/vaadin-iconset.js
  packages/vaadin-menu-bar/package.json
Labels: no-polymer

#2062 chore: update issues links in README [skip ci]
  README.md
Labels: target/20.0

#2065 fix!: rename misspelled icons
  packages/vaadin-icons/assets/fonts/Vaadin-Icons.svg
  packages/vaadin-icons/assets/icomoon.json
  packages/vaadin-icons/assets/png/bus.png
  packages/vaadin-icons/assets/png/function.png
  packages/vaadin-icons/assets/png/megaphone.png
  packages/vaadin-icons/assets/png/palette.png
  packages/vaadin-icons/assets/png/trending-down.png
  packages/vaadin-icons/assets/svg/bus.svg
  packages/vaadin-icons/assets/svg/function.svg
  packages/vaadin-icons/assets/svg/megaphone.svg
  packages/vaadin-icons/assets/svg/palette.svg
  packages/vaadin-icons/assets/svg/trending-down.svg
  packages/vaadin-icons/assets/vaadin-font-icons.json
  packages/vaadin-icons/docs/vaadin-icons-overview.adoc
  packages/vaadin-icons/iconset.js
  packages/vaadin-icons/vaadin-iconset.js
Labels: no-polymer

#2067 fix: force model's item bindings to re-render in template renderer
  packages/vaadin-template-renderer/src/vaadin-template-renderer-templatizer.js
  packages/vaadin-template-renderer/test/fixtures/mock-list-host.js
  packages/vaadin-template-renderer/test/list.test.js
Labels: no-polymer

#2069 fix: workaround a Safari sticky positioning issue
  packages/vaadin-grid/test/basic.test.js
  packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js
Labels: no-polymer

#2072 fix: exclude non-visible body cells from grid column auto width calc
  packages/vaadin-grid/src/vaadin-grid.js
  packages/vaadin-grid/test/column-auto-width.test.js
Labels: no-polymer
