Repository vaadin/web-components, pull requests merged in 2021-07, with the labels that each got.

#2172 fix: dispose of Lit parts after clearing innerHTML
  packages/vaadin-grid-pro/package.json
  packages/vaadin-grid-pro/src/vaadin-grid-pro-edit-column.js
  packages/vaadin-grid-pro/test/lit.test.js
  packages/vaadin-grid/src/vaadin-grid-column.js
  packages/vaadin-grid/test/lit-renderers.test.js
  packages/vaadin-grid/test/lit.test.js
  packages/vaadin-notification/package.json
  packages/vaadin-notification/src/vaadin-notification.js
  packages/vaadin-notification/test/lit.test.js
  packages/vaadin-overlay/package.json
  packages/vaadin-overlay/src/vaadin-overlay.js
  packages/vaadin-overlay/test/lit.test.js
Labels: no-polymer

#2153 fix: horizontally align combo-box overlay
  packages/vaadin-combo-box/src/vaadin-combo-box-dropdown.js
  packages/vaadin-combo-box/test/overlay-position.test.js
Labels: target/20.0

#2238 docs: deprecate the `iron-resize` event [skip ci]
  packages/vaadin-split-layout/src/vaadin-split-layout.js
  packages/vaadin-text-field/src/vaadin-text-area.js
  packages/vaadin-text-field/src/vaadin-text-field-mixin.js
Labels: no-polymer

#2232 fix: do not focus the field on helper element click
  packages/vaadin-checkbox/src/vaadin-checkbox-group.js
  packages/vaadin-checkbox/test/checkbox-group.test.js
  packages/vaadin-custom-field/src/vaadin-custom-field.js
  packages/vaadin-custom-field/test/helper.test.js
  packages/vaadin-radio-button/src/vaadin-radio-group.js
  packages/vaadin-select/src/vaadin-select.js
  packages/vaadin-select/test/select.test.js
  packages/vaadin-text-field/src/vaadin-text-area.js
  packages/vaadin-text-field/src/vaadin-text-field.js
  packages/vaadin-text-field/test/text-area.test.js
  packages/vaadin-text-field/test/text-field.test.js
Labels: target/20.0

#2251 test: cleanup helper text unit tests
  packages/vaadin-text-field/test/text-area.test.js
  packages/vaadin-text-field/test/text-field.test.js
Labels: target/20.0

#2254 fix: handle moving CRUD editor properly
  package.json
  packages/vaadin-crud/src/vaadin-crud.js
  packages/vaadin-crud/src/vaadin-dialog-layout.js
  packages/vaadin-crud/test/crud-editor.test.js
  tsconfig.json
  yarn.lock
Labels: target/20.0

#2260 docs: fix API docs for crud slots [skip ci]
  packages/vaadin-crud/src/vaadin-crud.d.ts
  packages/vaadin-crud/src/vaadin-crud.js
Labels: target/20.0

#2267 chore: refactor web-test-runner config
  package.json
  web-test-runner-firefox.config.js
  web-test-runner-lumo.config.js
  web-test-runner-material.config.js
  web-test-runner-webkit.config.js
  web-test-runner.config.js
  wtr-utils.js
  yarn.lock
Labels: internal

#2229 feat: add mixins to handle slotted input and label
  packages/field-base/LICENSE
  packages/field-base/README.md
  packages/field-base/index.d.ts
  packages/field-base/index.js
  packages/field-base/package.json
  packages/field-base/src/input-aria-mixin.d.ts
  packages/field-base/src/input-aria-mixin.js
  packages/field-base/src/input-mixin.d.ts
  packages/field-base/src/input-mixin.js
  packages/field-base/src/label-mixin.d.ts
  packages/field-base/src/label-mixin.js
  packages/field-base/src/slot-mixin.d.ts
  packages/field-base/src/slot-mixin.js
  packages/field-base/test/.eslintrc.json
  packages/field-base/test/input-aria-mixin.test.js
  packages/field-base/test/input-mixin.test.js
  packages/field-base/test/label-mixin.test.js
  packages/field-base/test/slot-mixin.test.js
  wtr-utils.js
Labels: a11y

#2231 feat: add mixins to handle slotted helper and error message
  packages/field-base/index.d.ts
  packages/field-base/index.js
  packages/field-base/src/field-aria-mixin.d.ts
  packages/field-base/src/field-aria-mixin.js
  packages/field-base/src/helper-text-mixin.d.ts
  packages/field-base/src/helper-text-mixin.js
  packages/field-base/src/validate-mixin.d.ts
  packages/field-base/src/validate-mixin.js
  packages/field-base/test/field-aria-mixin.test.js
  packages/field-base/test/helper-text-mixin.test.js
  packages/field-base/test/validate-mixin.test.js
Labels: a11y

#2281 fix: allow null and undefined in selected-item-changed event
  packages/vaadin-combo-box/src/interfaces.d.ts
  packages/vaadin-combo-box/test/typings/combo-box.types.ts
Labels: target/21.0

#2273 chore: use actions/setup-node built-in cache
  .github/workflows/chrome.yml
  .github/workflows/firefox.yml
  .github/workflows/lint.yml
  .github/workflows/lumo.yml
  .github/workflows/material.yml
  .github/workflows/webkit.yml
Labels: internal, target/20.0, target/21.0

#2277 chore: use playwright-cli to install deps
  .github/workflows/firefox.yml
  .github/workflows/webkit.yml
Labels: internal, target/20.0, target/21.0

#2233 feat: add mixins to handle focus and disabled state
  packages/field-base/index.d.ts
  packages/field-base/index.js
  packages/field-base/src/delegate-focus-mixin.d.ts
  packages/field-base/src/delegate-focus-mixin.js
  packages/field-base/src/disabled-mixin.d.ts
  packages/field-base/src/disabled-mixin.js
  packages/field-base/src/focus-mixin.d.ts
  packages/field-base/src/focus-mixin.js
  packages/field-base/test/delegate-focus-mixin.test.js
  packages/field-base/test/disabled-mixin.test.js
  packages/field-base/test/focus-mixin.test.js
Labels: a11y
