Repository vaadin/web-components, pull requests merged in 2021-10, with the labels that each got.

#2721 fix: Prevent firing custom value set event when readonly
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/test/basic.test.js
Labels: vaadin-combo-box, target/20.0, target/21.0

#2720 fix: do not override slot target content with whitespace nodes
  packages/field-base/src/slot-target-mixin.js
  packages/field-base/test/slot-label-mixin.test.js
  packages/field-base/test/slot-target-mixin.test.js
Labels: hacktoberfest-accepted

#2723 fix: remove unused cancel key on vaadin-upload
  packages/vaadin-upload/src/interfaces.d.ts
  packages/vaadin-upload/src/vaadin-upload.d.ts
  packages/vaadin-upload/src/vaadin-upload.js
Labels: hacktoberfest-accepted

#2719 chore: add dev page for text-field
  dev/text-field.html
Labels: internal

#2724 chore: update husky dev dependency to v7
  .husky/pre-commit
  package.json
  yarn.lock
Labels: hacktoberfest-accepted

#2726 fix: generate sentence case header for camel case columns
  packages/crud/src/vaadin-crud-grid.js
  packages/crud/test/crud-grid.test.js
Labels: hacktoberfest-accepted

#2718 fix: add itemValuePath to selectItemChanged observer.
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/test/object-values.test.js
Labels: target/20.0, target/21.0

#2732 chore: make husky pre-commit hook executable
  .husky/pre-commit
Labels: internal

#2730 fix: add itemValuePath to selectItemChanged observer (#2718)
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/test/object-values.test.js
Labels: target/20.0

#2735 refactor: make slot-target-mixin clone instead of moving
  dev/checkbox.html
  dev/radio-group.html
  packages/checkbox/src/vaadin-checkbox.js
  packages/checkbox/test/checkbox.test.js
  packages/checkbox/test/visual/lumo/checkbox.test.js
  packages/checkbox/test/visual/material/checkbox.test.js
  packages/field-base/src/slot-target-mixin.d.ts
  packages/field-base/src/slot-target-mixin.js
  packages/field-base/test/slot-target-mixin.test.js
  packages/radio-group/src/vaadin-radio-button.js
  packages/radio-group/test/radio-button.test.js
  packages/radio-group/test/visual/lumo/radio-button.test.js
  packages/radio-group/test/visual/material/radio-button.test.js
  wtr-utils.js
Labels: a11y

#2744 fix: don't prevent space keyup while interacting in grid
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/test/keyboard-navigation.test.js
Labels: a11y

#2745 feat: improve accessibility based on ARIA 1.2
  dev/combo-box.html
  packages/vaadin-combo-box/package.json
  packages/vaadin-combo-box/src/vaadin-combo-box-dropdown.js
  packages/vaadin-combo-box/src/vaadin-combo-box-item.js
  packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
  packages/vaadin-combo-box/src/vaadin-combo-box-scroller.js
  packages/vaadin-combo-box/test/aria.test.js
  packages/vaadin-combo-box/test/combo-box-light.test.js
  packages/vaadin-combo-box/test/dynamic-size.test.js
  packages/vaadin-combo-box/test/item-renderer.test.js
  packages/vaadin-combo-box/test/item-template.test.js
  packages/vaadin-combo-box/test/keyboard.test.js
  packages/vaadin-combo-box/test/lazy-loading.test.js
  packages/vaadin-combo-box/test/lit.test.js
  packages/vaadin-combo-box/test/object-values.test.js
  packages/vaadin-time-picker/src/vaadin-time-picker-combo-box.js
  packages/vaadin-time-picker/test/aria.test.js
Labels: a11y

#2749 revert: force highcharts to redraw when container's width changes
  packages/charts/test/visual/lumo/chart.test.js
  packages/charts/test/visual/lumo/screenshots/chart/baseline/responsive.png
  packages/charts/test/visual/material/chart.test.js
  packages/charts/test/visual/material/screenshots/chart/baseline/responsive.png
  packages/charts/theme/vaadin-chart-default-theme.js
Labels: target/20.0, target/21.0

#2762 revert: force highcharts to redraw when container's width changes (CP: 21)
  packages/vaadin-charts/test/visual/lumo/chart.test.js
  packages/vaadin-charts/test/visual/lumo/screenshots/chart/baseline/responsive.png
  packages/vaadin-charts/test/visual/material/chart.test.js
  packages/vaadin-charts/test/visual/material/screenshots/chart/baseline/responsive.png
  packages/vaadin-charts/theme/vaadin-chart-default-theme.js
Labels: target/20.0

#2774 refactor!: move vaadin-progress-bar to progress-bar
  packages/progress-bar/LICENSE
  packages/progress-bar/README.md
  packages/progress-bar/package.json
  packages/progress-bar/screenshot.gif
  packages/progress-bar/src/vaadin-progress-bar.d.ts
  packages/progress-bar/src/vaadin-progress-bar.js
  packages/progress-bar/src/vaadin-progress-mixin.d.ts
  packages/progress-bar/src/vaadin-progress-mixin.js
  packages/progress-bar/test/.eslintrc.json
  packages/progress-bar/test/progress-bar.test.js
  packages/progress-bar/test/visual/lumo/progress-bar.test.js
  packages/progress-bar/test/visual/lumo/screenshots/progress-bar/baseline/basic.png
  packages/progress-bar/test/visual/lumo/screenshots/progress-bar/baseline/rtl-basic.png
  packages/progress-bar/test/visual/lumo/screenshots/progress-bar/baseline/theme-contrast.png
  packages/progress-bar/test/visual/lumo/screenshots/progress-bar/baseline/theme-error.png
  packages/progress-bar/test/visual/lumo/screenshots/progress-bar/baseline/theme-success.png
  packages/progress-bar/test/visual/material/progress-bar.test.js
  packages/progress-bar/test/visual/material/screenshots/progress-bar/baseline/basic.png
  packages/progress-bar/test/visual/material/screenshots/progress-bar/baseline/rtl-basic.png
  packages/progress-bar/theme/lumo/vaadin-progress-bar-styles.js
  packages/progress-bar/theme/lumo/vaadin-progress-bar.js
  packages/progress-bar/theme/material/vaadin-progress-bar-styles.js
  packages/progress-bar/theme/material/vaadin-progress-bar.js
  packages/progress-bar/vaadin-progress-bar.d.ts
  packages/progress-bar/vaadin-progress-bar.js
  packages/upload/package.json
  packages/upload/src/vaadin-upload-file.js
  packages/upload/theme/lumo/vaadin-upload-styles.js
  packages/upload/theme/material/vaadin-upload-styles.js
  packages/vaadin-progress-bar/vaadin-directory-description.md
  test/legacy-component-aliases.test.js
  test/typings/legacy-component-aliases.types.ts
Labels: a11y

#2775 refactor: re-create vaadin-progress-bar package
  packages/vaadin-progress-bar/LICENSE
  packages/vaadin-progress-bar/README.md
  packages/vaadin-progress-bar/package.json
  packages/vaadin-progress-bar/screenshot.gif
  packages/vaadin-progress-bar/src/vaadin-progress-bar.d.ts
  packages/vaadin-progress-bar/src/vaadin-progress-bar.js
  packages/vaadin-progress-bar/theme/lumo/vaadin-progress-bar.js
  packages/vaadin-progress-bar/theme/material/vaadin-progress-bar.js
  packages/vaadin-progress-bar/vaadin-directory-description.md
  packages/vaadin-progress-bar/vaadin-progress-bar.d.ts
  packages/vaadin-progress-bar/vaadin-progress-bar.js
  test/legacy-component-aliases.test.js
  test/typings/legacy-component-aliases.types.ts
Labels: a11y

#2958 test: import root entrypoints in typings tests
  packages/confirm-dialog/test/typings/confirm-dialog.types.ts
  packages/split-layout/test/typings/split-layout.types.ts
Labels: internal
