Repository vaadin/web-components, pull requests merged in 2021-11, with the labels that each got.

#2957 fix: disable row drag and drop while loading
  packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
  packages/grid/test/drag-and-drop.test.js
Labels: target/21.0

#2980 chore: add dev page for grid-pro
  dev/grid-pro.html
Labels: internal

#2981 fix: workaround an issue with disabled textarea freezing the browser
  packages/text-area/src/vaadin-text-area.js
Labels: target/21.0

#2982 chore: add dev page for context-menu
  dev/context-menu.html
Labels: internal

#3002 chore: update Playwright to 1.16.3, fix grid keyboard test
  packages/grid/test/keyboard-navigation.test.js
  yarn.lock
Labels: internal

#3016 fix: use relative position for grid rows
  packages/grid/test/visual/lumo/grid.test.js
  packages/grid/test/visual/lumo/screenshots/grid/baseline/ltr-row-focus-header.png
  packages/grid/test/visual/lumo/screenshots/grid/baseline/rtl-row-focus-header.png
  packages/grid/test/visual/material/grid.test.js
  packages/grid/test/visual/material/screenshots/grid/baseline/ltr-row-focus-header.png
  packages/grid/test/visual/material/screenshots/grid/baseline/rtl-row-focus-header.png
  packages/grid/theme/lumo/vaadin-grid-styles.js
  packages/grid/theme/material/vaadin-grid-styles.js
Labels: target/22.0

#3021 fix: get filtered grid root items from the data provider
  packages/grid/src/vaadin-grid-selection-column.js
  packages/grid/test/selection.test.js
Labels: target/21.0, target/22.0

#2998 fix: make sure each grid section has a tabbable element
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/src/vaadin-grid.js
  packages/grid/test/keyboard-navigation-row-focus.test.js
  packages/grid/test/keyboard-navigation.test.js
  packages/grid/test/visual/lumo/grid.test.js
  packages/grid/test/visual/lumo/screenshots/grid/baseline/ltr-row-focus-header.png
  packages/grid/test/visual/lumo/screenshots/grid/baseline/ltr-row-focus.png
  packages/grid/test/visual/lumo/screenshots/grid/baseline/rtl-row-focus-header.png
  packages/grid/test/visual/lumo/screenshots/grid/baseline/rtl-row-focus.png
  packages/grid/test/visual/material/grid.test.js
  packages/grid/test/visual/material/screenshots/grid/baseline/ltr-row-focus-header.png
  packages/grid/test/visual/material/screenshots/grid/baseline/ltr-row-focus.png
  packages/grid/test/visual/material/screenshots/grid/baseline/rtl-row-focus-header.png
  packages/grid/test/visual/material/screenshots/grid/baseline/rtl-row-focus.png
Labels: target/22.0

#3033 fix: regenerate cell class names after column tree update
  packages/grid/src/vaadin-grid.js
  packages/grid/test/class-name-generator.test.js
Labels: target/21.0, target/22.0

#3042 chore: update dev dependencies versions
  package.json
  yarn.lock
Labels: target/22.0

#2964 fix(grid): consider all headers/footers when calculating columns width
  packages/grid/src/vaadin-grid.js
  packages/grid/test/column-auto-width.test.js
Labels: target/22.0

#3039 fix: stop Escape keydown propagation if the event was handled
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/keyboard.test.js
Labels: target/22.0

#3045 chore: update status badges in README
  README.md
Labels: internal

#3049 docs: improve JSDoc, remove Polymer-specific parts
  packages/combo-box/src/vaadin-combo-box.d.ts
  packages/combo-box/src/vaadin-combo-box.js
Labels: documentation, target/22.0

#3050 refactor: drop support for setting instanceProps
  packages/vaadin-overlay/src/vaadin-overlay.d.ts
  packages/vaadin-overlay/src/vaadin-overlay.js
  packages/vaadin-overlay/test/renderer.test.js
Labels: internal

#3056 chore: use relative imports for virtualizer
  packages/component-base/src/iron-list-core.js
  packages/component-base/src/virtualizer-iron-list-adapter.js
Labels: target/22.0

#3062 feat: add common browser detection utils
  packages/app-layout/src/detect-ios-navbar.js
  packages/component-base/src/browser-utils.js
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/context-menu/src/vaadin-contextmenu-event.js
  packages/custom-field/src/vaadin-custom-field.js
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/src/vaadin-infinite-scroller.js
  packages/grid/src/vaadin-grid.js
  packages/notification/src/vaadin-notification.js
  packages/rich-text-editor/src/vaadin-rich-text-editor.js
  packages/vaadin-overlay/src/vaadin-overlay.js
Labels: target/22.0

#3066 fix: allow null and undefined for errorMessage property
  packages/date-picker/test/typings/date-picker.types.ts
  packages/date-time-picker/test/typings/date-time-picker.types.ts
  packages/field-base/src/field-mixin.d.ts
Labels: target/22.0

#3069 refactor: initialize controllers in ControllerMixin
  packages/checkbox/src/vaadin-checkbox.d.ts
  packages/checkbox/src/vaadin-checkbox.js
  packages/checkbox/test/typings/checkbox.types.ts
  packages/combo-box/src/vaadin-combo-box.d.ts
  packages/combo-box/src/vaadin-combo-box.js
  packages/combo-box/test/typings/combo-box.types.ts
  packages/component-base/index.d.ts
  packages/component-base/index.js
  packages/component-base/src/controller-mixin.d.ts
  packages/component-base/src/controller-mixin.js
  packages/component-base/src/element-mixin.d.ts
  packages/component-base/src/element-mixin.js
  packages/component-base/test/controller-mixin.test.js
  packages/component-base/test/element-mixin.test.js
  packages/date-picker/src/vaadin-date-picker.d.ts
  packages/date-picker/src/vaadin-date-picker.js
  packages/date-picker/test/typings/date-picker.types.ts
  packages/field-base/test/aria-label-controller.test.js
  packages/field-base/test/checked-mixin.test.js
  packages/field-base/test/delegate-focus-mixin.test.js
  packages/field-base/test/field-mixin.test.js
  packages/field-base/test/input-constraints-mixin.test.js
  packages/field-base/test/input-control-mixin.test.js
  packages/field-base/test/input-controller.test.js
  packages/field-base/test/input-field-mixin.test.js
  packages/field-base/test/pattern-mixin.test.js
  packages/field-base/test/text-area-controller.test.js
  packages/number-field/src/vaadin-number-field.d.ts
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/test/typings/number-field.types.ts
  packages/radio-group/src/vaadin-radio-button.d.ts
  packages/radio-group/src/vaadin-radio-button.js
  packages/radio-group/test/typings/radio-button.types.ts
  packages/text-area/src/vaadin-text-area.d.ts
  packages/text-area/src/vaadin-text-area.js
  packages/text-area/test/typings/text-area.types.ts
  packages/text-field/src/vaadin-text-field.d.ts
  packages/text-field/src/vaadin-text-field.js
  packages/text-field/test/typings/text-field.types.ts
  packages/time-picker/src/vaadin-time-picker.d.ts
  packages/time-picker/src/vaadin-time-picker.js
  packages/time-picker/test/typings/time-picker.types.ts
Labels: internal, refactor

#3068 fix: set tabindex on the vaadin-upload-file element
  dev/upload.html
  packages/upload/src/vaadin-upload-file.js
  packages/upload/src/vaadin-upload.js
  packages/upload/test/a11y.test.js
  packages/upload/test/dom/__snapshots__/vaadin-upload-file.test.snap.js
  packages/upload/test/dom/__snapshots__/vaadin-upload.test.snap.js
  packages/upload/test/dom/vaadin-upload-file.test.js
  packages/upload/test/dom/vaadin-upload.test.js
  packages/upload/theme/lumo/vaadin-upload-styles.js
  packages/upload/theme/material/vaadin-upload-styles.js
Labels: target/22.0

#3070 feat: add helpers to detect iOS devices and touch
  packages/combo-box/src/vaadin-combo-box-dropdown.js
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/component-base/src/browser-utils.js
  packages/context-menu/src/vaadin-device-detector.js
  packages/dialog/src/vaadin-dialog-draggable-mixin.js
  packages/grid/src/vaadin-grid.js
  packages/upload/src/vaadin-upload.js
Labels: target/22.0

#3078 fix: include model reference in declaratively bound events
  packages/polymer-legacy-adapter/src/template-renderer-templatizer.js
  packages/polymer-legacy-adapter/test/vaadin-template-renderer.test.js
Labels: target/21.0, target/22.0

#3081 fix: ensure virtualizer re-renders unhidden items
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer.test.js
Labels: target/21.0, target/22.0

#3089 test: add mouseenter event to reduce flakiness
  packages/field-highlighter/test/visual/common.js
Labels: internal

#3085 feat: add type definitions for change event
  packages/combo-box/src/vaadin-combo-box-light.d.ts
  packages/combo-box/src/vaadin-combo-box.d.ts
  packages/combo-box/test/typings/combo-box.types.ts
  packages/custom-field/src/vaadin-custom-field.d.ts
  packages/custom-field/test/typings/custom-field.types.ts
  packages/date-picker/src/vaadin-date-picker-light.d.ts
  packages/date-picker/src/vaadin-date-picker.d.ts
  packages/date-picker/test/typings/date-picker.types.ts
  packages/date-time-picker/src/vaadin-date-time-picker.d.ts
  packages/date-time-picker/test/typings/date-time-picker.types.ts
  packages/email-field/src/vaadin-email-field.d.ts
  packages/email-field/test/typings/email-field.types.ts
  packages/integer-field/src/vaadin-integer-field.d.ts
  packages/integer-field/test/typings/integer-field.types.ts
  packages/number-field/src/vaadin-number-field.d.ts
  packages/number-field/test/typings/number-field.types.ts
  packages/password-field/src/vaadin-password-field.d.ts
  packages/password-field/test/typings/password-field.types.ts
  packages/rich-text-editor/src/vaadin-rich-text-editor.d.ts
  packages/rich-text-editor/test/typings/rich-text-editor.types.ts
  packages/select/src/vaadin-select.d.ts
  packages/select/test/typings/select.types.ts
  packages/text-area/src/vaadin-text-area.d.ts
  packages/text-area/test/typings/text-area.types.ts
  packages/text-field/src/vaadin-text-field.d.ts
  packages/text-field/test/typings/text-field.types.ts
  packages/time-picker/src/vaadin-time-picker.d.ts
  packages/time-picker/test/typings/time-picker.types.ts
Labels: target/22.0

#3082 fix: add missing combo-box mixin classes
  packages/combo-box/src/vaadin-combo-box-light.d.ts
  packages/combo-box/src/vaadin-combo-box.d.ts
  packages/combo-box/test/typings/combo-box.types.ts
Labels: target/22.0

#3086 test: prevent opening add file dialog in tests
  packages/upload/src/vaadin-upload.js
  packages/upload/test/adding-files.test.js
Labels: internal, target/22.0

#3095 chore: update dev dependencies versions
  package.json
  packages/field-highlighter/package.json
  yarn.lock
Labels: internal

#3098 chore: update grid jsdocs to use fetch in the data provider
  packages/grid/src/vaadin-grid.d.ts
  packages/grid/src/vaadin-grid.js
Labels: target/22.0

#3101 test: add missing visual tests for editing item
  packages/crud/test/visual/lumo/crud.test.js
  packages/crud/test/visual/lumo/screenshots/crud/baseline/basic.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-aside-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-aside-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-bottom-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-bottom-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-default-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-default-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/no-toolbar.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-aside-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-aside-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-bottom-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-bottom-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-default-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-default-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/toolbar-visible.png
  packages/crud/test/visual/material/crud.test.js
  packages/crud/test/visual/material/screenshots/crud/baseline/basic.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-aside-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-aside-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-bottom-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-bottom-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-default-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-default-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/no-toolbar.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-aside-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-aside-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-bottom-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-bottom-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-default-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-default-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/toolbar-visible.png
Labels: target/22.0

#3097 fix: restore focus on date picker outside click
  packages/date-picker/src/vaadin-date-picker-light.js
  packages/date-picker/src/vaadin-date-picker.js
  packages/date-picker/test/common.js
  packages/date-picker/test/dropdown.test.js
  packages/grid-pro/test/edit-column-overlay.test.js
  packages/grid-pro/test/helpers.js
Labels: target/22.0

#3088 fix: link form-item label to field via aria-labelledby
  packages/field-base/src/utils.d.ts
  packages/field-base/src/utils.js
  packages/field-base/test/utils.test.js
  packages/form-layout/package.json
  packages/form-layout/src/vaadin-form-item.d.ts
  packages/form-layout/src/vaadin-form-item.js
  packages/form-layout/test/form-item.test.js
Labels: target/22.0

#3106 refactor!: move header, form and buttons to slots
  dev/crud.html
  packages/crud/package.json
  packages/crud/src/vaadin-crud-dialog.js
  packages/crud/src/vaadin-crud.js
  packages/crud/src/vaadin-dialog-layout.js
  packages/crud/test/crud-editor.test.js
  packages/crud/test/crud.test.js
  packages/crud/test/visual/lumo/crud.test.js
  packages/crud/test/visual/lumo/screenshots/crud/baseline/theme-no-border-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/theme-no-border.png
  packages/crud/theme/lumo/vaadin-crud-styles.js
  packages/crud/theme/material/vaadin-crud-styles.js
  packages/crud/theme/vaadin-dialog-layout-overlay-styles.js
Labels: a11y

#3108 refactor!: simplify internal structure to make styling easier
  packages/crud/src/vaadin-crud-dialog.js
  packages/crud/src/vaadin-crud.js
  packages/crud/src/vaadin-dialog-layout.js
  packages/crud/test/crud-editor.test.js
  packages/crud/test/crud.test.js
  packages/crud/theme/lumo/vaadin-crud-styles.js
  packages/crud/theme/material/vaadin-crud-styles.js
  packages/crud/theme/vaadin-dialog-layout-overlay-styles.js
  packages/dialog/src/vaadin-dialog.d.ts
  packages/dialog/src/vaadin-dialog.js
Labels: a11y

#3114 docs: remove incorrectly documented stylable part
  packages/app-layout/src/vaadin-app-layout.d.ts
  packages/app-layout/src/vaadin-app-layout.js
Labels: target/22.0

#3115 refactor: remove no longer needed CSS property
  packages/app-layout/src/vaadin-app-layout.js
Labels: target/22.0

#3113 refactor: remove use of `constant()` as no longer required
  packages/app-layout/src/safe-area-inset.js
Labels: target/22.0

#3120 fix: restore select focus on fullscreen dropdown close
  dev/select.html
  packages/select/src/vaadin-select.js
  packages/select/test/select.test.js
Labels: target/21.0, target/22.0

#3127 fix: add theme to SubMenuItem interface
  packages/menu-bar/src/vaadin-menu-bar.d.ts
Labels: target/22.0

#3130 feat: add default slot support to SlotMixin
  packages/component-base/src/slot-mixin.js
  packages/component-base/test/slot-mixin.test.js
Labels: a11y

#3109 refactor!: use fullscreen attribute to apply styles
  packages/crud/src/vaadin-crud-dialog.js
  packages/crud/src/vaadin-crud.js
  packages/crud/test/crud-editor.test.js
  packages/crud/test/crud.test.js
  packages/crud/test/visual/lumo/crud.test.js
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-fullscreen-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-fullscreen-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-fullscreen-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-fullscreen-new.png
  packages/crud/test/visual/material/crud.test.js
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-fullscreen-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-fullscreen-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-fullscreen-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-fullscreen-new.png
  packages/crud/theme/lumo/vaadin-crud-styles.js
  packages/crud/theme/material/vaadin-crud-styles.js
Labels: a11y
