Repository vaadin/web-components, pull requests merged in 2021-08, with the labels that each got.

#2237 feat: add mixins for input properties and clear button
  packages/field-base/index.d.ts
  packages/field-base/index.js
  packages/field-base/src/clear-button-mixin.d.ts
  packages/field-base/src/clear-button-mixin.js
  packages/field-base/src/input-props-mixin.d.ts
  packages/field-base/src/input-props-mixin.js
  packages/field-base/test/clear-button-mixin.test.js
  packages/field-base/test/input-props-mixin.test.js
Labels: a11y

#2284 feat: add Lumo variants to input container
  packages/input-container/package.json
  packages/input-container/src/vaadin-input-container.js
  packages/input-container/test/visual/lumo/input-container.test.js
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/basic.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/disabled.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/invalid.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/ltr-align-center.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/ltr-align-left.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/ltr-align-right.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/prefix-icon.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/readonly.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/rtl-align-center.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/rtl-align-left.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/rtl-align-right.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/suffix-icon.png
  packages/input-container/theme/lumo/vaadin-input-container-styles.js
  packages/input-container/theme/material/vaadin-input-container-styles.js
Labels: a11y

#2245 feat: add mixins for text-field and related components
  packages/field-base/index.d.ts
  packages/field-base/index.js
  packages/field-base/src/input-field-mixin.d.ts
  packages/field-base/src/input-field-mixin.js
  packages/field-base/src/text-field-mixin.d.ts
  packages/field-base/src/text-field-mixin.js
  packages/field-base/test/input-field-mixin.test.js
  packages/field-base/test/text-field-mixin.test.js
Labels: a11y

#2302 fix: use more strict types for grid properties
  packages/vaadin-grid/src/vaadin-grid-row-details-mixin.d.ts
  packages/vaadin-grid/src/vaadin-grid-row-details-mixin.js
  packages/vaadin-grid/src/vaadin-grid-selection-mixin.d.ts
  packages/vaadin-grid/src/vaadin-grid-selection-mixin.js
  packages/vaadin-grid/test/typings/grid.types.ts
Labels: target/21.0

#2292 feat: add custom field with slotted label and helper
  packages/custom-field/LICENSE
  packages/custom-field/README.md
  packages/custom-field/package.json
  packages/custom-field/src/interfaces.d.ts
  packages/custom-field/src/vaadin-custom-field.d.ts
  packages/custom-field/src/vaadin-custom-field.js
  packages/custom-field/test/.eslintrc.json
  packages/custom-field/test/common.js
  packages/custom-field/test/custom-field.test.js
  packages/custom-field/test/keyboard.test.js
  packages/custom-field/test/slot-wrapper.test.js
  packages/custom-field/test/vaadin-custom-field.js
  packages/custom-field/test/visual/lumo/custom-field.test.js
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-error-message.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label-error-message.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label-helper-text.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/alignment-label.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-default.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-disabled-required.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-disabled.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-error-message.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-helper-text.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-invalid.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-label.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-required.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/basic-value.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/form-layout-item-text-area.png
  packages/custom-field/test/visual/lumo/screenshots/custom-field/baseline/form-layout-label-error-message.png
  packages/custom-field/test/visual/material/custom-field.test.js
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/alignment-error-message.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/alignment-label-error-message.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/alignment-label-helper-text.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/alignment-label.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-default.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-disabled-required.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-disabled.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-error-message.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-helper-text.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-invalid.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-label.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-required.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/basic-value.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/form-layout-item-text-area.png
  packages/custom-field/test/visual/material/screenshots/custom-field/baseline/form-layout-label-error-message.png
  packages/custom-field/theme/lumo/vaadin-custom-field-styles.js
  packages/custom-field/theme/lumo/vaadin-custom-field.js
  packages/custom-field/theme/material/vaadin-custom-field-styles.js
  packages/custom-field/theme/material/vaadin-custom-field.js
  packages/custom-field/vaadin-custom-field.d.ts
  packages/custom-field/vaadin-custom-field.js
Labels: a11y

#2297 fix: correct setting order of columns when we have more than 10 columns
  packages/vaadin-grid/src/vaadin-grid-column-group.js
  packages/vaadin-grid/src/vaadin-grid-column-reordering-mixin.js
  packages/vaadin-grid/src/vaadin-grid-helpers.js
  packages/vaadin-grid/test/column-groups.test.js
Labels: target/20.0, target/21.0

#2274 feat: add text-field using slotted input
  packages/text-field/LICENSE
  packages/text-field/README.md
  packages/text-field/package.json
  packages/text-field/src/vaadin-input-field-shared-styles.js
  packages/text-field/src/vaadin-text-field.d.ts
  packages/text-field/src/vaadin-text-field.js
  packages/text-field/test/.eslintrc.json
  packages/text-field/test/text-field.test.js
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/basic.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/clear-button.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/disabled.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/error-message.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/helper-text.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/label.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/placeholder.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/prefix.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/readonly.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/required.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/rtl-error-message.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/rtl-label.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/rtl-prefix.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/rtl-suffix.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/suffix.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/value.png
  packages/text-field/test/visual/lumo/text-field.test.js
  packages/text-field/test/visual/material/screenshots/text-field/baseline/basic.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/clear-button.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/disabled.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/error-message.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/helper-text.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/label.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/placeholder.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/prefix.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/readonly.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/required.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/rtl-error-message.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/rtl-label.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/rtl-prefix.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/rtl-suffix.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/suffix.png
  packages/text-field/test/visual/material/screenshots/text-field/baseline/value.png
  packages/text-field/test/visual/material/text-field.test.js
  packages/text-field/theme/lumo/vaadin-input-field-shared-styles.js
  packages/text-field/theme/lumo/vaadin-text-field-styles.js
  packages/text-field/theme/lumo/vaadin-text-field.js
  packages/text-field/theme/material/vaadin-input-field-shared-styles.js
  packages/text-field/theme/material/vaadin-text-field-styles.js
  packages/text-field/theme/material/vaadin-text-field.js
  packages/text-field/vaadin-text-field.d.ts
  packages/text-field/vaadin-text-field.js
Labels: a11y

#2306 refactor: cleanup duplicate text-field styles
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/clear-button.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/placeholder.png
  packages/text-field/test/visual/lumo/screenshots/text-field/baseline/value.png
  packages/text-field/theme/lumo/vaadin-input-field-shared-styles.js
Labels: a11y

#2276 feat: add text-area using slotted textarea
  packages/input-container/src/vaadin-input-container.js
  packages/text-area/LICENSE
  packages/text-area/README.md
  packages/text-area/package.json
  packages/text-area/src/vaadin-text-area.d.ts
  packages/text-area/src/vaadin-text-area.js
  packages/text-area/test/.eslintrc.json
  packages/text-area/test/text-area.test.js
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/basic.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/clear-button.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/disabled.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/error-message.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/helper-text.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/label.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/placeholder.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/prefix.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/readonly.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/required.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/suffix.png
  packages/text-area/test/visual/lumo/screenshots/text-area/baseline/value.png
  packages/text-area/test/visual/lumo/text-area.test.js
  packages/text-area/test/visual/material/screenshots/text-area/baseline/basic.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/clear-button.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/disabled.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/error-message.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/helper-text.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/label.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/placeholder.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/prefix.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/readonly.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/required.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/suffix.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/value.png
  packages/text-area/test/visual/material/text-area.test.js
  packages/text-area/theme/lumo/vaadin-text-area-styles.js
  packages/text-area/theme/lumo/vaadin-text-area.js
  packages/text-area/theme/material/vaadin-text-area-styles.js
  packages/text-area/theme/material/vaadin-text-area.js
  packages/text-area/vaadin-text-area.d.ts
  packages/text-area/vaadin-text-area.js
Labels: a11y

#2278 feat: add email-field using slotted input
  packages/email-field/LICENSE
  packages/email-field/README.md
  packages/email-field/package.json
  packages/email-field/src/vaadin-email-field.d.ts
  packages/email-field/src/vaadin-email-field.js
  packages/email-field/test/.eslintrc.json
  packages/email-field/test/email-field.test.js
  packages/email-field/test/visual/lumo/email-field.test.js
  packages/email-field/test/visual/lumo/screenshots/email-field/baseline/placeholder.png
  packages/email-field/test/visual/lumo/screenshots/email-field/baseline/rtl-placeholder.png
  packages/email-field/test/visual/lumo/screenshots/email-field/baseline/rtl-value.png
  packages/email-field/test/visual/lumo/screenshots/email-field/baseline/value.png
  packages/email-field/test/visual/material/email-field.test.js
  packages/email-field/test/visual/material/screenshots/email-field/baseline/placeholder.png
  packages/email-field/test/visual/material/screenshots/email-field/baseline/rtl-placeholder.png
  packages/email-field/test/visual/material/screenshots/email-field/baseline/rtl-value.png
  packages/email-field/test/visual/material/screenshots/email-field/baseline/value.png
  packages/email-field/theme/lumo/vaadin-email-field-styles.js
  packages/email-field/theme/lumo/vaadin-email-field.js
  packages/email-field/theme/material/vaadin-email-field.js
  packages/email-field/vaadin-email-field.d.ts
  packages/email-field/vaadin-email-field.js
Labels: a11y

#2275 feat: add password-field using slotted input
  packages/password-field/LICENSE
  packages/password-field/README.md
  packages/password-field/package.json
  packages/password-field/src/vaadin-password-field.d.ts
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/.eslintrc.json
  packages/password-field/test/password-field.test.js
  packages/password-field/test/visual/lumo/password-field.test.js
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/ltr-basic.png
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/ltr-clear-button.png
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/ltr-reveal-button-hidden.png
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/ltr-value.png
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/rtl-basic.png
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/rtl-clear-button.png
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/rtl-reveal-button-hidden.png
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/rtl-value.png
  packages/password-field/test/visual/material/password-field.test.js
  packages/password-field/test/visual/material/screenshots/password-field/baseline/ltr-basic.png
  packages/password-field/test/visual/material/screenshots/password-field/baseline/ltr-clear-button.png
  packages/password-field/test/visual/material/screenshots/password-field/baseline/ltr-reveal-button-hidden.png
  packages/password-field/test/visual/material/screenshots/password-field/baseline/ltr-value.png
  packages/password-field/test/visual/material/screenshots/password-field/baseline/rtl-basic.png
  packages/password-field/test/visual/material/screenshots/password-field/baseline/rtl-clear-button.png
  packages/password-field/test/visual/material/screenshots/password-field/baseline/rtl-reveal-button-hidden.png
  packages/password-field/test/visual/material/screenshots/password-field/baseline/rtl-value.png
  packages/password-field/theme/lumo/vaadin-password-field-styles.js
  packages/password-field/theme/lumo/vaadin-password-field.js
  packages/password-field/theme/material/vaadin-password-field-styles.js
  packages/password-field/theme/material/vaadin-password-field.js
  packages/password-field/vaadin-password-field.d.ts
  packages/password-field/vaadin-password-field.js
Labels: a11y

#2279 feat: add number-field using slotted input
  packages/number-field/LICENSE
  packages/number-field/README.md
  packages/number-field/package.json
  packages/number-field/src/vaadin-number-field.d.ts
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/test/.eslintrc.json
  packages/number-field/test/number-field.test.js
  packages/number-field/test/visual/lumo/number-field.test.js
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/basic.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/controls.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/disabled.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/error-message.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/helper-text.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/label.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/placeholder.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/prefix.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/readonly.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/required.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/suffix.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/theme-align-right.png
  packages/number-field/test/visual/lumo/screenshots/number-field/baseline/value.png
  packages/number-field/test/visual/material/number-field.test.js
  packages/number-field/test/visual/material/screenshots/number-field/baseline/basic.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/controls.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/disabled.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/error-message.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/helper-text.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/label.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/placeholder.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/prefix.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/readonly.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/required.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/suffix.png
  packages/number-field/test/visual/material/screenshots/number-field/baseline/value.png
  packages/number-field/theme/lumo/vaadin-number-field-styles.js
  packages/number-field/theme/lumo/vaadin-number-field.js
  packages/number-field/theme/material/vaadin-number-field-styles.js
  packages/number-field/theme/material/vaadin-number-field.js
  packages/number-field/vaadin-number-field.d.ts
  packages/number-field/vaadin-number-field.js
Labels: a11y

#2318 fix: do not reset initial invalid state
  packages/field-base/src/input-field-mixin.js
  packages/field-base/test/input-field-mixin.test.js
Labels: a11y

#2323 fix: avoid conflicting style module IDs
  packages/text-field/theme/lumo/vaadin-text-field-styles.js
  packages/text-field/theme/material/vaadin-text-field-styles.js
Labels: a11y

#2312 feat: add indicator part to new fields
  packages/custom-field/src/vaadin-custom-field.js
  packages/custom-field/theme/lumo/vaadin-custom-field-styles.js
  packages/custom-field/theme/material/vaadin-custom-field-styles.js
  packages/number-field/src/vaadin-number-field.js
  packages/text-area/src/vaadin-text-area.js
  packages/text-field/src/vaadin-text-field.js
  packages/text-field/theme/lumo/vaadin-input-field-shared-styles.js
  packages/text-field/theme/material/vaadin-input-field-shared-styles.js
  packages/vaadin-lumo-styles/mixins/required-field.js
  packages/vaadin-material-styles/mixins/required-field.js
Labels: a11y

#2325 fix: dispose of Lit parts after changing a renderer [combo-box, virtual-list]
  packages/vaadin-combo-box/package.json
  packages/vaadin-combo-box/src/vaadin-combo-box-item.js
  packages/vaadin-combo-box/test/item-renderer.test.js
  packages/vaadin-combo-box/test/lit.test.js
  packages/vaadin-virtual-list/package.json
  packages/vaadin-virtual-list/src/vaadin-virtual-list.js
  packages/vaadin-virtual-list/test/lit.test.js
  packages/vaadin-virtual-list/test/virtual-list.test.js
Labels: no-polymer, target/21.0

#2328 fix: dispose of Lit parts after changing a renderer (#2325) (CP: 21.0)
  packages/vaadin-combo-box/package.json
  packages/vaadin-combo-box/src/vaadin-combo-box-item.js
  packages/vaadin-combo-box/test/item-renderer.test.js
  packages/vaadin-combo-box/test/lit.test.js
  packages/vaadin-virtual-list/package.json
  packages/vaadin-virtual-list/src/vaadin-virtual-list.js
  packages/vaadin-virtual-list/test/lit.test.js
  packages/vaadin-virtual-list/test/virtual-list.test.js
Labels: no-polymer

#2316 feat: use semantic HTML tags for the upload
  packages/vaadin-upload/src/vaadin-upload-file.js
  packages/vaadin-upload/src/vaadin-upload.d.ts
  packages/vaadin-upload/src/vaadin-upload.js
  packages/vaadin-upload/test/a11y.test.js
  packages/vaadin-upload/test/keyboard-navigation.test.js
  packages/vaadin-upload/theme/material/vaadin-upload-styles.js
Labels: a11y

#2314 refactor!: restructure and rename field base mixins
  packages/email-field/src/vaadin-email-field.js
  packages/email-field/test/email-field.test.js
  packages/field-base/index.d.ts
  packages/field-base/index.js
  packages/field-base/src/aria-label-mixin.d.ts
  packages/field-base/src/aria-label-mixin.js
  packages/field-base/src/clear-button-mixin.d.ts
  packages/field-base/src/clear-button-mixin.js
  packages/field-base/src/forward-input-props-mixin.d.ts
  packages/field-base/src/forward-input-props-mixin.js
  packages/field-base/src/input-aria-mixin.d.ts
  packages/field-base/src/input-field-mixin.d.ts
  packages/field-base/src/input-field-mixin.js
  packages/field-base/src/input-mixin.d.ts
  packages/field-base/src/input-mixin.js
  packages/field-base/src/input-slot-mixin.d.ts
  packages/field-base/src/input-slot-mixin.js
  packages/field-base/src/pattern-mixin.d.ts
  packages/field-base/src/pattern-mixin.js
  packages/field-base/src/text-field-mixin.d.ts
  packages/field-base/src/text-field-mixin.js
  packages/field-base/test/aria-label-mixin.test.js
  packages/field-base/test/clear-button-mixin.test.js
  packages/field-base/test/delegate-focus-mixin.test.js
  packages/field-base/test/field-aria-mixin.test.js
  packages/field-base/test/forward-input-props-mixin.test.js
  packages/field-base/test/input-field-mixin.test.js
  packages/field-base/test/input-mixin.test.js
  packages/field-base/test/input-slot-mixin.test.js
  packages/field-base/test/pattern-mixin.test.js
  packages/field-base/test/text-field-mixin.test.js
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/test/number-field.test.js
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/password-field.test.js
  packages/text-area/src/vaadin-text-area.js
  packages/text-area/test/text-area.test.js
  packages/text-field/test/text-field.test.js
Labels: a11y, a11y phase 1

#2336 chore: cleanup READMEs for all packages [skip ci]
  README.md
  packages/vaadin-accordion/README.md
  packages/vaadin-app-layout/README.md
  packages/vaadin-avatar/README.md
  packages/vaadin-board/README.md
  packages/vaadin-button/README.md
  packages/vaadin-charts/README.md
  packages/vaadin-checkbox/README.md
  packages/vaadin-combo-box/README.md
  packages/vaadin-confirm-dialog/README.md
  packages/vaadin-context-menu/README.md
  packages/vaadin-control-state-mixin/README.md
  packages/vaadin-cookie-consent/README.md
  packages/vaadin-crud/README.md
  packages/vaadin-custom-field/README.md
  packages/vaadin-date-picker/README.md
  packages/vaadin-date-time-picker/README.md
  packages/vaadin-details/README.md
  packages/vaadin-dialog/README.md
  packages/vaadin-element-mixin/README.md
  packages/vaadin-form-layout/README.md
  packages/vaadin-grid-pro/README.md
  packages/vaadin-grid/README.md
  packages/vaadin-icon/README.md
  packages/vaadin-icons/README.md
  packages/vaadin-item/README.md
  packages/vaadin-list-box/README.md
  packages/vaadin-list-mixin/README.md
  packages/vaadin-login/README.md
  packages/vaadin-lumo-styles/README.md
  packages/vaadin-material-styles/README.md
  packages/vaadin-menu-bar/README.md
  packages/vaadin-messages/README.md
  packages/vaadin-notification/README.md
  packages/vaadin-ordered-layout/README.md
  packages/vaadin-overlay/README.md
  packages/vaadin-progress-bar/README.md
  packages/vaadin-radio-button/README.md
  packages/vaadin-rich-text-editor/README.md
  packages/vaadin-select/README.md
  packages/vaadin-split-layout/README.md
  packages/vaadin-tabs/README.md
  packages/vaadin-template-renderer/README.md
  packages/vaadin-text-field/README.md
  packages/vaadin-themable-mixin/README.md
  packages/vaadin-time-picker/README.md
  packages/vaadin-upload/README.md
  packages/vaadin-virtual-list/README.md
Labels: documentation, target/20.0, target/21.0

#2342 chore: bump web-test-runner dependencies
  package.json
  yarn.lock
Labels: internal, target/20.0, target/21.0

#2280 feat: add integer-field using slotted input
  packages/integer-field/LICENSE
  packages/integer-field/README.md
  packages/integer-field/package.json
  packages/integer-field/src/vaadin-integer-field.d.ts
  packages/integer-field/src/vaadin-integer-field.js
  packages/integer-field/test/.eslintrc.json
  packages/integer-field/test/integer-field.test.js
  packages/integer-field/test/visual/lumo/integer-field.test.js
  packages/integer-field/test/visual/lumo/screenshots/integer-field/baseline/basic.png
  packages/integer-field/test/visual/lumo/screenshots/integer-field/baseline/controls.png
  packages/integer-field/test/visual/lumo/screenshots/integer-field/baseline/value.png
  packages/integer-field/test/visual/material/integer-field.test.js
  packages/integer-field/test/visual/material/screenshots/integer-field/baseline/basic.png
  packages/integer-field/test/visual/material/screenshots/integer-field/baseline/controls.png
  packages/integer-field/test/visual/material/screenshots/integer-field/baseline/value.png
  packages/integer-field/theme/lumo/vaadin-integer-field.js
  packages/integer-field/theme/material/vaadin-integer-field.js
  packages/integer-field/vaadin-integer-field.d.ts
  packages/integer-field/vaadin-integer-field.js
Labels: a11y

#2345 fix: add reveal button focus ring styles
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/password-field.test.js
  packages/password-field/test/visual/lumo/password-field.test.js
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/ltr-reveal-button-focus.png
  packages/password-field/test/visual/lumo/screenshots/password-field/baseline/rtl-reveal-button-focus.png
  packages/password-field/test/visual/material/password-field.test.js
  packages/password-field/test/visual/material/screenshots/password-field/baseline/ltr-reveal-button-focus.png
  packages/password-field/test/visual/material/screenshots/password-field/baseline/rtl-reveal-button-focus.png
  packages/password-field/theme/lumo/vaadin-password-field-styles.js
  packages/password-field/theme/material/vaadin-password-field-styles.js
Labels: a11y

#2346 feat: add i18n property to password-field
  packages/password-field/src/vaadin-password-field.d.ts
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/password-field.test.js
Labels: a11y

#2352 fix: set font smoothing to slotted input
  packages/text-field/theme/lumo/vaadin-input-field-shared-styles.js
  packages/text-field/theme/material/vaadin-input-field-shared-styles.js
Labels: a11y

#2347 chore: bump chai dev dependency version
  packages/custom-field/package.json
  packages/email-field/package.json
  packages/field-base/package.json
  packages/input-container/package.json
  packages/integer-field/package.json
  packages/number-field/package.json
  packages/password-field/package.json
  packages/text-area/package.json
  packages/text-field/package.json
  packages/vaadin-accordion/package.json
  packages/vaadin-app-layout/package.json
  packages/vaadin-avatar/package.json
  packages/vaadin-board/package.json
  packages/vaadin-button/package.json
  packages/vaadin-charts/package.json
  packages/vaadin-checkbox/package.json
  packages/vaadin-combo-box/package.json
  packages/vaadin-confirm-dialog/package.json
  packages/vaadin-context-menu/package.json
  packages/vaadin-control-state-mixin/package.json
  packages/vaadin-cookie-consent/package.json
  packages/vaadin-crud/package.json
  packages/vaadin-custom-field/package.json
  packages/vaadin-date-picker/package.json
  packages/vaadin-date-time-picker/package.json
  packages/vaadin-details/package.json
  packages/vaadin-dialog/package.json
  packages/vaadin-element-mixin/package.json
  packages/vaadin-form-layout/package.json
  packages/vaadin-grid-pro/package.json
  packages/vaadin-grid/package.json
  packages/vaadin-item/package.json
  packages/vaadin-list-box/package.json
  packages/vaadin-list-mixin/package.json
  packages/vaadin-login/package.json
  packages/vaadin-menu-bar/package.json
  packages/vaadin-messages/package.json
  packages/vaadin-notification/package.json
  packages/vaadin-ordered-layout/package.json
  packages/vaadin-overlay/package.json
  packages/vaadin-progress-bar/package.json
  packages/vaadin-radio-button/package.json
  packages/vaadin-rich-text-editor/package.json
  packages/vaadin-select/package.json
  packages/vaadin-split-layout/package.json
  packages/vaadin-tabs/package.json
  packages/vaadin-template-renderer/package.json
  packages/vaadin-text-field/package.json
  packages/vaadin-themable-mixin/package.json
  packages/vaadin-time-picker/package.json
  packages/vaadin-upload/package.json
  packages/vaadin-virtual-list/package.json
  yarn.lock
Labels: internal, target/21.0

#2350 refactor: restructure mixins to fix text-area
  packages/field-base/index.d.ts
  packages/field-base/index.js
  packages/field-base/src/aria-label-mixin.d.ts
  packages/field-base/src/aria-label-mixin.js
  packages/field-base/src/char-length-mixin.d.ts
  packages/field-base/src/char-length-mixin.js
  packages/field-base/src/forward-input-props-mixin.d.ts
  packages/field-base/src/forward-input-props-mixin.js
  packages/field-base/src/input-constraints-mixin.d.ts
  packages/field-base/src/input-constraints-mixin.js
  packages/field-base/src/input-field-mixin.d.ts
  packages/field-base/src/input-field-mixin.js
  packages/field-base/src/pattern-mixin.js
  packages/field-base/src/text-area-slot-mixin.d.ts
  packages/field-base/src/text-area-slot-mixin.js
  packages/field-base/src/text-field-mixin.d.ts
  packages/field-base/src/text-field-mixin.js
  packages/field-base/test/aria-label-mixin.test.js
  packages/field-base/test/char-length-mixin.test.js
  packages/field-base/test/forward-input-props-mixin.test.js
  packages/field-base/test/input-constraints-mixin.test.js
  packages/field-base/test/input-field-mixin.test.js
  packages/field-base/test/pattern-mixin.test.js
  packages/field-base/test/text-area-slot-mixin.test.js
  packages/field-base/test/text-field-mixin.test.js
  packages/number-field/src/vaadin-number-field.d.ts
  packages/number-field/src/vaadin-number-field.js
  packages/text-area/src/vaadin-text-area.d.ts
  packages/text-area/src/vaadin-text-area.js
  packages/text-field/src/vaadin-text-field.d.ts
  packages/text-field/src/vaadin-text-field.js
Labels: a11y

#2320 refactor!: move email field to new package
  packages/custom-field/package.json
  packages/custom-field/test/visual/lumo/custom-field.test.js
  packages/custom-field/test/visual/material/custom-field.test.js
  packages/email-field/README.md
  packages/email-field/src/vaadin-email-field.d.ts
  packages/email-field/src/vaadin-email-field.js
  packages/email-field/test/email-field.test.js
  packages/email-field/test/typings/email-field.types.ts
  packages/email-field/test/visual/lumo/email-field.test.js
  packages/email-field/test/visual/material/email-field.test.js
  packages/email-field/vaadin-email-field.d.ts
  packages/email-field/vaadin-email-field.js
  packages/vaadin-text-field/package.json
  packages/vaadin-text-field/src/vaadin-email-field.d.ts
  packages/vaadin-text-field/src/vaadin-email-field.js
  packages/vaadin-text-field/test/email-field.test.js
  packages/vaadin-text-field/test/validation.test.js
  packages/vaadin-text-field/theme/lumo/vaadin-email-field-styles.js
  packages/vaadin-text-field/theme/lumo/vaadin-email-field.js
  packages/vaadin-text-field/theme/material/vaadin-email-field.js
Labels: a11y

#2319 refactor!: move password field to new package
  packages/custom-field/package.json
  packages/custom-field/test/visual/lumo/custom-field.test.js
  packages/custom-field/test/visual/material/custom-field.test.js
  packages/password-field/README.md
  packages/password-field/src/vaadin-password-field.d.ts
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/password-field.test.js
  packages/password-field/test/typings/password-field.types.ts
  packages/password-field/test/visual/lumo/password-field.test.js
  packages/password-field/test/visual/material/password-field.test.js
  packages/password-field/vaadin-password-field.d.ts
  packages/password-field/vaadin-password-field.js
  packages/vaadin-login/package.json
  packages/vaadin-login/src/vaadin-login-form.js
  packages/vaadin-login/theme/lumo/vaadin-login-form.js
  packages/vaadin-login/theme/material/vaadin-login-form.js
  packages/vaadin-text-field/package.json
  packages/vaadin-text-field/src/vaadin-password-field.d.ts
  packages/vaadin-text-field/src/vaadin-password-field.js
  packages/vaadin-text-field/test/password-field.test.js
  packages/vaadin-text-field/test/typings/text-field.types.ts
  packages/vaadin-text-field/test/validation.test.js
  packages/vaadin-text-field/test/visual/lumo/password-field.test.js
  packages/vaadin-text-field/test/visual/lumo/screenshots/password-field/baseline/ltr-basic.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/password-field/baseline/ltr-clear-button.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/password-field/baseline/ltr-reveal-button-hidden.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/password-field/baseline/ltr-value.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/password-field/baseline/rtl-basic.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/password-field/baseline/rtl-clear-button.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/password-field/baseline/rtl-reveal-button-hidden.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/password-field/baseline/rtl-value.png
  packages/vaadin-text-field/test/visual/material/password-field.test.js
  packages/vaadin-text-field/test/visual/material/screenshots/password-field/baseline/ltr-basic.png
  packages/vaadin-text-field/test/visual/material/screenshots/password-field/baseline/ltr-clear-button.png
  packages/vaadin-text-field/test/visual/material/screenshots/password-field/baseline/ltr-reveal-button-hidden.png
  packages/vaadin-text-field/test/visual/material/screenshots/password-field/baseline/ltr-value.png
  packages/vaadin-text-field/test/visual/material/screenshots/password-field/baseline/rtl-basic.png
  packages/vaadin-text-field/test/visual/material/screenshots/password-field/baseline/rtl-clear-button.png
  packages/vaadin-text-field/test/visual/material/screenshots/password-field/baseline/rtl-reveal-button-hidden.png
  packages/vaadin-text-field/test/visual/material/screenshots/password-field/baseline/rtl-value.png
  packages/vaadin-text-field/theme/lumo/vaadin-password-field-styles.js
  packages/vaadin-text-field/theme/lumo/vaadin-password-field.js
  packages/vaadin-text-field/theme/material/vaadin-password-field-styles.js
  packages/vaadin-text-field/theme/material/vaadin-password-field.js
Labels: a11y

#2361 feat: add upload buttons focus-ring styles
  packages/vaadin-upload/test/visual/lumo/screenshots/upload/baseline/focus-clear.png
  packages/vaadin-upload/test/visual/lumo/screenshots/upload/baseline/focus-file.png
  packages/vaadin-upload/test/visual/lumo/screenshots/upload/baseline/focus-retry.png
  packages/vaadin-upload/test/visual/lumo/screenshots/upload/baseline/focus-start.png
  packages/vaadin-upload/test/visual/lumo/upload.test.js
  packages/vaadin-upload/test/visual/material/screenshots/upload/baseline/focus-clear.png
  packages/vaadin-upload/test/visual/material/screenshots/upload/baseline/focus-file.png
  packages/vaadin-upload/test/visual/material/screenshots/upload/baseline/focus-retry.png
  packages/vaadin-upload/test/visual/material/screenshots/upload/baseline/focus-start.png
  packages/vaadin-upload/test/visual/material/screenshots/upload/baseline/ltr-files.png
  packages/vaadin-upload/test/visual/material/screenshots/upload/baseline/rtl-files.png
  packages/vaadin-upload/test/visual/material/upload.test.js
  packages/vaadin-upload/theme/lumo/vaadin-upload-styles.js
  packages/vaadin-upload/theme/material/vaadin-upload-styles.js
Labels: a11y

#2358 refactor!: migrate number and integer fields
  packages/integer-field/README.md
  packages/integer-field/src/vaadin-integer-field.d.ts
  packages/integer-field/src/vaadin-integer-field.js
  packages/integer-field/test/integer-field.test.js
  packages/integer-field/test/typings/integer-field.types.ts
  packages/integer-field/test/visual/lumo/integer-field.test.js
  packages/integer-field/test/visual/material/integer-field.test.js
  packages/integer-field/vaadin-integer-field.d.ts
  packages/integer-field/vaadin-integer-field.js
  packages/number-field/README.md
  packages/number-field/src/vaadin-number-field.d.ts
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/test/number-field.test.js
  packages/number-field/test/typings/number-field.types.ts
  packages/number-field/test/visual/lumo/number-field.test.js
  packages/number-field/test/visual/material/number-field.test.js
  packages/number-field/vaadin-number-field.d.ts
  packages/number-field/vaadin-number-field.js
  packages/vaadin-text-field/package.json
  packages/vaadin-text-field/src/vaadin-integer-field.d.ts
  packages/vaadin-text-field/src/vaadin-integer-field.js
  packages/vaadin-text-field/src/vaadin-number-field.d.ts
  packages/vaadin-text-field/src/vaadin-number-field.js
  packages/vaadin-text-field/test/integer-field.test.js
  packages/vaadin-text-field/test/number-field.test.js
  packages/vaadin-text-field/test/validation.test.js
  packages/vaadin-text-field/test/visual/lumo/number-field.test.js
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/basic.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/controls.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/disabled.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/error-message.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/helper-text.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/label.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/placeholder.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/prefix.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/readonly.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/required.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/suffix.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/theme-align-right.png
  packages/vaadin-text-field/test/visual/lumo/screenshots/number-field/baseline/value.png
  packages/vaadin-text-field/test/visual/material/number-field.test.js
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/basic.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/controls.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/disabled.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/error-message.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/helper-text.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/label.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/placeholder.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/prefix.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/readonly.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/required.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/suffix.png
  packages/vaadin-text-field/test/visual/material/screenshots/number-field/baseline/value.png
  packages/vaadin-text-field/theme/lumo/vaadin-integer-field.js
  packages/vaadin-text-field/theme/lumo/vaadin-number-field-styles.js
  packages/vaadin-text-field/theme/lumo/vaadin-number-field.js
  packages/vaadin-text-field/theme/material/vaadin-integer-field.js
  packages/vaadin-text-field/theme/material/vaadin-number-field-styles.js
  packages/vaadin-text-field/theme/material/vaadin-number-field.js
Labels: a11y

#2348 perf: reduce charts initialization time up to ~2x
  packages/vaadin-charts/src/vaadin-chart.js
  packages/vaadin-charts/test/chart-element.test.js
Labels: target/20.0, target/21.0

#2365 test: fix version regex to allow RC (#1999) (#2051)
  packages/vaadin-rich-text-editor/test/basic.test.js
Labels: internal, target/21.0

#2371 test: use focusin and focusout helpers
  packages/vaadin-avatar/test/avatar.test.js
  packages/vaadin-control-state-mixin/test/control-state-mixin.test.js
  packages/vaadin-custom-field/test/basic.test.js
  packages/vaadin-grid-pro/test/edit-column-overlay.test.js
  packages/vaadin-grid-pro/test/edit-column-renderer.test.js
  packages/vaadin-grid-pro/test/edit-column-type.test.js
  packages/vaadin-grid-pro/test/edit-column.test.js
  packages/vaadin-grid/test/keyboard-navigation.test.js
  packages/vaadin-menu-bar/test/menu-bar.test.js
  packages/vaadin-rich-text-editor/test/a11y.test.js
  packages/vaadin-rich-text-editor/test/basic.test.js
  packages/vaadin-time-picker/test/form-input.test.js
Labels: internal

#2374 refactor: split code into smaller methods
  packages/vaadin-menu-bar/src/vaadin-menu-bar-buttons-mixin.js
  packages/vaadin-menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Labels: a11y

#2383 chore: format README using Prettier
  README.md
  packages/button/README.md
Labels: internal

#2384 feat: add i18n property to menu bar
  packages/vaadin-menu-bar/src/interfaces.d.ts
  packages/vaadin-menu-bar/src/vaadin-menu-bar.d.ts
  packages/vaadin-menu-bar/src/vaadin-menu-bar.js
  packages/vaadin-menu-bar/test/menu-bar.test.js
Labels: a11y, a11y phase 1

#2415 refactor!: move vaadin-select to select
  packages/custom-field/test/visual/lumo/custom-field.test.js
  packages/custom-field/test/visual/material/custom-field.test.js
  packages/select/LICENSE
  packages/select/README.md
  packages/select/package.json
  packages/select/screenshot.gif
  packages/select/src/interfaces.d.ts
  packages/select/src/vaadin-select-overlay.js
  packages/select/src/vaadin-select-text-field.js
  packages/select/src/vaadin-select.d.ts
  packages/select/src/vaadin-select.js
  packages/select/test/.eslintrc.json
  packages/select/test/accessibility.test.js
  packages/select/test/renderer.test.js
  packages/select/test/scrollable-viewport.test.js
  packages/select/test/select.test.js
  packages/select/test/template.test.js
  packages/select/test/typings/select.types.ts
  packages/select/test/visual/lumo/screenshots/select/baseline/basic.png
  packages/select/test/visual/lumo/screenshots/select/baseline/disabled.png
  packages/select/test/visual/lumo/screenshots/select/baseline/error-message.png
  packages/select/test/visual/lumo/screenshots/select/baseline/helper-text.png
  packages/select/test/visual/lumo/screenshots/select/baseline/label.png
  packages/select/test/visual/lumo/screenshots/select/baseline/opened.png
  packages/select/test/visual/lumo/screenshots/select/baseline/placeholder.png
  packages/select/test/visual/lumo/screenshots/select/baseline/prefix.png
  packages/select/test/visual/lumo/screenshots/select/baseline/readonly.png
  packages/select/test/visual/lumo/screenshots/select/baseline/required.png
  packages/select/test/visual/lumo/screenshots/select/baseline/value.png
  packages/select/test/visual/lumo/select.test.js
  packages/select/test/visual/material/screenshots/select/baseline/basic.png
  packages/select/test/visual/material/screenshots/select/baseline/disabled.png
  packages/select/test/visual/material/screenshots/select/baseline/error-message.png
  packages/select/test/visual/material/screenshots/select/baseline/helper-text.png
  packages/select/test/visual/material/screenshots/select/baseline/label.png
  packages/select/test/visual/material/screenshots/select/baseline/opened.png
  packages/select/test/visual/material/screenshots/select/baseline/placeholder.png
  packages/select/test/visual/material/screenshots/select/baseline/prefix.png
  packages/select/test/visual/material/screenshots/select/baseline/readonly.png
  packages/select/test/visual/material/screenshots/select/baseline/required.png
  packages/select/test/visual/material/screenshots/select/baseline/value.png
  packages/select/test/visual/material/select.test.js
  packages/select/theme/lumo/vaadin-select-styles.js
  packages/select/theme/lumo/vaadin-select.js
  packages/select/theme/material/vaadin-select-styles.js
  packages/select/theme/material/vaadin-select.js
  packages/select/vaadin-directory-description.md
  packages/select/vaadin-select.d.ts
  packages/select/vaadin-select.js
  packages/vaadin-custom-field/package.json
  packages/vaadin-custom-field/test/visual/lumo/custom-field.test.js
  packages/vaadin-custom-field/test/visual/material/custom-field.test.js
  packages/vaadin-grid-pro/package.json
  packages/vaadin-grid-pro/src/vaadin-grid-pro-edit-select.js
  packages/vaadin-grid-pro/test/edit-column-type.test.js
  packages/vaadin-grid-pro/theme/lumo/vaadin-grid-pro-edit-select.js
  packages/vaadin-grid-pro/theme/material/vaadin-grid-pro-edit-select.js
Labels: a11y

#2416 refactor: re-export new select package
  packages/vaadin-select/LICENSE
  packages/vaadin-select/README.md
  packages/vaadin-select/package.json
  packages/vaadin-select/screenshot.gif
  packages/vaadin-select/src/vaadin-select.d.ts
  packages/vaadin-select/src/vaadin-select.js
  packages/vaadin-select/theme/lumo/vaadin-select.js
  packages/vaadin-select/theme/material/vaadin-select.js
  packages/vaadin-select/vaadin-directory-description.md
  packages/vaadin-select/vaadin-select.d.ts
  packages/vaadin-select/vaadin-select.js
  wtr-utils.js
Labels: a11y, a11y phase 1

#2424 chore: bump test-runner, simplify test packages detection
  package.json
  wtr-utils.js
  yarn.lock
Labels: internal

#2397 refactor: improve overflow detection to handle theme change
  packages/vaadin-menu-bar/src/vaadin-menu-bar-buttons-mixin.js
  packages/vaadin-menu-bar/test/menu-bar.test.js
  packages/vaadin-menu-bar/test/visual/lumo/menu-bar.test.js
  packages/vaadin-menu-bar/test/visual/material/menu-bar.test.js
  packages/vaadin-menu-bar/theme/material/vaadin-menu-bar-button-styles.js
Labels: a11y, a11y phase 1
