Repository vaadin/web-components, pull requests merged in 2022-07, with the labels that each got.

#4140 fix: clear selection when using `clear()` method
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/accessibility.test.js
  packages/multi-select-combo-box/test/selecting-items.test.js
Labels: target/23.1

#4141 fix: clear selection on clear button touchend
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/basic.test.js
Labels: target/23.1

#4152 fix: check if input is focused instead of using attribute
  packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/basic.test.js
  packages/time-picker/test/keyboard-navigation.test.js
Labels: target/23.1

#4191 docs: add disabled attribute to styling API
  packages/menu-bar/src/vaadin-menu-bar.d.ts
  packages/menu-bar/src/vaadin-menu-bar.js
Labels: target/23.1

#4193 docs: add missing JSDoc annotation for mixin
  packages/menu-bar/src/vaadin-menu-bar.js
Labels: target/23.1

#4166 fix: focus the input on change event in Safari
  packages/checkbox/test/checkbox.test.js
  packages/field-base/src/checked-mixin.js
  packages/field-base/test/checked-mixin.test.js
  packages/radio-group/test/radio-button.test.js
Labels: target/22.0, target/23.0, target/23.1

#4240 fix: prevent mousedown event for toggle button
  packages/select/src/vaadin-select.js
  packages/select/test/select.test.js
Labels: target/22.0, target/23.0, target/23.1

#4248 docs: add missing theme property type
  packages/combo-box/src/vaadin-combo-box-light.d.ts
  packages/combo-box/src/vaadin-combo-box.d.ts
  packages/combo-box/test/typings/combo-box.types.ts
  packages/grid/src/vaadin-grid.d.ts
  packages/grid/test/typings/grid.types.ts
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
  packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
Labels: target/23.1

#4250 refactor: cleanup no longer needed styles
  packages/grid/theme/lumo/vaadin-grid-styles.js
Labels: target/22.0, target/23.0, target/23.1

#4264 fix: select an input element when focusing
  packages/component-base/src/focus-trap-controller.js
  packages/component-base/test/focus-trap-controller.test.js
Labels: target/23.0, target/23.1
