Repository vaadin/web-components, pull requests merged in 2022-01, with the labels that each got.

#3238 feat: add helper for screen reader announcements
  packages/component-base/src/a11y-announcer.d.ts
  packages/component-base/src/a11y-announcer.js
  packages/component-base/test/a11y-announcer.test.js
Labels: a11y

#3239 refactor: use a11y-announcer in avatar-group
  dev/avatar-group.html
  packages/avatar-group/package.json
  packages/avatar-group/src/vaadin-avatar-group.js
  packages/avatar-group/test/avatar-group.test.js
  packages/avatar/package.json
Labels: a11y

#3240 refactor: use a11y-announcer in field highlighter
  packages/field-highlighter/package.json
  packages/field-highlighter/src/vaadin-field-highlighter.js
  packages/field-highlighter/test/field-highlighter.test.js
Labels: a11y

#3243 refactor: use a11y-announcer in date-picker
  packages/date-picker/package.json
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/test/wai-aria.test.js
Labels: a11y

#3250 refactor: remove obsolete IE11 workaround
  packages/vaadin-material-styles/color.js
Labels: target/22.0

#3254 fix: use correct 1-based index for aria-posinset
  packages/combo-box/src/vaadin-combo-box-scroller.js
  packages/combo-box/test/aria.test.js
  packages/time-picker/test/aria.test.js
Labels: a11y, target/22.0

#3259 fix: change grid table role to treegrid
  packages/grid/src/vaadin-grid.js
  packages/grid/test/accessibility.test.js
Labels: target/22.0

#3265 chore: fix typos detected by cspell
  packages/crud/src/vaadin-crud.d.ts
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/src/vaadin-grid-selection-column.js
  packages/grid/test/scroll-to-index.test.js
  packages/polymer-legacy-adapter/src/template-renderer-templatizer.js
  packages/vaadin-list-mixin/vaadin-list-mixin.js
  packages/vaadin-overlay/src/vaadin-overlay.js
  packages/vaadin-themable-mixin/test/register-styles.test.js
  packages/vaadin-themable-mixin/vaadin-themable-mixin.js
Labels: internal

#3185 refactor: extract helper logic to HelperController
  packages/field-base/src/field-mixin.js
  packages/field-base/src/helper-controller.d.ts
  packages/field-base/src/helper-controller.js
  packages/field-base/test/field-mixin.test.js
  packages/select/test/accessibility.test.js
Labels: a11y, target/22.0

#3263 fix: prevent grid body from expanding on dragover
  packages/grid/src/vaadin-grid.d.ts
  packages/grid/src/vaadin-grid.js
  packages/grid/test/basic.test.js
  packages/grid/test/visual/lumo/grid.test.js
  packages/grid/test/visual/lumo/screenshots/grid/baseline/dragover-below-last-row-all-rows-visible.png
  packages/grid/test/visual/material/grid.test.js
  packages/grid/test/visual/material/screenshots/grid/baseline/dragover-below-last-row-all-rows-visible.png
  packages/grid/theme/lumo/vaadin-grid-styles.js
  packages/grid/theme/material/vaadin-grid-styles.js
Labels: target/22.0

#3208 fix: prevent closing overlays when interacting with notifications
  packages/notification/src/vaadin-notification.js
  packages/notification/test/notification.test.js
Labels: target/22.0

#3219 fix: ensure focused month is visible when receiving focus
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/src/vaadin-infinite-scroller.js
  packages/date-picker/test/overlay.test.js
  packages/date-picker/test/visual/material/screenshots/date-picker/baseline/ltr-dropdown.png
  packages/date-picker/test/visual/material/screenshots/date-picker/baseline/rtl-dropdown.png
  packages/date-picker/theme/material/vaadin-date-picker-overlay-content-styles.js
Labels: target/22.0

#3272 fix: correctly assign menuElement in all cases
  dev/select.html
  packages/select/src/vaadin-select-overlay.js
  packages/select/src/vaadin-select.js
  packages/select/test/select.test.js
  packages/select/test/visual/lumo/screenshots/select/baseline/opened.png
  packages/select/test/visual/material/screenshots/select/baseline/opened.png
Labels: target/22.0

#3278 chore: add custom-field dev page
  dev/custom-field.html
Labels: internal

#3279 fix: do not override custom helper on attach
  packages/field-base/src/helper-controller.js
  packages/field-base/test/field-mixin.test.js
Labels: a11y, target/22.0

#3283 fix: ensure cell is connected before rendering
  packages/grid/src/vaadin-grid-column.js
  packages/grid/test/column.test.js
Labels: target/22.0

#3285 fix: flush virtualizer before measuring column auto-width
  packages/grid/src/vaadin-grid.js
  packages/grid/test/column-auto-width.test.js
Labels: target/22.0

#3302 fix: consider a value matching selected item label a known value
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/basic.test.js
  packages/combo-box/test/scrolling.test.js
Labels: target/22.0

#3305 fix: prevent long value from overflowing select
  packages/select/src/vaadin-select-value-button.js
  packages/select/test/visual/lumo/screenshots/select/baseline/value-overflow.png
  packages/select/test/visual/lumo/screenshots/select/baseline/width-value.png
  packages/select/test/visual/lumo/select.test.js
  packages/select/test/visual/material/screenshots/select/baseline/value-overflow.png
  packages/select/test/visual/material/select.test.js
Labels: target/22.0

#3307 fix: update items on clear button click
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/src/vaadin-combo-box-scroller.js
  packages/combo-box/test/selecting-items.test.js
Labels: target/22.0

#3310 fix: restore missing logic for focused state
  packages/date-time-picker/src/vaadin-date-time-picker.d.ts
  packages/date-time-picker/src/vaadin-date-time-picker.js
  packages/date-time-picker/test/basic.test.js
  packages/date-time-picker/test/visual/lumo/date-time-picker.test.js
  packages/date-time-picker/test/visual/lumo/screenshots/date-time-picker/baseline/focused.png
  packages/date-time-picker/test/visual/material/date-time-picker.test.js
  packages/date-time-picker/test/visual/material/screenshots/date-time-picker/baseline/focused.png
Labels: target/22.0

#3315 fix: disable autocomplete for date-picker
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/wai-aria.test.js
Labels: target/22.0

#3318 fix: remove unnecessary [has-label] selectors
  packages/vaadin-lumo-styles/mixins/input-field-shared.js
Labels: target/22.0

#3320 fix: validate on input event when invalid
  packages/field-base/src/input-field-mixin.js
  packages/field-base/test/input-field-mixin.test.js
Labels: target/22.0

#3329 fix: restore focused element reference on size change
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/test/keyboard-navigation.test.js
Labels: target/22.0

#3332 fix: only accept a focusable child element as a focus target
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/test/keyboard-navigation.test.js
Labels: target/22.0

#3327 fix: extend clickable area to handle clicks as expected
  dev/radio-group.html
  packages/radio-group/src/vaadin-radio-button.js
Labels: target/22.0

#3326 refactor: convert SlotTargetMixin to controller
  packages/checkbox/src/vaadin-checkbox.d.ts
  packages/checkbox/src/vaadin-checkbox.js
  packages/field-base/src/slot-label-mixin.d.ts
  packages/field-base/src/slot-label-mixin.js
  packages/field-base/src/slot-target-controller.d.ts
  packages/field-base/src/slot-target-controller.js
  packages/field-base/src/slot-target-mixin.d.ts
  packages/field-base/src/slot-target-mixin.js
  packages/field-base/test/slot-label-mixin.test.js
  packages/field-base/test/slot-target-controller.test.js
  packages/field-base/test/slot-target-mixin.test.js
  packages/radio-group/src/vaadin-radio-button.d.ts
  packages/radio-group/src/vaadin-radio-button.js
Labels: target/22.0

#3347 fix: don't update items manually on selection change
  packages/grid/src/vaadin-grid-column.js
  packages/grid/src/vaadin-grid-selection-mixin.js
  packages/grid/test/selection.test.js
Labels: target/22.0

#3349 fix: set aria-hidden on year scroller container
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/test/wai-aria.test.js
Labels: a11y, target/22.0

#3352 fix: update details cell visibility when details renderer set
  packages/grid/src/vaadin-grid-row-details-mixin.js
  packages/grid/test/row-details.test.js
Labels: target/22.0

#3270 refactor: move errorMessage logic to ErrorController
  packages/component-base/src/slot-controller.js
  packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
  packages/field-base/src/error-controller.d.ts
  packages/field-base/src/error-controller.js
  packages/field-base/src/field-mixin.js
  packages/field-base/test/field-mixin.test.js
  packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js
  packages/message-input/test/dom/__snapshots__/message-input.test.snap.js
  packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
  packages/password-field/src/vaadin-password-field.d.ts
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
  packages/select/test/dom/__snapshots__/select.test.snap.js
  packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
  packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
Labels: target/22.0

#3355 refactor!: update month calendar to use table
  packages/date-picker/src/vaadin-month-calendar.js
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/month-calendar.test.js
  packages/date-picker/test/wai-aria.test.js
Labels: a11y

#3360 fix: align footer border-radius with overlay container
  packages/confirm-dialog/theme/lumo/vaadin-confirm-dialog-styles.js
Labels: target/22.0
