Repository vaadin/web-components, pull requests merged in 2022-03, with the labels that each got.

#3502 fix: import vaadin-iconset in main entrypoint
  packages/vaadin-lumo-styles/all-imports.js
Labels: target/22.0

#3506 fix: do not expand to full available width
  packages/menu-bar/src/vaadin-menu-bar.js
  packages/menu-bar/test/menu-bar.test.js
Labels: target/22.0

#3525 fix: hide overflowing tree-toggle content
  packages/grid/src/vaadin-grid-tree-toggle.js
  packages/grid/test/visual/lumo/grid.test.js
  packages/grid/test/visual/lumo/screenshots/grid/baseline/tree-default.png
  packages/grid/test/visual/lumo/screenshots/grid/baseline/tree-overflow.png
  packages/grid/test/visual/material/grid.test.js
  packages/grid/test/visual/material/screenshots/grid/baseline/tree-default.png
  packages/grid/test/visual/material/screenshots/grid/baseline/tree-overflow.png
Labels: target/22.0

#3511 fix: use margin for centered theme variant
  packages/tabs/test/visual/lumo/screenshots/tabs/baseline/ltr-horizontal-centered-scroll.png
  packages/tabs/test/visual/lumo/screenshots/tabs/baseline/ltr-horizontal-centered.png
  packages/tabs/test/visual/lumo/screenshots/tabs/baseline/rtl-horizontal-centered-scroll.png
  packages/tabs/test/visual/lumo/screenshots/tabs/baseline/rtl-horizontal-centered.png
  packages/tabs/test/visual/lumo/tabs.test.js
  packages/tabs/theme/lumo/vaadin-tabs-styles.js
Labels: target/22.0

#3527 fix: reset stored column order on mousedown
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/test/keyboard-navigation.test.js
Labels: target/22.0

#3533 fix: do not fail when saving a new item when using dataProvider
  packages/crud/src/vaadin-crud.js
  packages/crud/test/crud.test.js
Labels: target/22.0

#3534 fix: revert setting align-self to stretch
  packages/menu-bar/src/vaadin-menu-bar.js
  packages/menu-bar/test/visual/lumo/menu-bar.test.js
  packages/menu-bar/test/visual/lumo/screenshots/menu-bar/baseline/ltr-flex-overflow.png
  packages/menu-bar/test/visual/lumo/screenshots/menu-bar/baseline/rtl-flex-overflow.png
  packages/menu-bar/test/visual/material/menu-bar.test.js
  packages/menu-bar/test/visual/material/screenshots/menu-bar/baseline/ltr-flex-overflow.png
  packages/menu-bar/test/visual/material/screenshots/menu-bar/baseline/rtl-flex-overflow.png
Labels: target/22.0

#3544 fix: use correct styles for week numbers
  packages/date-picker/src/vaadin-month-calendar.js
  packages/date-picker/test/visual/lumo/date-picker.test.js
  packages/date-picker/test/visual/lumo/screenshots/date-picker/baseline/ltr-week-numbers.png
  packages/date-picker/test/visual/lumo/screenshots/date-picker/baseline/rtl-week-numbers.png
  packages/date-picker/test/visual/material/date-picker.test.js
  packages/date-picker/test/visual/material/screenshots/date-picker/baseline/ltr-week-numbers.png
  packages/date-picker/test/visual/material/screenshots/date-picker/baseline/rtl-week-numbers.png
  packages/date-picker/theme/lumo/vaadin-month-calendar-styles.js
Labels: target/23.0

#3565 fix: do not delegate focus when clicking on non-focusable child
  packages/field-base/src/shadow-focus-mixin.js
  packages/field-base/test/shadow-focus-mixin.test.js
Labels: target/22.0, target/23.0

#3573 chore: fix flaky shadow focus mixin test
  packages/field-base/test/shadow-focus-mixin.test.js
Labels: target/23.0

#3558 fix: update dataProvider when grid is set
  packages/crud/src/vaadin-crud.js
  packages/crud/test/crud.test.js
Labels: target/22.0, target/23.0

#3577 fix: restore focused attribute behavior
  packages/field-base/src/shadow-focus-mixin.js
  packages/field-base/test/shadow-focus-mixin.test.js
Labels: target/22.0, target/23.0

#3584 fix: do not throw when setting theme attribute
  packages/date-time-picker/src/vaadin-date-time-picker.js
  packages/date-time-picker/test/basic.test.js
Labels: target/22.0, target/23.0

#3587 fix: do not dispatch cell-focus on mouse up outside of cell
  packages/grid/src/vaadin-grid.js
  packages/grid/test/keyboard-navigation.test.js
Labels: target/22.0, target/23.0

#3589 fix: improve resizing column min width logic
  packages/grid/src/vaadin-grid-column-resizing-mixin.js
  packages/grid/test/column-resizing.test.js
Labels: target/22.0, target/23.0

#3604 fix: material button alignment in Firefox
  packages/button/theme/material/vaadin-button-styles.js
Labels: target/23.0

#3606 fix: readonly select value should use secondary text color
  packages/select/test/visual/lumo/screenshots/select/baseline/readonly.png
  packages/select/test/visual/lumo/select.test.js
  packages/select/theme/lumo/vaadin-select-styles.js
Labels: target/23.0

#3603 fix: propagate enter key event when combo box is not opened
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/keyboard.test.js
Labels: target/22.0, target/23.0

#3600 fix: don't prevent custom values when autoOpenDisabled
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/external-filtering.test.js
  packages/combo-box/test/internal-filtering.test.js
  packages/time-picker/test/combo-box.test.js
Labels: target/23.0
