Repository vaadin/web-components, pull requests merged in 2022-12, with the labels that each got.

#5095 docs: remove Polymer specific demo from API docs
  packages/crud/src/vaadin-crud.d.ts
  packages/crud/src/vaadin-crud.js
Labels: target/23.1, target/23.2, target/23.3

#5092 fix: check for bad input when updating _hasInputValue
  packages/field-base/src/input-mixin.d.ts
  packages/field-base/src/input-mixin.js
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/test/number-field.test.js
Labels: target/23.3

#5112 docs: add JSDoc to DatePickerI18n interface
  packages/date-picker/src/vaadin-date-picker-mixin.d.ts
Labels: target/23.3

#5128 perf: reduce grid updateHeaderFooterRowVisibility call count
  packages/grid/src/vaadin-grid-column.js
  packages/grid/src/vaadin-grid.js
  packages/grid/test/column-groups.test.js
  packages/grid/test/dom/__snapshots__/grid.test.snap.js
Labels: target/23.3

#5130 refactor: reduce grid updateFrozenColumn call count
  packages/grid/src/vaadin-grid-column-reordering-mixin.js
  packages/grid/src/vaadin-grid-column.js
  packages/grid/src/vaadin-grid-scroll-mixin.js
  packages/grid/src/vaadin-grid.js
  packages/grid/test/column-reordering.test.js
  packages/grid/test/column-resizing.test.js
  packages/grid/test/frozen-columns.test.js
  packages/grid/test/helpers.js
Labels: target/23.3

#5153 fix: check cell parent before debouncing
  packages/grid/src/vaadin-grid-column.js
  packages/grid/test/column.test.js
Labels: target/23.3

#5152 fix: remove whitespace from tooltip overlay content
  packages/tooltip/src/vaadin-tooltip-overlay.js
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/white-space-pre.png
  packages/tooltip/test/visual/lumo/tooltip.test.js
  packages/tooltip/test/visual/material/screenshots/tooltip/baseline/white-space-pre.png
  packages/tooltip/test/visual/material/tooltip.test.js
Labels: target/23.3

#5151 fix!: change default tooltip delay from 0 to 500ms
  integration/tests/component-tooltip.test.js
  integration/tests/grid-tooltip.test.js
  integration/tests/menu-bar-tooltip.test.js
  packages/tooltip/src/vaadin-tooltip.js
  packages/tooltip/test/tooltip-offset.test.js
  packages/tooltip/test/tooltip-position.test.js
  packages/tooltip/test/tooltip-timers.test.js
  packages/tooltip/test/tooltip.test.js
  packages/tooltip/test/visual/lumo/tooltip.test.js
  packages/tooltip/test/visual/material/tooltip.test.js
Labels: target/23.3

#5158 test: update avatar visual tests tooltip delay
  packages/avatar/test/visual/lumo/avatar.test.js
  packages/avatar/test/visual/material/avatar.test.js
Labels: target/23.3

#5161 fix: support appending tabs in tabsheet lazily
  packages/tabsheet/src/vaadin-tabsheet.js
  packages/tabsheet/test/tabsheet.test.js
Labels: target/23.3

#5175 fix: propagate autocapitalize attribute in Chrome
  packages/field-base/src/input-field-mixin.js
  packages/field-base/test/input-field-mixin.test.js
  packages/login/test/dom/__snapshots__/login-form.test.snap.js
  packages/login/test/dom/__snapshots__/login-overlay.test.snap.js
Labels: target/23.2, target/23.3

#5179 docs: remove incorrect usage of DisabledMixin types
  packages/field-base/src/input-constraints-mixin.d.ts
  packages/field-base/src/pattern-mixin.d.ts
Labels: target/23.3
