Repository vaadin/web-components, pull requests merged in 2022-09, with the labels that each got.

#4440 docs: add missing attribute JSDoc annotation
  packages/avatar/src/vaadin-avatar.d.ts
  packages/avatar/src/vaadin-avatar.js
Labels: target/23.1, target/23.2

#4441 docs: update vaadin-tabs JSDoc description
  packages/tabs/src/vaadin-tabs.d.ts
  packages/tabs/src/vaadin-tabs.js
Labels: target/23.1, target/23.2

#4450 chore: add missing vaadin-map screenshot
  packages/map/README.md
  packages/map/screenshot.png
Labels: target/23.1, target/23.2

#4454 fix: handle toggling visibility when recalculating column widths
  packages/grid/src/vaadin-grid.js
  packages/grid/test/column-auto-width.test.js
Labels: target/23.1, target/23.2

#4455 chore: add vaadin-multi-select-combo-box screenshot
  packages/multi-select-combo-box/README.md
  packages/multi-select-combo-box/screenshot.png
Labels: target/23.1, target/23.2

#4462 docs: add missing attribute JSDoc annotation
  packages/avatar-group/src/vaadin-avatar-group.d.ts
  packages/avatar-group/src/vaadin-avatar-group.js
Labels: target/23.1, target/23.2

#4468 chore: use patch-package to patch Lerna version
  package.json
  patches/@lerna+version+4.0.0.patch
  yarn.lock
Labels: target/23.0, target/23.1, target/23.2

#4478 fix: do not validate when focus is moving inside the field
  packages/date-time-picker/src/vaadin-date-time-picker.js
  packages/date-time-picker/test/validation.test.js
Labels: target/23.1, target/23.2

#4487 test: disable animations in time-picker tests
  packages/time-picker/test/combo-box.test.js
  packages/time-picker/test/keyboard-navigation.test.js
  packages/time-picker/test/not-animated-styles.js
  packages/time-picker/test/time-picker.test.js
Labels: target/23.1, target/23.2

#4488 refactor: cleanup validation methods typings
  packages/date-picker/src/vaadin-date-picker-mixin.d.ts
  packages/time-picker/src/vaadin-time-picker.d.ts
  packages/time-picker/test/typings/time-picker.types.ts
Labels: target/23.2

#4498 refactor: cleanup checkValidity typings override
  packages/custom-field/src/vaadin-custom-field.d.ts
Labels: target/23.2

#4505 docs: add missing attribute JSDoc annotations
  packages/message-list/src/vaadin-message.d.ts
  packages/message-list/src/vaadin-message.js
Labels: target/23.1, target/23.2

#4518 docs: fix custom-field state attributes API docs
  packages/custom-field/src/vaadin-custom-field.d.ts
  packages/custom-field/src/vaadin-custom-field.js
Labels: target/23.1, target/23.2

#4525 chore: remove import for enable on map dev page
  dev/map.html
Labels: target/23.2

#4537 fix: add missing event declarations to JS API docs
  scripts/prepareDocs.js
Labels: target/22.0, target/23.1, target/23.2

#4546 test: ignore a flaky test on Firefox
  packages/grid/test/scrolling-mode.test.js
Labels: target/23.1, target/23.2

#4556 chore: add missing JSDoc annotations to methods
  packages/message-list/src/vaadin-message-list.js
Labels: target/23.1, target/23.2

#4562 fix: do not throw on content update with undefined columns
  packages/grid/src/vaadin-grid.js
  packages/grid/test/missing-imports.test.js
Labels: target/23.1, target/23.2

#4571 fix: use correct styles to hide input placeholder
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
Labels: target/23.1, target/23.2

#4575 docs: add missing attribute JSDoc annotation
  packages/field-base/src/input-control-mixin.d.ts
  packages/field-base/src/input-control-mixin.js
Labels: target/23.2

#4577 fix: inject placeholder styles to correct root node
  packages/field-base/src/input-control-mixin.d.ts
  packages/field-base/src/input-control-mixin.js
  packages/field-base/src/input-field-mixin.d.ts
  packages/input-container/src/vaadin-input-container.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/number-field/src/vaadin-number-field.d.ts
  packages/number-field/src/vaadin-number-field.js
  packages/password-field/src/vaadin-password-field.d.ts
  packages/password-field/src/vaadin-password-field.js
Labels: target/23.2

#4588 fix: enforce dash case for event names in docs
  scripts/prepareDocs.js
Labels: target/22.0, target/23.1, target/23.2

#4561 fix: request pages asynchronously when scrolling
  packages/combo-box/src/vaadin-combo-box-scroller.js
  packages/combo-box/test/dynamic-size.test.js
  packages/combo-box/test/lazy-loading.test.js
Labels: target/23.1, target/23.2

#4598 fix: do not clear data provider cache when readonly
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/readonly.test.js
Labels: target/23.1, target/23.2

#4633 fix: use feature detection for iOS dnd polyfilling
  packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
  packages/grid/test/drag-and-drop.test.js
  packages/grid/theme/lumo/vaadin-grid-styles.js
  packages/grid/theme/material/vaadin-grid-styles.js
Labels: target/23.1, target/23.2

#4637 refactor: remove obsolete overlay positioning logic from menu bar
  packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Labels: target/23.1, target/23.2

#4641 fix: escape regex operators in upload accept pattern
  packages/upload/src/vaadin-upload.js
  packages/upload/test/adding-files.test.js
Labels: target/22.0, target/23.1, target/23.2
