Repository vaadin/web-components, pull requests merged in 2022-10, with the labels that each got.

#4657 fix: use translate instead of margin for tree toggle
  packages/grid/test/column-auto-width.test.js
  packages/grid/theme/lumo/vaadin-grid-tree-toggle-styles.js
Labels: target/23.1, target/23.2

#4664 refactor: remove unused part styles
  packages/date-time-picker/src/vaadin-date-time-picker.js
Labels: target/22.0, target/23.1, target/23.2

#4668 fix: do not allow any interaction when disabled
  packages/date-time-picker/src/vaadin-date-time-picker.js
Labels: target/22.0, target/23.1, target/23.2

#4689 fix: do not update position on scroll events inside the overlay
  packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js
  packages/vaadin-overlay/test/position-mixin-listeners.test.js
Labels: target/23.1, target/23.2

#4693 chore: update GitHub Actions to latest versions
  .github/workflows/coverage.yml
  .github/workflows/unit-tests.yml
  .github/workflows/verify.yml
  .github/workflows/visual-tests.yml
Labels: target/23.1, target/23.2

#4703 fix: ensure variable item height virtualizer scrolls to top
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-variable-row-height.test.js
Labels: target/23.1, target/23.2

#4709 fix: update content offset when navbar height changes
  packages/app-layout/src/vaadin-app-layout.js
  packages/app-layout/test/app-layout.test.js
Labels: target/23.1, target/23.2

#4713 fix: add missing hidden styles to message-input
  packages/message-input/src/vaadin-message-input.js
  packages/message-input/test/message-input.test.js
Labels: target/22.0, target/23.1, target/23.2

#4718 fix: avoid triggering connected callback from disconnected callback
  packages/component-base/src/dir-mixin.js
  packages/component-base/test/dir-mixin.test.js
Labels: target/23.1, target/23.2

#4724 fix: close overflow avatar overlay on detach
  packages/avatar-group/src/vaadin-avatar-group.js
  packages/avatar-group/test/avatar-group.test.js
  packages/avatar-group/test/visual/lumo/avatar-group.test.js
  packages/avatar-group/test/visual/material/avatar-group.test.js
Labels: target/22.0, target/23.1, target/23.2

#4729 refactor: use relative imports in component-base
  packages/component-base/src/a11y-announcer.js
  packages/component-base/src/active-mixin.js
  packages/component-base/test/dir-mixin.test.js
Labels: target/23.1, target/23.2

#4740 refactor: use relative import in menu-overlay mixin
  packages/vaadin-material-styles/mixins/menu-overlay.js
Labels: target/23.1, target/23.2

#4759 fix: ensure focused date is visible if overlay is small (CP: 24)
  integration/tests/dialog-date-picker.test.js
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/src/vaadin-infinite-scroller.js
  packages/date-picker/test/overlay.test.js
  packages/date-picker/test/visual/lumo/screenshots/date-picker/baseline/ltr-dropdown.png
  packages/date-picker/test/visual/lumo/screenshots/date-picker/baseline/ltr-week-numbers.png
  packages/date-picker/test/visual/lumo/screenshots/date-picker/baseline/rtl-dropdown.png
  packages/date-picker/test/visual/lumo/screenshots/date-picker/baseline/rtl-week-numbers.png
  packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js
Labels: target/23.1, target/23.2, target/23.3

#4771 refactor: remove no longer used code from date-picker
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/theme/material/vaadin-date-picker-overlay-content-styles.js
Labels: target/22.0, target/23.1, target/23.2, target/23.3

#4777 refactor: small code style tweaks, add missing JSDoc
  packages/date-picker/src/vaadin-infinite-scroller.js
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/common.js
  packages/date-picker/test/overlay.test.js
  packages/date-picker/test/scroller.test.js
  packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js
Labels: target/23.1, target/23.2, target/23.3

#4783 fix: add support for setting custom role attribute
  packages/avatar/src/vaadin-avatar.js
  packages/avatar/test/avatar.test.js
Labels: target/22.0, target/23.1, target/23.2, target/23.3

#4793 fix: make sure virtualizer clears item placeholder height
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-item-height.test.js
Labels: target/23.1, target/23.2, target/23.3

#4798 refactor: remove unused code from date-picker
  packages/date-picker/src/vaadin-date-picker-styles.js
  packages/date-picker/src/vaadin-month-calendar.js
Labels: target/23.1, target/23.2, target/23.3

#4802 chore: update actions/upload-artifact to v3
  .github/workflows/visual-tests.yml
Labels: target/22.0, target/23.1, target/23.2, target/23.3

#4813 test: update input-container Lumo test screenshots
  packages/input-container/test/visual/lumo/input-container.test.js
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/basic.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/disabled.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/invalid.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/ltr-align-center.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/ltr-align-left.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/ltr-align-right.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/prefix-icon.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/readonly.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/rtl-align-center.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/rtl-align-left.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/rtl-align-right.png
  packages/input-container/test/visual/lumo/screenshots/input-container/baseline/suffix-icon.png
Labels: target/23.1, target/23.2, target/23.3

#4819 fix: hide tooltip while scrolling
  integration/tests/grid-tooltip.test.js
  packages/grid/src/vaadin-grid-scroll-mixin.js
  packages/grid/src/vaadin-grid.js
  packages/grid/test/helpers.js
Labels: target/23.3

#4823 fix: consider any custom element a non-empty helper
  packages/field-base/src/helper-controller.js
  packages/field-base/test/field-mixin.test.js
Labels: target/22.0, target/23.1, target/23.2, target/23.3

#4828 fix: focus entered date on open with auto-open disabled
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/keyboard-input.test.js
Labels: target/22.0, target/23.1, target/23.2, target/23.3

#4833 fix: set default max-width: 40ch on the tooltip overlay
  packages/tooltip/src/vaadin-tooltip-overlay.js
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/max-width.png
  packages/tooltip/test/visual/lumo/tooltip.test.js
  packages/tooltip/test/visual/material/screenshots/tooltip/baseline/max-width.png
  packages/tooltip/test/visual/material/tooltip.test.js
Labels: target/23.3

#4837 fix: use small line height for Tooltip (Lumo)
  packages/avatar/test/visual/lumo/screenshots/avatar/baseline/tooltip.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/bottom-end.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/bottom-start.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/bottom.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/end-bottom.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/end-top.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/end.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/max-width.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/start-bottom.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/start-top.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/start.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/theme-dark.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/top-end.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/top-start.png
  packages/tooltip/test/visual/lumo/screenshots/tooltip/baseline/top.png
  packages/tooltip/theme/lumo/vaadin-tooltip-styles.js
Labels: target/23.3

#4792 feat: add custom reference date functionality to date picker
  packages/date-picker/src/vaadin-date-picker-helper.d.ts
  packages/date-picker/src/vaadin-date-picker-helper.js
  packages/date-picker/src/vaadin-date-picker-mixin.d.ts
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/keyboard-input.test.js
  packages/date-time-picker/src/vaadin-date-time-picker.js
Labels: target/23.3

#4852 fix: close tooltip when opening another overlay
  integration/tests/component-tooltip.test.js
  packages/tooltip/src/vaadin-tooltip.js
  packages/tooltip/test/tooltip.test.js
Labels: target/23.3

#4855 test: update Material theme map controls screenshot
  packages/map/test/visual/material/screenshots/map/baseline/controls-all-controls.png
Labels: target/23.1, target/23.2, target/23.3

#4862 fix: allow navigating and removing chips while opened
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/basic.test.js
Labels: target/23.1, target/23.2, target/23.3
