Repository vaadin/web-components, pull requests merged in 2022-05, with the labels that each got.

#3769 fix: focus selected item set before filtered items
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/external-filtering.test.js
Labels: target/22.0, target/23.0

#3789 fix: run the class name generator only for loaded rows
  packages/grid/src/vaadin-grid-styling-mixin.js
  packages/grid/test/class-name-generator.test.js
Labels: target/23.0

#3793 test: make keyboard tests more reliable
  packages/date-picker/test/keyboard-navigation.test.js
Labels: target/23.0

#3816 fix: update event types to use correct detail object
  packages/grid-pro/src/vaadin-grid-pro.d.ts
  packages/grid-pro/test/typings/grid-pro.types.ts
Labels: target/22.0, target/23.0

#3821 fix: prevent overriding column hidden state when attaching column group (#3805) (CP: 23)
  packages/grid/src/vaadin-grid-column-group.js
  packages/grid/test/column-group.test.js
Labels: target/22.0

#3826 refactor: extract method for updating overflow
  packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js
Labels: target/22.0, target/23.0

#3830 fix: close a notification on detach
  dev/notification.html
  packages/notification/src/vaadin-notification.js
  packages/notification/test/notification.test.js
Labels: target/23.0

#3829 refactor: add option to observe parent resize
  packages/component-base/src/resize-mixin.d.ts
  packages/component-base/src/resize-mixin.js
  packages/component-base/test/resize-mixin.test.js
Labels: target/23.0

#3824 fix: observe parent resize to detect overflow
  packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js
  packages/menu-bar/test/menu-bar.test.js
Labels: target/23.0

#3838 fix: do not throw on Tab if grid has tabindex
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/test/keyboard-navigation.test.js
Labels: target/22.0, target/23.0

#3849 chore: make sure iron-list internal properties are in sync
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-scrolling.test.js
Labels: target/23.0

#3845 refactor: Improve performance of SelectionMixinClass#isSelected
  packages/grid/src/vaadin-grid-selection-mixin.js
Labels: target/22.0, target/23.0

#3854 refactor: use PositionMixin instead of custom positioning logic
  packages/field-highlighter/src/vaadin-user-tags-overlay.js
  packages/field-highlighter/src/vaadin-user-tags.js
  packages/field-highlighter/test/field-highlighter.test.js
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/checkbox-group.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/checkbox.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/date-time-picker-focused.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/date-time-picker.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/list-box-focused.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/list-box.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/text-area-focused.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/text-area.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/text-field-focused.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/text-field.png
Labels: target/22.0, target/23.0

#3863 fix: set focused index but not scroll into view
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/src/vaadin-combo-box-scroller.js
  packages/combo-box/test/lazy-loading.test.js
Labels: target/22.0, target/23.0

#3868 refactor: update cached keys to use computed properties
  packages/grid/src/vaadin-grid-data-provider-mixin.js
  packages/grid/src/vaadin-grid-selection-mixin.js
Labels: target/23.0

#3874 refactor: cleanup date-picker overlay content logic
  packages/date-picker/src/vaadin-date-picker-light.js
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/src/vaadin-date-picker.js
Labels: target/23.0

#3876 test: simplify date-picker-light unit tests
  packages/date-picker/test/custom-input.test.js
Labels: target/23.0

#3883 fix: call stopPropagation() when clearing on Esc
  packages/field-base/src/input-control-mixin.js
  packages/field-base/test/input-control-mixin.test.js
Labels: target/22.0, target/23.0

#3888 fix: import themed overlay with themed extensions
  packages/avatar-group/theme/lumo/vaadin-avatar-group.js
  packages/avatar-group/theme/material/vaadin-avatar-group.js
  packages/combo-box/theme/material/vaadin-combo-box-dropdown-styles.js
  packages/context-menu/theme/lumo/vaadin-context-menu.js
  packages/context-menu/theme/material/vaadin-context-menu.js
  packages/date-picker/theme/lumo/vaadin-date-picker-overlay-styles.js
  packages/date-picker/theme/material/vaadin-date-picker-overlay-styles.js
  packages/dialog/theme/lumo/vaadin-dialog.js
  packages/dialog/theme/material/vaadin-dialog.js
  packages/field-highlighter/theme/lumo/vaadin-user-tags.js
  packages/field-highlighter/theme/material/vaadin-user-tags.js
  packages/select/theme/lumo/vaadin-select.js
  packages/select/theme/material/vaadin-select.js
Labels: target/23.0

#3886 fix: prevent toggling overlay opened state when filtering
  packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js
  packages/combo-box/test/lazy-loading.test.js
Labels: target/22.0, target/23.0

#3901 refactor: remove obsolete overlay content code
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
Labels: target/22.0, target/23.0

#3908 refactor: make virtualizer use dynamic placeholder height
  packages/combo-box/test/dynamic-size.test.js
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-item-height.test.js
  packages/component-base/test/virtualizer-reorder-elements.test.js
Labels: target/23.0

#3870 fix: allow modeless overlay to close on Esc
  packages/vaadin-overlay/src/vaadin-overlay.js
  packages/vaadin-overlay/test/multiple.test.js
Labels: target/23.0

#3913 fix: update incorrect fullscreen mode focus logic
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/basic.test.js
Labels: target/23.0

#3919 fix: do not stop propagation of Esc when fullscreen
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/test/basic.test.js
Labels: target/23.0

#3921 fix: close all menus when pressing Tab
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/context-menu/test/items.test.js
Labels: target/22.0, target/23.0

#3922 fix: initialize date-picker-light overlay properly
  packages/date-picker/src/vaadin-date-picker-light.js
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/src/vaadin-date-picker.js
  packages/date-picker/test/custom-input.test.js
Labels: target/22.0, target/23.0

#3933 fix: clear time-picker with clear button on Esc
  packages/time-picker/src/vaadin-time-picker.js
  packages/time-picker/test/time-picker.test.js
Labels: target/22.0, target/23.0

#3954 fix: prevent default for click event on open
  packages/select/src/vaadin-select.js
  packages/select/test/select.test.js
Labels: target/22.0, target/23.0

#3957 fix: prevent default for combo-box click on open
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/toggling-dropdown.test.js
Labels: target/22.0, target/23.0

#3963 chore: combine tests jobs into workflows
  .github/workflows/chrome.yml
  .github/workflows/firefox.yml
  .github/workflows/lumo.yml
  .github/workflows/material.yml
  .github/workflows/unit-tests.yml
  .github/workflows/visual-tests.yml
  .github/workflows/webkit.yml
Labels: target/22.0, target/23.0

#3952 refactor: use PositionMixin instead of custom logic
  packages/avatar-group/src/vaadin-avatar-group-overlay.js
  packages/avatar-group/src/vaadin-avatar-group.js
  packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js
Labels: target/23.0

#3973 fix: prevent default for date-picker click on open
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/basic.test.js
Labels: target/22.0, target/23.0
