Repository vaadin/web-components, pull requests merged in 2022-11, with the labels that each got.

#4876 test: fix tooltip ITs to get rid of delay flakiness
  integration/tests/grid-tooltip.test.js
  integration/tests/menu-bar-tooltip.test.js
Labels: target/23.3

#4882 feat: add multiSortOnShiftClick property
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/src/vaadin-grid-sort-mixin.d.ts
  packages/grid/src/vaadin-grid-sort-mixin.js
  packages/grid/src/vaadin-grid-sorter.d.ts
  packages/grid/src/vaadin-grid-sorter.js
  packages/grid/test/helpers.js
  packages/grid/test/keyboard-navigation.test.js
  packages/grid/test/sorting.test.js
  packages/grid/test/typings/grid.types.ts
Labels: target/23.3

#4888 refactor: cleanup no longer needed login-form code
  packages/login/src/vaadin-login-form.d.ts
  packages/login/src/vaadin-login-form.js
Labels: target/22.0, target/23.1, target/23.2, target/23.3

#4905 refactor!: do not notify properties set from outside
  packages/login/src/vaadin-login-mixin.js
  packages/login/src/vaadin-login-overlay.js
Labels: target/23.3

#4910 feat: add crud-edit and crud-edit-column entrypoints
  packages/crud/test/typings/crud.types.ts
  packages/crud/vaadin-crud-edit-column.d.ts
  packages/crud/vaadin-crud-edit-column.js
  packages/crud/vaadin-crud-edit.d.ts
  packages/crud/vaadin-crud-edit.js
Labels: target/23.3

#4904 fix: add missing types for properties notify events
  packages/login/src/vaadin-login-form.d.ts
  packages/login/src/vaadin-login-form.js
  packages/login/src/vaadin-login-overlay.d.ts
  packages/login/src/vaadin-login-overlay.js
  packages/login/test/typings/login.types.ts
Labels: target/23.1, target/23.2, target/23.3

#4907 fix: add missing index property to CrudEditEvent
  packages/crud/src/vaadin-crud.d.ts
  packages/crud/test/typings/crud.types.ts
Labels: target/23.1, target/23.2, target/23.3

#4908 feat: add root entrypoint for vaadin-chart-series
  packages/charts/test/typings/chart.types.ts
  packages/charts/vaadin-chart-series.d.ts
  packages/charts/vaadin-chart-series.js
Labels: target/23.3

#4917 fix: make row details renderer arguments required
  packages/grid/src/vaadin-grid-row-details-mixin.d.ts
  packages/grid/test/typings/grid.types.ts
Labels: target/23.1, target/23.2, target/23.3

#4918 fix: make context menu renderer arguments required
  packages/context-menu/src/vaadin-context-menu.d.ts
  packages/context-menu/test/typings/context-menu.types.ts
Labels: target/23.1, target/23.2, target/23.3

#4919 fix: make dialog renderer owner argument required
  packages/dialog/src/vaadin-dialog.d.ts
  packages/dialog/test/typings/dialog.types.ts
Labels: target/23.1, target/23.2, target/23.3

#4906 fix: add missing event map to vaadin-accordion-panel
  packages/accordion/src/vaadin-accordion-panel.d.ts
  packages/accordion/test/typings/accordion.types.ts
Labels: target/23.1, target/23.2, target/23.3

#4934 fix: make notification renderer argument required
  packages/notification/src/vaadin-notification.d.ts
  packages/notification/test/typings/notification.types.ts
Labels: target/23.1, target/23.2, target/23.3

#4935 feat: add IntelliJ auto-complete support for Lumo theme
  .gitignore
  package.json
  packages/vaadin-lumo-styles/package.json
  scripts/generateLumoAutoCompleteCss.js
Labels: target/23.3

#4949 fix: do not set form theme attribute to undefined
  packages/crud/src/vaadin-crud.js
  packages/crud/test/dom/__snapshots__/crud.test.snap.js
Labels: target/23.1, target/23.2, target/23.3

#4961 docs: add slots for editor buttons to JSDoc
  packages/crud/src/vaadin-crud.d.ts
  packages/crud/src/vaadin-crud.js
Labels: target/23.1, target/23.2, target/23.3

#4965 docs: fix incorrect mixin and controller JSDoc
  packages/field-base/src/error-controller.js
  packages/field-base/src/label-mixin.js
Labels: target/23.1, target/23.2, target/23.3

#4981 fix: make select renderer owner argument required
  packages/select/src/vaadin-select.d.ts
  packages/select/test/typings/select.types.ts
Labels: target/23.1, target/23.2, target/23.3

#4990 refactor: cleanup duplicate imports for Lumo modules
  packages/grid/theme/lumo/vaadin-grid.js
Labels: target/23.3

#5006 refactor: move private RTL direction getter to DirMixin
  packages/avatar-group/src/vaadin-avatar-group.js
  packages/component-base/src/dir-mixin.d.ts
  packages/component-base/src/dir-mixin.js
  packages/context-menu/src/vaadin-contextmenu-items-mixin.d.ts
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/grid/src/vaadin-grid-column-resizing-mixin.js
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/src/vaadin-grid.js
  packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/overlay/src/vaadin-overlay-position-mixin.js
  packages/radio-group/src/vaadin-radio-group.js
  packages/split-layout/src/vaadin-split-layout.js
  packages/tabs/src/vaadin-tabs.js
Labels: target/23.3

#5015 docs: format attributes table, add frozen-to-end
  packages/grid/src/vaadin-grid.d.ts
  packages/grid/src/vaadin-grid.js
Labels: target/23.1, target/23.2, target/23.3

#5027 fix: update MultiSelectListMixin type definitions
  packages/list-box/test/typings/list-box.types.ts
  packages/vaadin-list-mixin/vaadin-multi-select-list-mixin.d.ts
Labels: target/23.1, target/23.2, target/23.3

#5028 docs: add missing private JSDoc annotations
  packages/grid/src/vaadin-grid-data-provider-mixin.js
  packages/grid/src/vaadin-grid-styling-mixin.js
  packages/grid/src/vaadin-grid.js
Labels: target/23.1, target/23.2, target/23.3

#4969 fix: make sure frozenToEnd cells align to the end of the viewport
  packages/grid/src/vaadin-grid-styles.js
  packages/grid/test/frozen-columns.test.js
Labels: target/23.1, target/23.2, target/23.3

#5049 fix: set aria-hidden="true" on prefix and suffix
  packages/button/src/vaadin-button.js
  packages/button/test/dom/__snapshots__/button.test.snap.js
Labels: target/22.0, target/23.1, target/23.2, target/23.3

#5061 fix: do not set pointer events on rows and cells
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/src/vaadin-grid-styles.js
Labels: target/23.1, target/23.2, target/23.3

#5076 fix: clear value when committing invalid input
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/keyboard-input.test.js
  packages/date-picker/test/validation.test.js
Labels: target/23.3

#5089 fix: ignore sorter click if event is canceled
  packages/grid/src/vaadin-grid-sorter.js
  packages/grid/test/sorting.test.js
Labels: target/23.2, target/23.3
