Repository vaadin/web-components, pull requests merged in 2022-04, with the labels that each got.

#3634 fix: prevent child elements being drawn outside dialog content area
  packages/dialog/src/vaadin-dialog-resizable-mixin.js
Labels: target/22.0, target/23.0

#3627 refactor: default tabindex property to undefined in TabIndexMixin
  packages/button/src/vaadin-button.js
  packages/component-base/src/tabindex-mixin.d.ts
  packages/component-base/src/tabindex-mixin.js
  packages/component-base/test/tabindex-mixin.test.js
  packages/field-base/src/delegate-focus-mixin.js
  packages/field-base/src/shadow-focus-mixin.js
  packages/grid/src/vaadin-grid.js
Labels: target/22.0, target/23.0

#3633 fix: display overlay over backdrop for Material theme
  packages/app-layout/test/visual/lumo/app-layout.test.js
  packages/app-layout/test/visual/lumo/screenshots/app-layout/baseline/ltr-primary-drawer-overlay-opened.png
  packages/app-layout/test/visual/lumo/screenshots/app-layout/baseline/rtl-primary-drawer-overlay-opened.png
  packages/app-layout/test/visual/material/app-layout.test.js
  packages/app-layout/test/visual/material/screenshots/app-layout/baseline/ltr-primary-drawer-overlay-opened.png
  packages/app-layout/test/visual/material/screenshots/app-layout/baseline/rtl-primary-drawer-overlay-opened.png
  packages/app-layout/theme/material/vaadin-app-layout-styles.js
Labels: target/22.0, target/23.0

#3659 test: make keyboard tests more reliable
  packages/date-picker/test/common.js
  packages/date-picker/test/keyboard-input.test.js
  packages/date-picker/test/keyboard-navigation.test.js
Labels: target/23.0

#3648 fix: restore overlay opened state when moving within the DOM
  packages/dialog/src/vaadin-dialog.js
  packages/dialog/test/dialog.test.js
  packages/login/src/vaadin-login-overlay.js
  packages/login/test/login-overlay.test.js
Labels: target/22.0, target/23.0

#3676 refactor: align naming of event handlers and observers
  packages/crud/src/vaadin-crud.js
Labels: target/23.0

#3677 fix: make charts respect global Highcharts no data message
  packages/charts/src/vaadin-chart.js
  packages/charts/test/chart-properties.test.js
Labels: target/23.0

#3689 fix: restore missing RTL pseudo element style
  packages/input-container/theme/lumo/vaadin-input-container-styles.js
Labels: target/22.0, target/23.0

#3690 refactor: remove unused code from time-picker
  packages/time-picker/src/vaadin-time-picker-combo-box.js
Labels: target/22.0, target/23.0

#3696 test: disable buttons animation in visual tests
  packages/menu-bar/test/not-animated-styles.js
Labels: target/22.0, target/23.0

#3699 chore: bump sinon to 13.0.2, fix sinon fake timers warnings
  packages/accordion/package.json
  packages/app-layout/package.json
  packages/avatar-group/package.json
  packages/avatar/package.json
  packages/board/package.json
  packages/button/package.json
  packages/charts/package.json
  packages/checkbox-group/package.json
  packages/checkbox/package.json
  packages/combo-box/package.json
  packages/component-base/package.json
  packages/component-base/test/virtualizer-reorder-elements.test.js
  packages/confirm-dialog/package.json
  packages/context-menu/package.json
  packages/crud/package.json
  packages/custom-field/package.json
  packages/date-picker/package.json
  packages/date-time-picker/package.json
  packages/details/package.json
  packages/dialog/package.json
  packages/email-field/package.json
  packages/field-base/package.json
  packages/field-highlighter/package.json
  packages/form-layout/package.json
  packages/grid-pro/package.json
  packages/grid/package.json
  packages/integer-field/package.json
  packages/item/package.json
  packages/list-box/package.json
  packages/login/package.json
  packages/map/package.json
  packages/menu-bar/package.json
  packages/message-input/package.json
  packages/message-list/package.json
  packages/multi-select-combo-box/package.json
  packages/notification/package.json
  packages/number-field/package.json
  packages/password-field/package.json
  packages/polymer-legacy-adapter/package.json
  packages/radio-group/package.json
  packages/rich-text-editor/package.json
  packages/select/package.json
  packages/split-layout/package.json
  packages/tabs/package.json
  packages/text-area/package.json
  packages/text-field/package.json
  packages/time-picker/package.json
  packages/upload/package.json
  packages/upload/test/upload.test.js
  packages/vaadin-avatar/package.json
  packages/vaadin-list-mixin/package.json
  packages/vaadin-messages/package.json
  packages/vaadin-overlay/package.json
  packages/vaadin-themable-mixin/package.json
  packages/virtual-list/package.json
  yarn.lock
Labels: internal

#3701 fix: enable using custom id for form-item label
  packages/form-layout/src/vaadin-form-item.js
  packages/form-layout/test/form-item.test.js
Labels: target/23.0

#3686 feat: show dropdown with selected items when readonly
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-scroller.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/basic.test.js
  packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-chip-styles.js
  packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-styles.js
  packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-chip-styles.js
  packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-styles.js
Labels: papercuts

#3729 docs: restore missing DatePickerMixin
  packages/date-picker/src/vaadin-date-picker.js
Labels: target/22.0, target/23.0

#3734 fix: use correct styles for week number cells
  packages/date-picker/src/vaadin-month-calendar.js
  packages/date-picker/test/visual/lumo/screenshots/date-picker/baseline/ltr-week-numbers.png
  packages/date-picker/test/visual/lumo/screenshots/date-picker/baseline/rtl-week-numbers.png
  packages/date-picker/test/visual/material/screenshots/date-picker/baseline/ltr-dropdown.png
  packages/date-picker/test/visual/material/screenshots/date-picker/baseline/ltr-week-numbers.png
  packages/date-picker/test/visual/material/screenshots/date-picker/baseline/rtl-dropdown.png
  packages/date-picker/test/visual/material/screenshots/date-picker/baseline/rtl-week-numbers.png
  packages/date-picker/theme/lumo/vaadin-month-calendar-styles.js
Labels: target/23.0

#3737 fix: Remove -webkit-overflow-scrolling style setting
  packages/grid/src/vaadin-grid.js
Labels: target/23.0

#3753 fix: use solid background for editable cells
  packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
  packages/grid-pro/theme/material/vaadin-grid-pro-styles.js
Labels: target/22.0, target/23.0
