Repository vaadin/web-components, pull requests merged in 2022-02, with the labels that each got.

#3371 test: rewrite date-picker keyboard tests to use sendKeys
  packages/date-picker/test/common.js
  packages/date-picker/test/keyboard-input-old.test.js
  packages/date-picker/test/keyboard-input.test.js
  packages/date-picker/test/keyboard-navigation.test.js
Labels: target/22.0

#3375 fix: add aria-hidden to clear and toggle buttons
  packages/combo-box/src/vaadin-combo-box.js
  packages/date-picker/src/vaadin-date-picker.js
  packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
  packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js
  packages/number-field/src/vaadin-number-field.js
  packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
  packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
  packages/select/src/vaadin-select.js
  packages/select/test/dom/__snapshots__/select.test.snap.js
  packages/text-area/src/vaadin-text-area.js
  packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
  packages/text-field/src/vaadin-text-field.js
  packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
  packages/time-picker/src/vaadin-time-picker.js
Labels: target/22.0

#3386 fix: only run the crud grid header renderer once
  packages/crud/src/vaadin-crud-grid.js
  packages/crud/test/crud-grid.test.js
Labels: target/22.0

#3390 fix: improve drawer toggle ARIA attributes
  dev/app-layout.html
  packages/app-layout/src/vaadin-app-layout.js
  packages/app-layout/src/vaadin-drawer-toggle.js
  packages/app-layout/test/app-layout.test.js
  packages/app-layout/test/drawer-toggle.test.js
Labels: a11y, target/22.0

#3372 refactor!: re-implement date-picker keyboard navigation
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/src/vaadin-date-picker-overlay.js
  packages/date-picker/src/vaadin-month-calendar.js
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/keyboard-input-old.test.js
  packages/date-picker/test/keyboard-input.test.js
  packages/date-picker/test/keyboard-navigation.test.js
  packages/date-picker/test/wai-aria.test.js
Labels: a11y

#3396 fix: cleanup slot attribute on removed nodes
  packages/split-layout/src/vaadin-split-layout.js
  packages/split-layout/test/split-layout.test.js
Labels: target/22.0

#3398 [date-picker] fix: prevent input blur on calendar icon click
  packages/date-picker/src/vaadin-date-picker.js
  packages/date-picker/test/basic.test.js
Labels: target/22.0

#3401 refactor: cleanup no longer used button roles
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/src/vaadin-date-picker.js
  packages/date-picker/test/wai-aria.test.js
Labels: a11y

#3402 fix: do not open dropdown on helper click
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/src/vaadin-combo-box.js
  packages/combo-box/test/toggling-dropdown.test.js
Labels: target/22.0

#3408 fix: fire input event when clearing on Esc
  packages/field-base/src/input-control-mixin.js
  packages/field-base/test/input-control-mixin.test.js
Labels: target/22.0

#3413 fix: restore old logic for getting focusable elements
  packages/accordion/package.json
  packages/accordion/test/dialog.test.js
  packages/component-base/src/focus-trap-controller.js
  packages/component-base/src/focus-utils.js
  packages/component-base/test/focus-trap-controller.test.js
Labels: a11y

#3416 fix: forward tabindex attribute to focusElement
  packages/component-base/src/tabindex-mixin.js
  packages/field-base/src/delegate-focus-mixin.d.ts
  packages/field-base/src/delegate-focus-mixin.js
  packages/field-base/src/shadow-focus-mixin.js
  packages/field-base/test/delegate-focus-mixin.test.js
  packages/message-input/test/dom/__snapshots__/message-input.test.snap.js
Labels: a11y, target/22.0

#3420 refactor: remove unused private property
  packages/select/src/vaadin-select.js
Labels: target/22.0

#3438 fix: add missing .js extension to utilities
  packages/vaadin-lumo-styles/utilities/accessibility.js
  packages/vaadin-lumo-styles/utilities/background.js
  packages/vaadin-lumo-styles/utilities/border.js
  packages/vaadin-lumo-styles/utilities/flexbox-grid.js
  packages/vaadin-lumo-styles/utilities/layout.js
  packages/vaadin-lumo-styles/utilities/shadows.js
  packages/vaadin-lumo-styles/utilities/sizing.js
  packages/vaadin-lumo-styles/utilities/spacing.js
  packages/vaadin-lumo-styles/utilities/typography.js
  packages/vaadin-lumo-styles/utility.js
Labels: target/22.0

#3441 fix: do not set aria-expanded on grid cells
  packages/grid/src/vaadin-grid-a11y-mixin.js
  packages/grid/src/vaadin-grid-row-details-mixin.js
  packages/grid/src/vaadin-grid.js
  packages/grid/test/accessibility.test.js
  packages/grid/test/row-details.test.js
Labels: target/22.0

#3450 fix: only set aria-level on tree grid rows
  packages/grid/src/vaadin-grid-a11y-mixin.js
  packages/grid/test/accessibility.test.js
  packages/grid/test/data-provider.test.js
Labels: a11y, target/22.0

#3447 fix: ensure slotted label ID is set properly
  packages/field-base/src/label-controller.js
  packages/field-base/test/field-mixin.test.js
Labels: target/22.0

#3459 fix: do not remove menu item component theme
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/context-menu/test/items.test.js
Labels: target/22.0

#3474 docs: restore JSDoc for input and change events
  packages/custom-field/src/vaadin-custom-field.js
  packages/field-base/src/input-control-mixin.js
Labels: target/22.0

#3478 fix: do not fire custom-value-set event twice
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/basic.test.js
Labels: target/22.0

#3495 fix: don't cancel text-area wheel event unnecessarily
  packages/text-area/src/vaadin-text-area.js
  packages/text-area/test/text-area.test.js
Labels: target/22.0
