Repository vaadin/web-components, pull requests merged in 2022-06, with the labels that each got.

#3950 fix: show user tags overlay only when the field is fully visible
  packages/field-highlighter/src/vaadin-user-tags.js
  packages/field-highlighter/test/field-components.test.js
  packages/field-highlighter/test/field-highlighter.test.js
  packages/field-highlighter/test/user-tags.test.js
Labels: target/23.0

#3986 fix: add hidden attribute styles to vaadin-tab
  packages/tabs/src/vaadin-tab.js
  packages/tabs/test/tab.test.js
Labels: target/22.0, target/23.0

#4007 fix: close drawer on touchend and prevent click
  packages/app-layout/src/vaadin-app-layout.js
  packages/app-layout/test/app-layout.test.js
Labels: target/23.1

#4004 fix: make getEventContext() work with context-menu on iOS
  packages/context-menu/src/vaadin-contextmenu-event.js
  packages/context-menu/test/touch.test.js
  packages/grid/src/vaadin-grid-event-context-mixin.js
  packages/grid/test/event-context.test.js
Labels: target/22.0, target/23.1

#4012 fix: do not fire change event on native input change
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/basic.test.js
Labels: target/23.1

#4016 fix: update selectedItems when updating items
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/basic.test.js
Labels: target/23.1

#4026 fix: restore broken date-picker scroll duration
  packages/date-picker/src/vaadin-date-picker-overlay-content.js
  packages/date-picker/test/keyboard-input.test.js
Labels: target/23.1

#4042 chore: disable yarn cache to fix CI builds
  .github/workflows/coverage.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/smoke.yml
  .github/workflows/snapshots.yml
  .github/workflows/unit-tests.yml
  .github/workflows/visual-tests.yml
Labels: target/23.1

#4064 fix: accept boolean and numeric item values
  packages/select/src/vaadin-select.js
  packages/select/test/select.test.js
Labels: target/23.1

#4068 fix: remove disconnected sorters with no parent
  packages/grid/src/vaadin-grid-sort-mixin.js
  packages/grid/src/vaadin-grid-sorter.js
  packages/grid/test/sorting.test.js
Labels: target/23.1

#4075 fix: do not un-select entered item with dataProvider
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/basic.test.js
  packages/multi-select-combo-box/test/selecting-items.test.js
Labels: target/23.1

#4090 fix: ensure checkValidity() returns the correct result
  packages/select/src/vaadin-select.d.ts
  packages/select/src/vaadin-select.js
  packages/select/test/select.test.js
  packages/select/test/typings/select.types.ts
Labels: target/23.1

#4082 fix: set correct input value with allowCustomValue
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/object-values.test.js
Labels: target/23.1

#4105 fix: announce item label when removing chip with keyboard
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/accessibility.test.js
Labels: target/23.1

#4100 fix: make ComboBoxDataProviderCallback size optional
  packages/combo-box/src/vaadin-combo-box-data-provider-mixin.d.ts
  packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js
  packages/combo-box/test/lazy-loading.test.js
Labels: target/23.1
