Repository vaadin/web-components, pull requests merged in 2023-07, with the labels that each got.

#6094 fix: auto-focus editor with aside or bottom editor position
  packages/crud/src/vaadin-crud.js
  packages/crud/test/a11y.test.js
  packages/crud/test/dom/__snapshots__/crud.test.snap.js
  packages/crud/test/visual/lumo/screenshots/crud/baseline/flex-column-layout.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/flex-layout.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-aside-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-aside-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-bottom-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/ltr-editor-position-bottom-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-aside-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-aside-new.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-bottom-edit.png
  packages/crud/test/visual/lumo/screenshots/crud/baseline/rtl-editor-position-bottom-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/flex-column-layout.png
  packages/crud/test/visual/material/screenshots/crud/baseline/flex-layout.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-aside-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-aside-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-bottom-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/ltr-editor-position-bottom-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-aside-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-aside-new.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-bottom-edit.png
  packages/crud/test/visual/material/screenshots/crud/baseline/rtl-editor-position-bottom-new.png
  packages/crud/theme/lumo/vaadin-crud-styles.js
  packages/crud/theme/material/vaadin-crud-styles.js
Labels: target/24.1

#6099 fix: animate primary drawer open and close transition
  packages/app-layout/src/vaadin-app-layout.js
  packages/app-layout/test/app-layout.test.js
Labels: target/24.0, target/24.1

#6105 fix: set tabindex on remaining button after updating overflow
  packages/menu-bar/src/vaadin-menu-bar-mixin.js
  packages/menu-bar/test/menu-bar.test.js
Labels: target/24.1

#6114 refator: move Esc keydown listener to window
  packages/app-layout/src/vaadin-app-layout.js
  packages/app-layout/test/app-layout.test.js
Labels: target/23.3, target/24.0, target/24.1

#6119 test: add missing await to prevent aria-hidden warnings
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/events.test.js
  packages/date-picker/test/validation.test.js
  packages/date-time-picker/test/basic.test.js
Labels: target/24.1

#6097 test: check that clicking the clear button in a field won't close the editor
  packages/grid-pro/test/edit-column-renderer.test.js
Labels: target/23.3, target/24.0, target/24.1

#6150 fix: ensure change event is fired on blur after prevented mousedown
  packages/password-field/src/vaadin-password-field.js
  packages/password-field/test/password-field.test.js
Labels: target/23.3, target/24.0, target/24.1

#6170 fix: use correct property to set CRUD dialog aria-label
  packages/crud/src/vaadin-crud.js
  packages/crud/test/a11y.test.js
Labels: target/24.0, target/24.1

#6171 fix!: make CBG group-field part a flex container
  packages/checkbox-group/src/vaadin-checkbox-group.js
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/basic.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/disabled.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/error-message.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/full-width.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/helper-above-field.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/helper-text.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/label-focused.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/label.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/required.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/rtl-basic.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/rtl-error-message.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/rtl-wrapped.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/value.png
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/wrapped.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/basic.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/disabled.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/error-message.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/full-width.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/helper-text.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/label-focused.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/label.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/required.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/rtl-basic.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/rtl-error-message.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/rtl-wrapped.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/value.png
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/wrapped.png
  packages/checkbox-group/theme/lumo/vaadin-checkbox-group-styles.js
  packages/checkbox-group/theme/material/vaadin-checkbox-group-styles.js
  packages/field-highlighter/test/visual/lumo/screenshots/field-highlighter/baseline/checkbox-group-focused.png
  packages/field-highlighter/test/visual/lumo/screenshots/field-highlighter/baseline/checkbox-group.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/checkbox-group-focused.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/checkbox-group.png
Labels: target/24.1

#6172 fix!: make RG group-field part a flex container
  packages/field-highlighter/test/visual/lumo/screenshots/field-highlighter/baseline/radio-group-focused.png
  packages/field-highlighter/test/visual/lumo/screenshots/field-highlighter/baseline/radio-group.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/radio-group-focused.png
  packages/field-highlighter/test/visual/material/screenshots/field-highlighter/baseline/radio-group.png
  packages/radio-group/src/vaadin-radio-group.js
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/basic.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/disabled.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/error-message.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/full-width.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/helper-above-field.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/helper-text.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/label-focused.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/label.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/required.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/rtl-basic.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/rtl-error-message.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/rtl-wrapped.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/value.png
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/wrapped.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/basic.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/disabled.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/error-message.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/full-width.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/helper-text.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/label-focused.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/label.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/required.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/rtl-basic.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/rtl-error-message.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/rtl-wrapped.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/value.png
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/wrapped.png
  packages/radio-group/theme/lumo/vaadin-radio-group-styles.js
  packages/radio-group/theme/material/vaadin-radio-group-styles.js
Labels: target/24.1
