Repository vaadin/web-components, pull requests merged in 2023-11, with the labels that each got.

#6719 fix: do not throw when item with keepOpen is after hr
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/context-menu/test/items.test.js
Labels: target/24.2

#6731 fix: check if grid focus target is in viewport
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/src/vaadin-grid-scroll-mixin.js
  packages/grid/test/keyboard-navigation.common.js
Labels: target/23.3, target/24.1, target/24.2

#6732 fix: check if grid focus target is in viewport (#6731)
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/test/keyboard-navigation.test.js
Labels: target/23.3

#6738 refactor: do not use button in not collapsible side-nav
  packages/side-nav/src/vaadin-side-nav.js
  packages/side-nav/test/accessibility.test.js
  packages/side-nav/test/dom/__snapshots__/side-nav.test.snap.js
Labels: target/23.3

#6748 fix: update Quill to fix disappearing cursor in Safari 17
  packages/rich-text-editor/vendor/vaadin-quill.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#6764 fix: check origin when matching paths for external URLs
  packages/component-base/src/url-utils.d.ts
  packages/component-base/src/url-utils.js
  packages/component-base/test/url-utils.test.js
Labels: target/24.2

#6767 fix: make link focusable when path is an empty string
  packages/side-nav/src/vaadin-side-nav-item.js
  packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
  packages/side-nav/test/dom/side-nav-item.test.js
Labels: target/24.2

#6689 fix: force zero padding on `no-padding` theme variant
  packages/dialog/test/visual/lumo/dialog.test.js
  packages/dialog/test/visual/lumo/screenshots/dialog/baseline/content-no-padding-theme.png
  packages/dialog/test/visual/material/dialog.test.js
  packages/dialog/test/visual/material/screenshots/dialog/baseline/content-no-padding-theme.png
  packages/dialog/theme/lumo/vaadin-dialog-styles.js
  packages/dialog/theme/material/vaadin-dialog-styles.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#6795 fix: update virtualizer scroller size before size change
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/grid/test/resizing.common.js
Labels: target/24.1, target/24.2

#6798 fix: support non-latin chars in list-mixin keyboard search
  packages/a11y-base/src/list-mixin.js
  packages/a11y-base/test/list-mixin.test.js
Labels: target/24.1, target/24.2

#6815 fix: measure grid column auto-width from column cell
  packages/grid/src/vaadin-grid-mixin.js
  packages/grid/test/column-auto-width.common.js
Labels: target/24.1, target/24.2

#6823 fix: add missing pre and code block Material styles
  packages/rich-text-editor/test/visual/material/rich-text-editor.test.js
  packages/rich-text-editor/test/visual/material/screenshots/rich-text-editor/baseline/dark-theme.png
  packages/rich-text-editor/theme/material/vaadin-rich-text-editor-styles.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#6822 fix: do not reset selected items when disabled set to false
  packages/list-box/src/vaadin-multi-select-list-mixin.js
  packages/list-box/test/multi-select-list-mixin.test.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#6836 fix: align check used to detect if the item is selected
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
  packages/multi-select-combo-box/test/selecting-items.test.js
Labels: target/23.4

#6840 fix: update text-area height on resize
  packages/text-area/src/vaadin-text-area-mixin.js
  packages/text-area/test/text-area.common.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#6838 fix: fix label color in disabled state
  packages/checkbox-group/test/visual/lumo/checkbox-group.test.js
  packages/checkbox-group/test/visual/lumo/screenshots/checkbox-group/baseline/label-disabled.png
  packages/checkbox-group/test/visual/material/checkbox-group.test.js
  packages/checkbox-group/test/visual/material/screenshots/checkbox-group/baseline/label-disabled.png
  packages/radio-group/test/visual/lumo/radio-group.test.js
  packages/radio-group/test/visual/lumo/screenshots/radio-group/baseline/label-disabled.png
  packages/radio-group/test/visual/material/radio-group.test.js
  packages/radio-group/test/visual/material/screenshots/radio-group/baseline/label-disabled.png
  packages/radio-group/theme/lumo/vaadin-radio-group-styles.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#6859 fix: do not change value on step buttons touch scroll
  packages/number-field/src/vaadin-number-field-mixin.js
  packages/number-field/test/value-control-buttons.common.js
Labels: target/24.1, target/24.2

#6871 fix: cache pending html value for unattached rte
  packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
  packages/rich-text-editor/test/basic.common.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4
