Repository vaadin/web-components, pull requests merged in 2023-01, with the labels that each got.

#5135 fix: handle large item height differences in virtualizer
  packages/component-base/src/iron-list-core.js
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-variable-row-height.test.js
Labels: target/23.2, target/23.3

#5203 docs: add private JSDoc annotation to theme classes
  packages/vaadin-lumo-styles/version.js
  packages/vaadin-material-styles/version.js
Labels: target/23.2, target/23.3

#5217 docs: use fetch in combo-box dataProvider example
  packages/combo-box/src/vaadin-combo-box.d.ts
  packages/combo-box/src/vaadin-combo-box.js
Labels: target/23.2, target/23.3

#5223 fix: do not throw on requestContentUpdate before attach
  packages/context-menu/src/vaadin-context-menu.js
  packages/context-menu/test/items.test.js
  packages/context-menu/test/renderer.test.js
Labels: target/23.2, target/23.3

#5226 test: improve context-menu Lit renderer tests formatting
  packages/context-menu/test/lit-renderer-directives.test.js
Labels: target/23.2, target/23.3

#5235 test: add missing snapshot tests to vaadin-menu-bar
  packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js
  packages/menu-bar/test/dom/menu-bar.test.js
Labels: target/23.2, target/23.3

#5239 test: update and fix vaadin-time-picker snapshot tests
  packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js
  packages/time-picker/test/dom/time-picker.test.js
Labels: target/23.2, target/23.3

#5243 test: add missing typings tests to vaadin-avatar-group
  packages/avatar-group/test/typings/avatar-group.types.ts
Labels: target/23.2, target/23.3

#5244 test: add missing avatar-group overlay snapshot tests
  packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js
  packages/avatar-group/test/dom/avatar-group.test.js
Labels: target/23.2, target/23.3

#5254 fix[combo-box]: Correct aria-setsize placement on scroller
  packages/combo-box/src/vaadin-combo-box-scroller.js
  packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js
  packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js
Labels: target/22.0, target/23.2, target/23.3

#5263 fix: do not consider label and hidden elements focusable
  packages/grid/src/vaadin-grid-active-item-mixin.js
  packages/grid/test/keyboard-navigation.test.js
Labels: target/23.2, target/23.3

#5271 fix: ignore label clicks in grid cells
  packages/grid/src/vaadin-grid-active-item-mixin.js
  packages/grid/src/vaadin-grid-tree-toggle.js
  packages/grid/test/renderers.test.js
  packages/grid/test/tree-toggle.test.js
Labels: target/23.2, target/23.3

#5290 refactor!: remove special handling of dom-if and dom-repeat in board
  packages/board/src/vaadin-board-row.js
  packages/board/test/template.test.js
Labels: no-polymer

#5296 fix: allow programmatically multi-sorting if multiSortOnShiftClick is enabled
  packages/grid/src/vaadin-grid-sort-mixin.js
  packages/grid/src/vaadin-grid-sorter.d.ts
  packages/grid/src/vaadin-grid-sorter.js
  packages/grid/test/sorting.test.js
  packages/grid/test/typings/grid.types.ts
Labels: target/23.2, target/23.3

#5302 refactor: make globals opt-in for backwards compatibility
  packages/checkbox/theme/lumo/vaadin-checkbox-styles.js
  packages/checkbox/theme/material/vaadin-checkbox-styles.js
  packages/radio-group/theme/lumo/vaadin-radio-button-styles.js
  packages/radio-group/theme/material/vaadin-radio-button-styles.js
  packages/vaadin-lumo-styles/style.js
  packages/vaadin-material-styles/style.js
Labels: target/23.2, target/23.3

#5330 fix: do not throw when combo-box is templatized
  packages/combo-box/src/vaadin-combo-box-scroller.js
  packages/combo-box/test/polymer.test.js
Labels: target/23.2, target/23.3

#5345 fix: align select placeholder color with other components
  packages/select/test/visual/lumo/screenshots/select/baseline/placeholder.png
  packages/select/theme/lumo/vaadin-select-styles.js
Labels: target/23.2, target/23.3

#5355 fix: do not update the whole row when removing grid-pro editor
  packages/grid-pro/src/vaadin-grid-pro-edit-column.js
  packages/grid-pro/test/lit.test.js
Labels: target/23.2, target/23.3

#5368 test: move helpers from common.js to helpers.js
  dev/upload.html
  integration/tests/dialog-date-picker.test.js
  packages/board/test/helpers.js
  packages/board/test/redraw.test.js
  packages/board/test/size.test.js
  packages/context-menu/test/dom/context-menu.test.js
  packages/context-menu/test/helpers.js
  packages/context-menu/test/visual/lumo/context-menu.test.js
  packages/context-menu/test/visual/material/context-menu.test.js
  packages/custom-field/test/custom-field.test.js
  packages/custom-field/test/helpers.js
  packages/custom-field/test/slot-wrapper.test.js
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/custom-input.test.js
  packages/date-picker/test/dom/date-picker.test.js
  packages/date-picker/test/dom/month-calendar.test.js
  packages/date-picker/test/dropdown.test.js
  packages/date-picker/test/fullscreen.test.js
  packages/date-picker/test/helpers.js
  packages/date-picker/test/keyboard-input.test.js
  packages/date-picker/test/keyboard-navigation.test.js
  packages/date-picker/test/month-calendar.test.js
  packages/date-picker/test/overlay.test.js
  packages/date-picker/test/scroller.test.js
  packages/date-picker/test/theme-propagation.test.js
  packages/date-picker/test/validation.test.js
  packages/date-picker/test/wai-aria.test.js
  packages/date-time-picker/test/validation.test.js
  packages/field-highlighter/test/field-components.test.js
  packages/field-highlighter/test/visual/common.js
  packages/field-highlighter/test/visual/helpers.js
  packages/field-highlighter/test/visual/lumo/field-highlighter.test.js
  packages/field-highlighter/test/visual/material/field-highlighter.test.js
  packages/horizontal-layout/test/helpers.js
  packages/horizontal-layout/test/horizontal-layout.test.js
  packages/upload/test/a11y.test.js
  packages/upload/test/adding-files.test.js
  packages/upload/test/file-list.test.js
  packages/upload/test/file.test.js
  packages/upload/test/helpers.js
  packages/upload/test/keyboard-navigation.test.js
  packages/upload/test/slots.test.js
  packages/upload/test/upload.test.js
  packages/vertical-layout/test/helpers.js
  packages/vertical-layout/test/vertical-layout.test.js
Labels: target/23.2, target/23.3

#5396 fix: use correct selector for highlight-read-only-cells theme
  packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
Labels: target/23.3

#5406 refactor: calculate grid overflow in debouncer callback
  packages/grid/src/vaadin-grid-scroll-mixin.js
Labels: performance

#5402 fix: set aria-selected on selected item, not the focused one
  packages/combo-box/src/vaadin-combo-box-scroller.js
  packages/combo-box/test/aria.test.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-scroller.js
  packages/time-picker/test/aria.test.js
Labels: target/23.2, target/23.3

#5419 fix: allow undefined in activeItem and corresponding event [skip ci]
  packages/grid-pro/test/typings/grid-pro.types.ts
  packages/grid/src/vaadin-grid-active-item-mixin.d.ts
  packages/grid/src/vaadin-grid.d.ts
  packages/grid/test/typings/grid.types.ts
Labels: target/23.2, target/23.3
