Repository vaadin/web-components, pull requests merged in 2023-10, with the labels that each got.

#6606 fix: set initial value using property to ensure change is fired
  packages/field-base/src/input-controller.js
  packages/field-base/test/input-controller.test.js
Labels: target/23.3, target/24.1, target/24.2

#6602 fix: make auto-width and text-align usable in custom slot
  packages/grid/src/vaadin-grid-column-mixin.js
  packages/grid/src/vaadin-grid-mixin.js
  packages/grid/test/grid-wrapper-polymer.test.js
  packages/grid/test/grid-wrapper.common.js
Labels: target/23.3, target/24.1, target/24.2

#6618 fix: defer grid cell-focus event with lazy data provider
  packages/grid/src/vaadin-grid-data-provider-mixin.js
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/test/keyboard-navigation.common.js
Labels: target/23.3, target/24.1, target/24.2

#6638 fix: make sure unhidden combo-box items get re-rendered
  packages/combo-box/src/vaadin-combo-box-item-mixin.js
  packages/combo-box/test/item-renderer.test.js
Labels: target/23.3, target/24.1, target/24.2

#6651 fix: prevent rte from trimming whitespace on delta conversion
  packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
  packages/rich-text-editor/test/basic.common.js
Labels: target/24.1, target/24.2

#6648 fix: update grid header and footer on column tree update
  packages/grid/src/vaadin-grid-mixin.js
  packages/grid/test/renderers.common.js
Labels: target/23.3, target/24.1, target/24.2

#6645 fix: make vaadin-icon respect fill and stroke from source icon
  dev/assets/info-circle.svg
  dev/icon.html
  packages/icon/src/vaadin-icon.js
  packages/icon/test/icon.test.js
Labels: target/24.2

#6665 test: fix a grid pro test case
  packages/grid-pro/test/edit-column.test.js
Labels: target/24.2

#6704 fix: support items with duplicate labels in combo-box
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/object-values.test.js
Labels: target/24.1, target/24.2

#6707 fix: support dynamic changes to cookie consent properties
  packages/cookie-consent/src/vaadin-cookie-consent.js
  packages/cookie-consent/test/cookie-consent.test.js
Labels: target/24.1, target/24.2
