Repository vaadin/web-components, pull requests merged in 2023-09, with the labels that each got.

#6443 fix: wrap nodes correctly to ensure proper initialization
  integration/package.json
  integration/tests/confirm-dialog-fields.test.js
  packages/confirm-dialog/src/vaadin-confirm-dialog.js
Labels: target/24.0, target/24.1

#6448 fix: do not throw when removing sort column after sorting
  packages/grid/src/vaadin-grid-dynamic-columns-mixin.js
  packages/grid/test/lit.test.js
Labels: target/23.3, target/24.0, target/24.1

#6476 fix: validate on value change triggered by arrow key
  packages/number-field/src/vaadin-number-field-mixin.js
  packages/number-field/test/validation.common.js
Labels: target/23.3, target/24.0, target/24.1

#6492 fix: remove hardcoded aria-labels from the `learn more` and `dismiss` links
  packages/cookie-consent/src/vaadin-cookie-consent.js
  packages/cookie-consent/test/cookie-consent.test.js
Labels: target/23.3, target/24.1

#6499 fix: toolbar should have role="toolbar" for better screen reader support
  packages/rich-text-editor/src/vaadin-rich-text-editor.js
  packages/rich-text-editor/test/a11y.test.js
Labels: target/23.3, target/24.1

#6507 fix: workaround disappearing text on spellcheck suggestion
  packages/rich-text-editor/src/vaadin-rich-text-editor.js
Labels: target/23.3, target/24.1

#6530 chore: config tests to retry on failure
  wtr-utils.js
Labels: target/23.3, target/24.0, target/24.1

#6550 fix: unset input width/height to avoid issue with UA styles
  packages/checkbox/src/vaadin-checkbox-styles.js
Labels: target/23.3, target/24.0, target/24.1

#6554 fix: unset radio button input width and height to fix UA styles relat…
  packages/radio-group/src/vaadin-radio-button.js
Labels: target/23.3, target/24.1, target/24.2
