Repository vaadin/web-components, pull requests merged in 2023-02, with the labels that each got.

#5430 fix: stop grid column reordering on contextmenu event
  packages/grid/src/vaadin-grid-column-reordering-mixin.js
  packages/grid/test/column-reordering.test.js
Labels: target/23.3

#5432 fix: add required vertical space for combo-box overlay
  packages/combo-box/src/vaadin-combo-box-overlay.js
  packages/combo-box/test/overlay-position.test.js
  packages/overlay/src/vaadin-overlay-position-mixin.d.ts
  packages/overlay/src/vaadin-overlay-position-mixin.js
  packages/overlay/test/position-mixin.test.js
  packages/overlay/test/typings/overlay.types.ts
Labels: target/22.0, target/23.3

#5439 chore: Avoid utf-8 characters in code
  packages/button/theme/lumo/vaadin-button-styles.js
Labels: target/23.2, target/23.3

#5449 test: disable animations in tabs and tabsheet visual tests
  packages/tabs/test/visual/lumo/tabs.test.js
  packages/tabs/test/visual/material/tabs.test.js
  packages/tabs/test/visual/not-animated-styles.js
  packages/tabsheet/test/visual/lumo/tabsheet.test.js
  packages/tabsheet/test/visual/material/tabsheet.test.js
Labels: target/23.3

#5454 refactor: use Unicode entities for forward and back buttons
  packages/tabs/src/vaadin-tabs.js
Labels: target/23.3

#5456 refactor: use HTML entity for the menu-bar overflow button
  packages/menu-bar/src/vaadin-menu-bar-mixin.js
Labels: target/23.3

#5426 fix: hide placeholder item when select is readonly or disabled
  packages/select/test/visual/lumo/screenshots/select/baseline/disabled-placeholder.png
  packages/select/test/visual/lumo/screenshots/select/baseline/readonly-placeholder.png
  packages/select/test/visual/lumo/select.test.js
  packages/select/theme/lumo/vaadin-select-styles.js
Labels: target/23.2, target/23.3

#5460 test: flush the virtualizer to avoid test flakiness
  packages/component-base/test/virtualizer-item-height.test.js
Labels: target/23.2, target/23.3, target/24.0

#5433 fix: use computed style to get item height
  packages/component-base/src/iron-list-core.js
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-item-height.test.js
  packages/component-base/test/virtualizer-unlimited-size.test.js
Labels: target/23.2, target/23.3, target/24.0

#5477 fix: allow propagating enter key event after selecting value
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/keyboard.test.js
Labels: target/23.2, target/23.3, target/24.0

#5505 refactor: rename __clear() to _onClearAction()
  packages/field-base/src/input-control-mixin.js
Labels: target/24.0

#5507 fix: do not check for extending Item when setting ARIA attribute
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js
  packages/context-menu/test/helpers.js
Labels: target/24.0

#5508 refactor: align naming related to value clearing
  packages/combo-box/src/vaadin-combo-box-light.js
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/src/vaadin-combo-box.js
  packages/combo-box/test/basic.test.js
Labels: target/24.0

#5513 refactor: extract clear button related logic to ClearButtonMixin
  packages/combo-box/src/vaadin-combo-box.d.ts
  packages/combo-box/test/typings/combo-box.types.ts
  packages/date-picker/test/typings/date-picker.types.ts
  packages/field-base/src/clear-button-mixin.d.ts
  packages/field-base/src/clear-button-mixin.js
  packages/field-base/src/input-control-mixin.d.ts
  packages/field-base/src/input-control-mixin.js
  packages/field-base/src/input-field-mixin.d.ts
  packages/field-base/test/clear-button-mixin.test.js
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
  packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
  packages/time-picker/test/typings/time-picker.types.ts
Labels: target/24.0

#5515 refactor: remove a unnecessary clear() method override
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
Labels: target/24.0

#5522 refactor: extract number-field logic to reusable NumberFieldMixin
  packages/number-field/package.json
  packages/number-field/src/vaadin-number-field-mixin.d.ts
  packages/number-field/src/vaadin-number-field-mixin.js
  packages/number-field/src/vaadin-number-field.d.ts
  packages/number-field/src/vaadin-number-field.js
Labels: target/24.0

#5524 test: update text-field tests to allow async property updates
  packages/text-field/test/text-field.test.js
  packages/text-field/test/validation.test.js
Labels: target/24.0

#5528 test: update text-area tests to allow async property updates
  packages/text-area/test/text-area.test.js
  packages/text-area/test/validation.test.js
Labels: target/24.0

#5529 refactor: extract number-field styles to reusable css literal
  packages/number-field/package.json
  packages/number-field/src/vaadin-number-field-styles.d.ts
  packages/number-field/src/vaadin-number-field-styles.js
  packages/number-field/src/vaadin-number-field.js
Labels: target/24.0

#5534 test: update number-field tests to allow async updates
  packages/number-field/test/number-field.test.js
  packages/number-field/test/validation.test.js
Labels: target/24.0

#5537 test: update email-field tests to allow async updates
  packages/email-field/test/email-field.test.js
Labels: target/24.0

#5539 experiment: add LitElement based version of vaadin-text-area
  packages/text-area/package.json
  packages/text-area/src/vaadin-lit-text-area.d.ts
  packages/text-area/src/vaadin-lit-text-area.js
  packages/text-area/test/text-area-lit.test.js
  packages/text-area/test/text-area-polymer.test.js
  packages/text-area/test/text-area.common.js
  packages/text-area/test/validation-lit.test.js
  packages/text-area/test/validation-polymer.test.js
  packages/text-area/test/validation.common.js
Labels: target/24.0

#5541 experiment: add Lit based version of vaadin-number-field
  packages/number-field/package.json
  packages/number-field/src/vaadin-lit-number-field.d.ts
  packages/number-field/src/vaadin-lit-number-field.js
  packages/number-field/test/number-field-lit.test.js
  packages/number-field/test/number-field-polymer.test.js
  packages/number-field/test/number-field.common.js
  packages/number-field/test/validation-lit.test.js
  packages/number-field/test/validation-polymer.test.js
  packages/number-field/test/validation.common.js
Labels: target/24.0

#5544 refactor: extract button template and reusable css literal
  packages/button/package.json
  packages/button/src/vaadin-button-base.d.ts
  packages/button/src/vaadin-button-base.js
  packages/button/src/vaadin-button.js
  packages/crud/src/vaadin-crud-edit.js
Labels: target/24.0

#5549 experiment: add Lit based version of vaadin-email-field
  packages/email-field/package.json
  packages/email-field/src/vaadin-lit-email-field.d.ts
  packages/email-field/src/vaadin-lit-email-field.js
  packages/email-field/test/email-field-lit.test.js
  packages/email-field/test/email-field-polymer.test.js
  packages/email-field/test/email-field.common.js
Labels: target/24.0

#5551 experiment: add Lit based version of vaadin-button
  packages/button/package.json
  packages/button/src/vaadin-button-mixin.js
  packages/button/src/vaadin-lit-button.d.ts
  packages/button/src/vaadin-lit-button.js
  packages/button/test/button-lit.test.js
  packages/button/test/button-polymer.test.js
  packages/button/test/button.common.js
Labels: target/24.0

#5552 chore: update release notes script to list experiments
  scripts/generateReleaseNotes.js
Labels: target/24.0

#5556 refactor: fix incorrect exports in the new button base
  packages/button/src/vaadin-button-base.d.ts
Labels: target/24.0

#5557 refactor: extract progress-bar styles to reusable css literal
  packages/progress-bar/package.json
  packages/progress-bar/src/vaadin-progress-bar-styles.d.ts
  packages/progress-bar/src/vaadin-progress-bar-styles.js
  packages/progress-bar/src/vaadin-progress-bar.js
Labels: target/24.0

#5558 experiment: add Lit based version of vaadin-progress-bar
  packages/progress-bar/package.json
  packages/progress-bar/src/vaadin-lit-progress-bar.d.ts
  packages/progress-bar/src/vaadin-lit-progress-bar.js
  packages/progress-bar/test/progress-bar-lit.test.js
  packages/progress-bar/test/progress-bar-polymer.test.js
  packages/progress-bar/test/progress-bar.common.js
Labels: target/24.0

#5562 refactor: extract checkbox styles to reusable css literal
  packages/checkbox/package.json
  packages/checkbox/src/vaadin-checkbox-styles.d.ts
  packages/checkbox/src/vaadin-checkbox-styles.js
  packages/checkbox/src/vaadin-checkbox.js
Labels: target/24.0

#5563 refactor: extract checkbox logic to reusable CheckboxMixin
  packages/checkbox/package.json
  packages/checkbox/src/vaadin-checkbox-mixin.d.ts
  packages/checkbox/src/vaadin-checkbox-mixin.js
  packages/checkbox/src/vaadin-checkbox.js
Labels: target/24.0

#5565 docs: improve JSDoc for checkbox stylable parts and states
  packages/checkbox/src/vaadin-checkbox.d.ts
  packages/checkbox/src/vaadin-checkbox.js
Labels: target/24.0

#5567 experiment: add Lit based version of vaadin-checkbox
  packages/checkbox/package.json
  packages/checkbox/src/vaadin-lit-checkbox.d.ts
  packages/checkbox/src/vaadin-lit-checkbox.js
  packages/checkbox/test/checkbox-lit.test.js
  packages/checkbox/test/checkbox-polymer.test.js
  packages/checkbox/test/checkbox.common.js
Labels: target/24.0

#5512 refactor: simplify and split context-menu ItemsMixin logic
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
Labels: target/24.0

#5573 refactor: simplify logic, set modeless state using property
  packages/context-menu/src/vaadin-context-menu.d.ts
  packages/context-menu/src/vaadin-context-menu.js
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/menu-bar/src/vaadin-menu-bar-submenu.js
Labels: target/24.0

#5577 fix: do not link label with value button if label is empty
  packages/select/src/vaadin-select.js
  packages/select/test/dom/__snapshots__/select.test.snap.js
Labels: target/23.3, target/24.0

#5584 fix: use registerStyles for vaadin-drawer-toggle core styles
  packages/app-layout/src/vaadin-drawer-toggle.js
Labels: target/24.0

#5600 refactor!: rename CSS property for input-field border radius
  packages/date-time-picker/theme/lumo/vaadin-date-time-picker-styles.js
  packages/input-container/src/vaadin-input-container.js
  packages/input-container/theme/lumo/vaadin-input-container-styles.js
  packages/vaadin-lumo-styles/style.js
Labels: target/24.0

#5599 fix: reset _hasInputValue on programmatic value clear
  packages/field-base/src/input-mixin.js
  packages/field-base/test/input-mixin.test.js
Labels: target/24.0

#5614 test: rename datepicker to datePicker
  integration/tests/dialog-date-picker.test.js
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/custom-input.test.js
  packages/date-picker/test/dropdown.test.js
  packages/date-picker/test/fullscreen.test.js
  packages/date-picker/test/helpers.js
  packages/date-picker/test/keyboard-input.test.js
  packages/date-picker/test/keyboard-navigation.test.js
  packages/date-picker/test/theme-propagation.test.js
  packages/date-picker/test/wai-aria.test.js
Labels: target/23.3, target/24.0

#5610 fix: reset menu-bar-item attributes to initial state when returned to the menu bar
  packages/menu-bar/src/vaadin-menu-bar-mixin.js
  packages/menu-bar/test/menu-bar.test.js
Labels: target/24.0
