Repository vaadin/web-components, pull requests merged in 2023-08, with the labels that each got.

#6327 fix: reflect icon as an attribute
  packages/icon/src/vaadin-icon.d.ts
  packages/icon/src/vaadin-icon.js
  packages/icon/test/icon.test.js
Labels: target/23.3, target/24.1

#6331 fix: prevent toggling opened state on click when disabled
  packages/accordion/test/accordion-panel.test.js
  packages/details/src/collapsible-mixin.js
  packages/details/test/details.common.js
Labels: target/24.0, target/24.1

#6354 fix: do not toggle opened state on summary anchor click
  packages/accordion/test/accordion-panel.test.js
  packages/details/src/collapsible-mixin.js
  packages/details/test/details.common.js
Labels: target/23.3, target/24.0, target/24.1

#6357 fix: reset pointer-events: none for header slot children
  packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js
  packages/confirm-dialog/test/confirm-dialog.test.js
Labels: target/23.3, target/24.0, target/24.1

#6373 fix: do not clear selected items on Escape when readonly
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
  packages/multi-select-combo-box/test/readonly.test.js
Labels: target/23.3, target/24.0, target/24.1

#6371 fix: do not fire change event for time-picker bad input
  packages/time-picker/src/vaadin-time-picker.js
  packages/time-picker/test/validation.test.js
Labels: target/24.0, target/24.1

#6396 fix: do not fire change event if the value has not changed
  packages/time-picker/src/vaadin-time-picker.js
  packages/time-picker/test/events.test.js
Labels: target/24.0, target/24.1

#6406 fix: do not scroll to the first column on focus
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/test/keyboard-navigation.test.js
Labels: target/23.2, target/23.3, target/24.0, target/24.1

#6421 fix: fire change event on arrow keys when step >= 1
  packages/time-picker/src/vaadin-time-picker.js
  packages/time-picker/test/events.test.js
Labels: regression

#6411 fix: correctly handle aria-hidden with nested shadow roots
  packages/a11y-base/src/aria-hidden.js
  packages/a11y-base/test/aria-hidden.test.js
Labels: target/24.1

#6434 fix: Remove empty spans used by Quill internally from htmlValue
  packages/rich-text-editor/src/vaadin-rich-text-editor.js
  packages/rich-text-editor/test/basic.test.js
Labels: target/23.3, target/24.0, target/24.1
