Repository vaadin/web-components, pull requests merged in 2023-06, with the labels that each got.

#5932 fix: show tooltips when target is partially visible
  packages/avatar/test/avatar.test.js
  packages/tooltip/src/vaadin-tooltip.js
  packages/tooltip/test/tooltip.test.js
Labels: target/23.3, target/24.0, target/24.1

#5943 refactor: set aria-hidden on elements outside overlay drawer
  packages/app-layout/src/vaadin-app-layout.js
  packages/app-layout/test/keyboard-mobile.test.js
Labels: target/24.1

#5951 refactor: extract overlay focus restoration logic into a controller
  packages/a11y-base/index.d.ts
  packages/a11y-base/index.js
  packages/a11y-base/src/focus-restoration-controller.d.ts
  packages/a11y-base/src/focus-restoration-controller.js
  packages/a11y-base/test/focus-restoration-controller.test.js
  packages/overlay/src/vaadin-overlay-focus-mixin.d.ts
  packages/overlay/src/vaadin-overlay-focus-mixin.js
  packages/overlay/src/vaadin-overlay.js
  packages/overlay/test/restore-focus.test.js
Labels: target/24.1

#5966 fix: focus input element when overlay is opened
  packages/combo-box/src/vaadin-combo-box-light.js
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/combo-box-light.test.js
  packages/multi-select-combo-box/test/basic.test.js
  packages/multi-select-combo-box/test/dom/__snapshots__/multi-select-combo-box.test.snap.js
  packages/multi-select-combo-box/test/visual/common.js
  packages/multi-select-combo-box/test/visual/lumo/multi-select-combo-box.test.js
  packages/multi-select-combo-box/test/visual/lumo/screenshots/multi-select-combo-box/baseline/selected-focused-chip.png
  packages/multi-select-combo-box/test/visual/material/multi-select-combo-box.test.js
  packages/multi-select-combo-box/test/visual/material/screenshots/multi-select-combo-box/baseline/opened-readonly.png
  packages/multi-select-combo-box/test/visual/material/screenshots/multi-select-combo-box/baseline/opened-selected.png
  packages/multi-select-combo-box/test/visual/material/screenshots/multi-select-combo-box/baseline/opened.png
  packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js
  packages/time-picker/test/time-picker.test.js
  packages/time-picker/test/visual/lumo/time-picker.test.js
  packages/time-picker/test/visual/material/screenshots/time-picker/baseline/ltr-opened.png
  packages/time-picker/test/visual/material/screenshots/time-picker/baseline/rtl-opened.png
  packages/time-picker/test/visual/material/time-picker.test.js
Labels: target/23.3, target/24.0, target/24.1

#5925 fix: scroll to the next item on button click
  packages/tabs/src/vaadin-tabs.js
  packages/tabs/test/scroll.test.js
Labels: target/24.1

#5995 fix: avoid opened changed events when moving dialog within DOM
  packages/confirm-dialog/test/confirm-dialog.test.js
  packages/dialog/src/vaadin-dialog.js
  packages/dialog/test/dialog.test.js
Labels: target/24.0, target/24.1

#6011 fix: use cached references to iterate cells instead of DOM state
  packages/grid/src/vaadin-grid-a11y-mixin.js
  packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
  packages/grid/src/vaadin-grid-helpers.js
  packages/grid/src/vaadin-grid-styling-mixin.js
  packages/grid/src/vaadin-grid.js
  packages/grid/test/column-rendering.test.js
Labels: target/24.1

#6017 refactor: cache body row cells
  packages/grid/src/vaadin-grid-helpers.js
  packages/grid/src/vaadin-grid.js
Labels: target/24.1

#6022 fix: manually restore scroll position for grid in Firefox
  packages/grid/src/vaadin-grid-scroll-mixin.js
  packages/grid/test/scroll-restoration.test.js
Labels: target/23.3, target/24.0, target/24.1

#6033 test: properly reset global tooltip state
  packages/tooltip/src/vaadin-tooltip.js
  packages/tooltip/test/tooltip-timers.test.js
Labels: target/23.3, target/24.0, target/24.1

#6040 test: automatically retry visual tests in CI
  .github/workflows/visual-tests.yml
Labels: target/23.3, target/24.0, target/24.1

#6046 fix: properly escape email pattern
  packages/email-field/src/vaadin-email-field.js
  packages/email-field/src/vaadin-lit-email-field.js
  packages/email-field/test/email-field.common.js
  packages/field-base/test/pattern-mixin.test.js
Labels: target/24.0, target/24.1

#6054 test: increase visual test workflow timeout
  .github/workflows/visual-tests.yml
Labels: target/23.3, target/24.0, target/24.1

#6044 fix: make focus restoration work with slotted grid
  packages/crud/src/vaadin-crud-grid.js
  packages/crud/src/vaadin-crud.js
  packages/crud/test/a11y.test.js
  packages/grid/src/vaadin-grid.js
Labels: target/24.1

#6060 fix: invoke setFocused only on events triggered by focusElement
  packages/a11y-base/src/delegate-focus-mixin.js
  packages/a11y-base/test/delegate-focus-mixin.test.js
Labels: target/24.0, target/24.1

#6075 fix: prevent extra vertical padding with filled variant
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/rtl-theme-reverse-filled.png
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/theme-reverse-filled.png
  packages/accordion/theme/lumo/vaadin-accordion-heading-styles.js
Labels: target/24.1

#6074 fix: display tooltips over notifications
  integration/package.json
  integration/tests/notification-tooltip.test.js
  packages/tooltip/src/vaadin-tooltip-overlay.js
Labels: target/24.1

#6085 fix: update aria-labelledby when restoring default label
  packages/component-base/src/slot-child-observe-controller.js
  packages/field-base/test/field-mixin.test.js
Labels: target/24.0, target/24.1
