Repository vaadin/web-components, pull requests merged in 2023-05, with the labels that each got.

#5797 fix: prevent diacritics from being cut off
  packages/vaadin-lumo-styles/mixins/required-field.js
Labels: target/23.3, target/24.0

#5832 refactor: remove optional chaining from confirm-dialog
  packages/confirm-dialog/src/vaadin-confirm-dialog.js
Labels: target/24.0

#5840 fix: do not recalculate flex basis on resize if row is invisible
  packages/board/package.json
  packages/board/src/vaadin-board-row.js
  packages/board/test/redraw.test.js
Labels: target/23.3, target/24.0

#5849 fix: compute offsetLeft using boundingClientRect
  packages/menu-bar/src/vaadin-menu-bar-mixin.js
  packages/menu-bar/test/menu-bar.test.js
Labels: target/24.0

#5848 fix: allow setting custom preserveAspectRatio attribute
  packages/icon/src/vaadin-icon.js
  packages/icon/src/vaadin-iconset.d.ts
  packages/icon/src/vaadin-iconset.js
  packages/icon/test/icon.test.js
Labels: target/23.3, target/24.0

#5878 fix: keep previously added custom elements
  packages/component-base/src/slot-controller.js
  packages/component-base/test/slot-controller.test.js
Labels: target/24.0, target/24.1

#5888 fix: update hidden state when virtualizer container is invisible
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer.test.js
Labels: target/24.0, target/24.1

#5876 fix: prevent column width calculation when grid is not visible
  packages/grid/src/vaadin-grid.js
  packages/grid/test/column-auto-width.test.js
Labels: target/23.3, target/24.0, target/24.1

#5899 fix: do not reset scroll position when hiding grid
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/grid/test/hidden-grid.test.js
Labels: target/23.3, target/24.0, target/24.1
