Repository vaadin/web-components, pull requests merged in 2023-12, with the labels that each got.

#6929 fix: add missing export for DetailsSummary component class
  packages/details/src/vaadin-details-summary.js
  packages/details/src/vaadin-lit-details-summary.js
Labels: target/24.1, target/24.2

#6930 fix: add missing export for CrudEdit component class
  packages/crud/src/vaadin-crud-edit.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#6939 fix: update vaadin-tabsheet type to extend HTMLElement
  packages/tabsheet/src/vaadin-tabsheet.d.ts
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#6953 refactor: remove unused ifDefined import from side-nav
  packages/side-nav/src/vaadin-side-nav.js
Labels: target/24.2

#6958 fix: add missing held property to UploadFile type
  packages/upload/src/vaadin-upload-mixin.d.ts
Labels: target/24.2

#6957 fix: allow defining slots in split-layout (#6938) (CP: 24.1)
  packages/split-layout/src/vaadin-split-layout.js
  packages/split-layout/test/split-layout.test.js
Labels: target/23.3, target/23.4

#6988 docs: fix incorrect type name in deprecation notice
  packages/grid/src/vaadin-grid-styling-mixin.d.ts
Labels: target/24.2, target/24.3

#6987 fix: stop propagation of click events on overlay
  integration/tests/context-menu-date-picker.test.js
  packages/date-picker/src/vaadin-date-picker-mixin.js
Labels: target/23.3, target/24.2, target/23.4, target/24.3

#6993 fix: remove double header border when using column groups without header
  packages/grid/theme/lumo/vaadin-grid-styles.js
Labels: target/24.3

#6995 fix: stop propagation of click events on overlay (#6987)
  integration/tests/context-menu-date-picker.test.js
  packages/date-picker/src/vaadin-date-picker-mixin.js
Labels: target/23.3

#6996 fix: do not throw when dir attribute is set initially
  packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
  packages/rich-text-editor/test/basic.common.js
Labels: target/24.3

#7011 chore: add missing type: module entry to package.json
  packages/multi-select-combo-box/package.json
Labels: target/24.2, target/24.3

#7021 docs: add missing mixes annotations to ActiveMixin JSDoc
  packages/a11y-base/src/active-mixin.js
Labels: target/24.2, target/24.3

#7020 docs: use correct mixins in vaadin-login-overlay JSDoc
  packages/login/src/vaadin-login-overlay-wrapper.js
Labels: target/24.2, target/24.3

#7028 docs: fix vaadin-grid-selection-column JSDoc annotations
  packages/grid/src/vaadin-grid-selection-column-base-mixin.d.ts
  packages/grid/src/vaadin-grid-selection-column-mixin.js
Labels: target/24.3

#7029 docs: add missing mixes annotations to ItemMixin JSDoc
  packages/item/src/vaadin-item-mixin.js
Labels: target/24.2, target/24.3

#7038 docs: remove customElement JSDoc from Lit based tooltip
  packages/tooltip/src/vaadin-lit-tooltip.js
Labels: target/24.3
