Repository vaadin/web-components, pull requests merged in 2023-04, with the labels that each got.

#5736 docs: remove no longer existing parts from JSDoc
  packages/details/src/vaadin-details.d.ts
  packages/details/src/vaadin-details.js
Labels: target/24.0

#5737 fix: align the toggle icon to the end in the reverse theme
  packages/accordion/src/vaadin-accordion-heading.js
  packages/accordion/test/visual/lumo/accordion-panel.test.js
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/basic.png
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/opened.png
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/rtl-basic.png
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/rtl-opened.png
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/rtl-theme-reverse-filled.png
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/rtl-theme-reverse.png
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/theme-reverse-filled.png
  packages/accordion/test/visual/lumo/screenshots/accordion-panel/baseline/theme-reverse.png
  packages/details/test/visual/lumo/details.test.js
  packages/details/test/visual/lumo/screenshots/details/baseline/rtl-theme-reverse-filled.png
  packages/details/test/visual/lumo/screenshots/details/baseline/rtl-theme-reverse.png
  packages/details/test/visual/lumo/screenshots/details/baseline/theme-reverse-filled.png
  packages/details/test/visual/lumo/screenshots/details/baseline/theme-reverse.png
Labels: target/24.0

#5754 fix: TypeScript typings for clearButtonVisible prop in field components
  packages/number-field/src/vaadin-number-field-mixin.d.ts
  packages/number-field/test/typings/number-field.types.ts
  packages/text-area/src/vaadin-text-area-mixin.d.ts
  packages/text-area/test/typings/text-area.types.ts
  packages/text-field/src/vaadin-text-field-mixin.d.ts
  packages/text-field/test/typings/text-field.types.ts
Labels: hilla, target/23.3, target/24.0

#5758 fix: TypeScript typings for clearButtonVisible prop in field components (CP: 24.0)
  packages/number-field/src/vaadin-number-field-mixin.d.ts
  packages/number-field/test/typings/number-field.types.ts
  packages/text-area/src/vaadin-text-area-mixin.d.ts
  packages/text-area/test/typings/text-area.types.ts
  packages/text-field/src/vaadin-text-field-mixin.d.ts
  packages/text-field/test/typings/text-field.types.ts
Labels: target/23.3

#5762 fix: hide bottom navbar when it's empty
  packages/app-layout/src/vaadin-app-layout.js
  packages/app-layout/test/app-layout.test.js
Labels: target/24.0

#5773 fix: create grid columns only after the grid header is configured
  packages/crud/src/vaadin-crud.js
  packages/crud/test/crud-grid-properties.test.js
  packages/crud/test/crud-grid.test.js
  packages/crud/test/helpers.js
Labels: target/24.0

#5785 fix: restore context menu opened state when moving within DOM
  packages/context-menu/src/vaadin-context-menu.js
  packages/context-menu/test/context.test.js
Labels: target/24.0

#5792 fix: keyboard navigation when using position fixed
  packages/a11y-base/src/focus-utils.js
  packages/a11y-base/test/focus-utils.test.js
Labels: target/23.3, target/24.0
