Repository vaadin/web-components, pull requests merged in 2023-03, with the labels that each got.

#5625 fix: reset _hasInputValue on programmatic input change
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/events.test.js
Labels: target/24.0

#5638 fix: update _hasInputValue on programmatic input change
  packages/time-picker/src/vaadin-time-picker-combo-box.js
  packages/time-picker/src/vaadin-time-picker.js
  packages/time-picker/test/events.test.js
Labels: target/24.0

#5624 fix: clear dragover row and cell parts on dragover change
  packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
  packages/grid/src/vaadin-grid-helpers.js
  packages/grid/src/vaadin-grid.js
  packages/grid/test/drag-and-drop.test.js
Labels: target/24.0

#5647 refactor: avoid unnecessary render cycles in the data provider callback
  packages/grid/src/vaadin-grid-data-provider-mixin.js
  packages/grid/test/data-provider.test.js
Labels: performance

#5646 fix: inflate functions in arrays
  packages/charts/src/helpers.js
  packages/charts/test/private-api.test.js
Labels: target/23.2, target/23.3, target/24.0

#5652 fix: make extension patterns match the end of the file name
  packages/upload/src/vaadin-upload.js
  packages/upload/test/adding-files.test.js
Labels: target/23.2, target/23.3, target/24.0

#5650 refactor: avoid unnecessary re-renders on virtualizer size change
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer.test.js
Labels: performance

#5661 fix: make extension patterns match the end of the file name (#5652) (CP: 23.3)
  packages/upload/src/vaadin-upload.js
  packages/upload/test/adding-files.test.js
Labels: target/23.2

#5670 fix: commit focused date on outside click
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/dropdown.test.js
Labels: target/23.3, target/24.0

#5693 fix: close notification on detach only if not immediately reattached
  .idea/workspace.xml
  packages/notification/src/vaadin-notification.js
  packages/notification/test/notification.test.js
Labels: target/24.0

#5692 fix: open detail when summary child components clicked
  packages/accordion/test/accordion.test.js
  packages/details/src/collapsible-mixin.js
  packages/details/test/details.test.js
Labels: target/24.0

#5698 fix: do not preserve bad input on value property change
  packages/time-picker/src/vaadin-time-picker.js
  packages/time-picker/test/time-picker.test.js
Labels: target/23.3, target/24.0

#5707 refactor: debounce tasks ran after creating grid rows
  packages/grid/src/vaadin-grid.js
Labels: performance

#5715 refactor: batch run virtualizer placeholder updates
  packages/component-base/src/virtualizer-iron-list-adapter.js
Labels: performance

#5713 refactor: minimize virtualizer item create rounds
  packages/combo-box/test/lazy-loading.test.js
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-item-height.test.js
  packages/grid/test/filtering.test.js
Labels: performance

#5696 fix: set only vertical margins of headings to zero
  packages/confirm-dialog/theme/lumo/vaadin-confirm-dialog-styles.js
  packages/crud/theme/lumo/vaadin-crud-styles.js
  packages/vaadin-lumo-styles/typography.js
Labels: target/24.0

#5723 refactor: use visibility to hide loading grid cells
  packages/grid/src/vaadin-grid-styles.js
  packages/grid/test/basic.test.js
Labels: performance
