Repository vaadin/web-components, pull requests merged in 2024-12, with the labels that each got.

#8273 refactor: extract common sub-menu logic into reusable mixin
  packages/menu-bar/src/vaadin-lit-menu-bar-submenu.js
  packages/menu-bar/src/vaadin-menu-bar-submenu-mixin.js
  packages/menu-bar/src/vaadin-menu-bar-submenu.js
Labels: target/24.5

#8270 fix: clear value when removing the last input
  packages/custom-field/src/vaadin-custom-field-mixin.js
  packages/custom-field/test/custom-field.common.js
Labels: target/24.4, target/24.5

#8268 fix: observe internal layout to avoid problems with fixed height
  packages/form-layout/src/vaadin-form-layout.js
  packages/form-layout/test/form-layout.test.js
Labels: target/24.4, target/24.5

#8272 fix: do not stop click event propagation on menu-bar button
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/menu-bar/src/vaadin-menu-bar-mixin.js
  packages/menu-bar/src/vaadin-menu-bar-submenu-mixin.js
  packages/menu-bar/test/sub-menu.common.js
Labels: target/24.5

#8278 fix: use Math.round to get correct scroller first index
  packages/date-picker/src/vaadin-infinite-scroller.js
  packages/date-picker/test/scroller.test.js
Labels: target/24.4, target/23.5, target/24.5

#8291 fix: prevent notification from affecting overlay interactions
  packages/overlay/src/vaadin-overlay-stack-mixin.js
  test/integration/not-animated-styles.js
  test/integration/notification-overlay.test.js
Labels: target/24.5, target/24.6

#8294 fix: do not show required indicator when checkbox has no label
  packages/checkbox/test/visual/lumo/checkbox.test.js
  packages/checkbox/test/visual/lumo/screenshots/checkbox/baseline/required-empty.png
  packages/checkbox/test/visual/material/checkbox.test.js
  packages/checkbox/test/visual/material/screenshots/checkbox/baseline/required-empty.png
  packages/checkbox/theme/lumo/vaadin-checkbox-styles.js
  packages/checkbox/theme/material/vaadin-checkbox-styles.js
Labels: target/24.4, target/24.5, target/24.6

#8116 fix: update media query to work with larger phones
  packages/context-menu/src/vaadin-context-menu-mixin.js
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/theme/lumo/vaadin-date-picker-overlay-styles.js
  packages/date-picker/theme/lumo/vaadin-date-picker-styles.js
  packages/select/src/vaadin-select-base-mixin.js
  packages/vaadin-lumo-styles/mixins/menu-overlay.js
Labels: target/24.5, target/24.6

#8304 fix: do not lose dashboard widget focus in shadow root
  packages/dashboard/src/vaadin-dashboard.js
  packages/dashboard/test/dashboard.test.ts
Labels: target/24.6

#8301 fix: prevent unselecting already committed value on outside click
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal-mixin.js
  packages/multi-select-combo-box/test/selecting-items.common.js
Labels: target/24.6

#8308 fix: do not fire custom-value-set on input blur or outside click
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal-mixin.js
  packages/multi-select-combo-box/test/basic.common.js
  packages/multi-select-combo-box/test/selecting-items.common.js
Labels: target/24.6

#8317 fix: prevent repeated selection attempts during drag selection
  packages/grid/src/vaadin-grid-selection-column-base-mixin.js
  packages/grid/test/selection.common.js
Labels: target/24.5, target/24.6

#8307 fix: hide toggle items text
  packages/side-nav/src/vaadin-side-nav-item.js
  packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
Labels: target/24.5, target/24.6

#8325 fix: add missing section type to dashboard events
  packages/dashboard/src/vaadin-dashboard.d.ts
  packages/dashboard/test/typings/dashboard.types.ts
Labels: target/24.6

#8350 fix: ignore target set while popover is detached until re-attached
  packages/popover/src/vaadin-popover-target-mixin.js
  packages/popover/test/basic.test.js
Labels: target/24.5, target/24.6

#8351 fix: hide scroller completely when dragging large grids
  packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
  packages/grid/test/drag-and-drop.common.js
  packages/virtual-list/src/vaadin-virtual-list-mixin.js
  packages/virtual-list/test/drag-and-drop.common.js
Labels: target/23.5, target/24.5, target/24.6

#8370 test: use nextUpdate to stabilize dashboard tests on Webkit
  packages/dashboard/test/dashboard.test.ts
  packages/dashboard/test/helpers.ts
Labels: target/24.6

#8359 fix: slot dashboard widgets instead of dom reordering
  packages/dashboard/src/vaadin-dashboard-section.js
  packages/dashboard/src/vaadin-dashboard.js
  packages/dashboard/test/dashboard-keyboard.test.ts
  packages/dashboard/test/dashboard-widget-reordering.test.ts
  packages/dashboard/test/dashboard.test.ts
Labels: target/24.6

#8375 chore: pin ubuntu version in GitHub Actions
  .github/workflows/coverage.yml
  .github/workflows/unit-tests.yml
  .github/workflows/verify.yml
  .github/workflows/visual-tests.yml
Labels: target/24.4, target/23.5, target/24.5, target/24.6

#8387 test: replace onceResized with nextResize
  packages/app-layout/test/app-layout.common.js
  packages/app-layout/test/not-animated-styles.js
  packages/avatar-group/test/avatar-group.common.js
  packages/board/test/helpers.js
  packages/board/test/redraw.test.js
  packages/charts/test/chart-element.test.js
  packages/component-base/test/overflow-controller.test.js
  packages/component-base/test/resize-mixin.test.js
  packages/dashboard/test/dashboard-keyboard.test.ts
  packages/dashboard/test/dashboard-layout.test.ts
  packages/dashboard/test/dashboard-widget-reordering.test.ts
  packages/dashboard/test/dashboard-widget-resizing.test.ts
  packages/dashboard/test/dashboard.test.ts
  packages/dashboard/test/helpers.ts
  packages/dialog/test/header-footer.common.js
  packages/form-layout/test/form-layout.common.js
  packages/grid/test/column-groups.common.js
  packages/grid/test/column-rendering.common.js
  packages/grid/test/frozen-columns.common.js
  packages/grid/test/helpers.js
  packages/grid/test/min-height.common.js
  packages/grid/test/resizing.common.js
  packages/grid/test/scrolling-mode.common.js
  packages/icon/test/icon-font.common.js
  packages/menu-bar/test/overflow.common.js
  packages/multi-select-combo-box/test/chips.common.js
  packages/tabs/test/tabs.common.js
  packages/text-area/test/text-area.common.js
Labels: target/24.5, target/24.6

#8384 fix: ensure error message is announced by VoiceOver
  packages/checkbox-group/test/dom/__snapshots__/checkbox-group.test.snap.js
  packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js
  packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js
  packages/custom-field/test/dom/__snapshots__/custom-field.test.snap.js
  packages/date-picker/test/dom/__snapshots__/date-picker.test.snap.js
  packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js
  packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
  packages/field-base/src/error-controller.js
  packages/field-base/test/field-mixin.test.js
  packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js
  packages/login/test/dom/__snapshots__/login-form.test.snap.js
  packages/multi-select-combo-box/test/dom/__snapshots__/multi-select-combo-box.test.snap.js
  packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
  packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
  packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js
  packages/select/test/dom/__snapshots__/select.test.snap.js
  packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
  packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
  packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js
Labels: target/24.5, target/24.6

#8399 fix: get the correct reference to the Notification class
  packages/notification/src/vaadin-notification-mixin.js
Labels: target/24.6

#8402 fix: do not close select overlay when opened before attached
  packages/select/src/vaadin-select-base-mixin.js
  packages/select/test/lit-renderer-directives.common.js
  packages/select/test/select.common.js
Labels: target/24.5, target/24.6
