Repository vaadin/web-components, pull requests merged in 2024-07, with the labels that each got.

#7504 fix: do not show placeholder when select item has child elements
  packages/select/src/vaadin-select-base-mixin.js
  packages/select/test/select.common.js
Labels: target/24.3, target/24.4

#7510 Update badge.js
  packages/vaadin-lumo-styles/badge.js
Labels: target/24.4, target/23.5

#7516 fix: select date on Today click if today is max date
  packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js
  packages/date-picker/test/overlay-content.common.js
Labels: target/24.3, target/24.4

#7519 fix: only focus parent item if sub-menu contained focus
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/context-menu/test/items.common.js
Labels: target/24.3, target/24.4

#7521 fix: allow helper disallowed char patterns set for input
  packages/field-base/src/input-control-mixin.js
  packages/field-base/test/input-control-mixin.test.js
Labels: target/24.3, target/24.4

#7524 fix: wait for updateComplete before setting positionTarget
  packages/menu-bar/src/vaadin-menu-bar-mixin.js
Labels: target/24.4

#7534 docs: add missing JSDoc annotation for resized event
  packages/dialog/src/vaadin-dialog-resizable-mixin.js
Labels: target/24.3, target/24.4

#7529 fix: allow the content part of details summary the remainder of the width
  packages/details/theme/lumo/vaadin-details-summary-styles.js
Labels: target/24.3, target/24.4

#7542 fix: render at most 7 weekdays in datepicker
  packages/date-picker/src/vaadin-month-calendar-mixin.js
  packages/date-picker/test/month-calendar.common.js
Labels: target/24.3, target/24.4

#7554 fix: only close combo-box overlay on blur from keyboard
  integration/tests/dialog-combo-box.test.js
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/interactions.common.js
  packages/time-picker/src/vaadin-time-picker.js
Labels: target/24.3, target/24.4

#7560 fix: remove ARIA attributes when time-picker has no dropdown
  packages/time-picker/src/vaadin-time-picker.js
  packages/time-picker/test/aria.test.js
Labels: target/24.3, target/24.4

#7558 fix: update Quill, disconnect and connect emitter
  packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
  packages/rich-text-editor/test/basic.common.js
  packages/rich-text-editor/vendor/vaadin-quill.js
Labels: target/24.3, target/24.4

#7566 fix: position loader part correctly in RTL mode
  packages/combo-box/test/visual/common.js
  packages/combo-box/test/visual/lumo/combo-box.test.js
  packages/combo-box/test/visual/lumo/screenshots/combo-box/baseline/ltr-loading.png
  packages/combo-box/test/visual/lumo/screenshots/combo-box/baseline/ltr-opened.png
  packages/combo-box/test/visual/lumo/screenshots/combo-box/baseline/opened.png
  packages/combo-box/test/visual/lumo/screenshots/combo-box/baseline/rtl-loading.png
  packages/combo-box/test/visual/lumo/screenshots/combo-box/baseline/rtl-opened.png
  packages/combo-box/theme/lumo/vaadin-combo-box-overlay-styles.js
Labels: target/24.3, target/24.4

#7577 fix: allow focusing date-picker input using keyboard on fullscreen
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/fullscreen.common.js
Labels: target/24.3, target/24.4

#7573 fix: do not set placeholder to empty string by default
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
  packages/multi-select-combo-box/test/accessibility.test.js
  packages/multi-select-combo-box/test/dom/__snapshots__/multi-select-combo-box.test.snap.js
Labels: target/24.3, target/24.4

#7599 fix: prevent scroll when restoring focus not from keyboard
  packages/a11y-base/src/focus-restoration-controller.js
  packages/a11y-base/test/focus-restoration-controller.test.js
  packages/overlay/src/vaadin-overlay-focus-mixin.js
  packages/overlay/test/restore-focus.common.js
Labels: target/24.3, target/24.4

#7601 refactor: update select to use overlay focus restoration logic
  packages/select/src/vaadin-select-base-mixin.js
  packages/select/src/vaadin-select-overlay-mixin.js
  packages/select/test/keyboard.common.js
Labels: target/24.3, target/24.4
