Repository vaadin/web-components, pull requests merged in 2024-03, with the labels that each got.

#7165 fix: delay column width recalculation until all rows have index
  packages/grid/src/vaadin-grid-mixin.js
  packages/grid/test/column-auto-width.common.js
Labels: target/24.2, target/24.3

#7167 fix: use correct custom CSS property for input field height
  packages/input-container/theme/lumo/vaadin-input-container-styles.js
Labels: target/24.3

#7181 fix: allow to prevent creating default slotted buttons
  packages/crud/src/vaadin-crud-controllers.js
  packages/crud/src/vaadin-crud.js
  packages/crud/test/crud-buttons.test.js
Labels: target/24.2, target/24.3

#7195 docs: update vaadin-checkbox typings to use correct mixin
  packages/checkbox/src/vaadin-checkbox.d.ts
  packages/checkbox/test/typings/checkbox.types.ts
Labels: target/24.2, target/24.3

#7203 fix: reset tabindex to -1 when initializing menu item
  packages/context-menu/src/vaadin-contextmenu-items-mixin.js
  packages/context-menu/test/items.common.js
  packages/menu-bar/test/sub-menu.common.js
Labels: target/24.3

#7206 fix: add click listener in constructor to ensure listener order (CP: 24.3)
  packages/grid/src/vaadin-grid-tree-toggle-mixin.js
  packages/grid/test/tree-toggle.common.js
Labels: target/24.2

#7215 fix: do not override theme attribute set on slotted buttons
  packages/crud/src/vaadin-crud-controllers.js
  packages/crud/test/crud-buttons.test.js
Labels: target/24.2, target/24.3

#7201 fix: observe tabs ID attribute changes and update panels
  packages/tabsheet/src/vaadin-tabsheet-mixin.js
  packages/tabsheet/test/tabsheet.test.js
Labels: target/24.3

#7205 Revert "refactor: avoid unnecessary re-renders on virtualizer size change (#5650)"
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-unlimited-size.test.js
  packages/component-base/test/virtualizer.test.js
  packages/grid/test/basic.common.js
Labels: target/24.3

#7230 fix: focus first non-disabled item if all items have tabindex -1
  packages/a11y-base/src/keyboard-direction-mixin.js
  packages/a11y-base/src/list-mixin.js
  packages/a11y-base/test/list-mixin.test.js
  packages/context-menu/test/items.common.js
  packages/menu-bar/test/sub-menu.common.js
Labels: target/24.3

#7240 fix: render message avatars with Lit to keep them on items update
  packages/message-list/src/vaadin-message-list.js
  packages/message-list/test/message-list.test.js
Labels: target/24.3

#7250 fix: fire change event on hyperlink edit, update test timings
  packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
  packages/rich-text-editor/test/basic.common.js
Labels: target/23.4, target/24.3

#7268 fix: calculate vidxOffset correctly when clientHeight != offsetHeight
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer-unlimited-size.test.js
Labels: target/24.3

#7274 fix: only create focus button mode div for body cells
  packages/grid/src/vaadin-grid-mixin.js
  packages/grid/test/keyboard-navigation-cell-button.common.js
Labels: target/24.3

#7273 fix: handle focus button mode columns for reordering
  packages/grid-pro/test/keyboard-navigation.common.js
  packages/grid/src/vaadin-grid-column-reordering-mixin.js
  packages/grid/test/column-reordering.common.js
Labels: target/24.3

#7275 fix: update vaadin-grid-filter to use input event instead of value-changed
  packages/grid/src/vaadin-grid-filter-element-mixin.js
  packages/grid/test/filtering.common.js
Labels: target/24.3

#7288 fix: close select overlay when clicking already selected item
  packages/select/src/vaadin-select-base-mixin.js
  packages/select/test/select.common.js
Labels: target/24.3

#7235 fix: focus editor only after it is ready
  packages/grid-pro/src/vaadin-grid-pro-edit-column-mixin.js
  packages/grid-pro/test/edit-column-type.common.js
Labels: target/24.3
