Repository vaadin/web-components, pull requests merged in 2024-11, with the labels that each got.

#8068 fix: exclude unchecked checkboxes from login form submissions
  packages/login/package.json
  packages/login/src/vaadin-login-form-mixin.js
  packages/login/test/login-submit-lit.test.js
  packages/login/test/login-submit-polymer.test.js
  packages/login/test/login-submit.common.js
Labels: target/24.4, target/24.5

#8093 fix: do not open popover after mouseleave during hover delay
  packages/popover/src/vaadin-popover.js
  packages/popover/test/timers.test.js
Labels: target/24.5

#8095 fix: set max-height on popover overlay to not overflow viewport
  packages/popover/src/vaadin-popover-overlay.js
  packages/popover/test/basic.test.js
Labels: target/24.5

#8102 fix: ensure grid has tabbable elements after it becomes visible
  packages/grid/src/vaadin-grid-mixin.js
  packages/grid/test/hidden-grid.common.js
Labels: target/24.4, target/24.5

#8117 fix: do not reset configuration if chart is immediately re-attached
  packages/charts/src/vaadin-chart.js
  packages/charts/test/reattach.test.js
Labels: target/24.4, target/23.5, target/24.5

#8115 fix: reset charts series objects when chart is detached
  packages/charts/src/vaadin-chart-series.js
  packages/charts/src/vaadin-chart.js
  packages/charts/test/reattach.test.js
Labels: target/24.4, target/23.5, target/24.5

#8131 fix: handle tooltip controller closing state properly
  packages/tooltip/src/vaadin-tooltip-mixin.js
  packages/tooltip/test/tooltip-timers.common.js
Labels: target/24.4, target/24.5

#8141 fix: set input value font weight property on input container
  packages/input-container/theme/lumo/vaadin-input-container-styles.js
  packages/vaadin-lumo-styles/mixins/input-field-shared.js
  packages/vaadin-lumo-styles/style.js
Labels: target/24.4, target/24.5

#8156 feat: grid-pro loading editor state
  packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
  packages/grid-pro/test/keyboard-navigation.common.js
  packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
Labels: target/24.3, target/24.4, target/24.5

#8174 fix: prevent year scroller from getting focused in Chrome
  packages/date-picker/src/vaadin-infinite-scroller.js
  packages/date-picker/test/dom/__snapshots__/date-picker-year-scroller.test.snap.js
  packages/date-picker/test/dom/date-picker-year-scroller.test.js
Labels: target/24.4, target/24.5

#8181 fix: do not render hidden combo box items
  packages/combo-box/src/vaadin-combo-box-item-mixin.js
  packages/combo-box/test/item-renderer.common.js
Labels: target/24.5

#8189 fix: align prefix and suffix with textarea in Material theme
  packages/text-area/test/visual/material/screenshots/text-area/baseline/prefix.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/scrolled-with-prefix-suffix-clear-button.png
  packages/text-area/test/visual/material/screenshots/text-area/baseline/suffix.png
  packages/text-area/test/visual/material/text-area.test.js
  packages/text-area/theme/material/vaadin-text-area-styles.js
Labels: target/24.5

#8208 fix: do not close popover when it is just moved in DOM
  packages/popover/src/vaadin-popover.js
  packages/popover/test/basic.test.js
Labels: target/24.5

#8211 refactor: remove z-index override from tooltip overlay
  packages/tooltip/src/vaadin-tooltip-overlay-styles.js
Labels: target/24.5

#8207 fix: make text area auto-sizing stable
  packages/text-area/src/vaadin-text-area-mixin.js
Labels: target/24.4, target/23.5, target/24.5

#8217 fix: force scroller update after revealing a date
  packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js
  packages/date-picker/src/vaadin-infinite-scroller.js
  packages/date-picker/test/custom-input.test.js
  packages/date-picker/test/dropdown.common.js
  packages/date-picker/test/events.common.js
  packages/date-picker/test/fullscreen.common.js
  packages/date-picker/test/helpers.js
  packages/date-picker/test/keyboard-input.common.js
  packages/date-picker/test/keyboard-navigation.common.js
  packages/date-picker/test/theme-propagation.common.js
  packages/date-picker/test/value-commit.common.js
  packages/grid/test/column-rendering.common.js
  test/integration/context-menu-date-picker.test.js
  test/integration/dialog-date-picker.test.js
Labels: target/24.4, target/24.5

#8232 fix: do not dispatch event on stopedit when editor loading
  packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
  packages/grid-pro/test/keyboard-navigation.common.js
Labels: target/24.4, target/24.5
