Repository vaadin/web-components, pull requests merged in 2024-10, with the labels that each got.

#7899 fix: bump Quill to fix error thrown on deleting text
  packages/rich-text-editor/vendor/vaadin-quill.js
  packages/rich-text-editor/vendor/vaadin-quill.js.map
Labels: target/24.4, target/24.5

#7908 fix: validate date-time-picker when required is set to false
  packages/date-time-picker/src/vaadin-date-time-picker.js
  packages/date-time-picker/test/validation.test.js
Labels: target/24.4, target/24.5

#7912 fix: remove not working vaadin-lit-date-picker-light entrypoint
  packages/date-picker/vaadin-lit-date-picker-light.d.ts
  packages/date-picker/vaadin-lit-date-picker-light.js
Labels: target/24.4, target/24.5

#7917 fix: use correct ComboBoxScrollerMixin import in typings
  packages/combo-box/src/vaadin-combo-box-scroller.d.ts
Labels: target/24.4, target/24.5

#7923 fix: validate custom-field when required is set to false
  packages/custom-field/src/vaadin-custom-field-mixin.js
  packages/custom-field/test/validation.common.js
Labels: target/24.4, target/24.5

#7890 fix: delay parsing htmlValue when RTE is attached but not rendered
  packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
  packages/rich-text-editor/test/attach-lit.test.js
  packages/rich-text-editor/test/attach-polymer.test.js
  packages/rich-text-editor/test/attach.common.js
  packages/rich-text-editor/test/basic.common.js
Labels: target/24.4

#7925 fix: add missing export for SelectListBox element class
  packages/select/src/vaadin-lit-select-list-box.js
  packages/select/src/vaadin-select-list-box.js
Labels: target/24.4, target/24.5

#7933 fix: do not throw when setting checkbox-group value to null
  packages/checkbox-group/src/vaadin-checkbox-group-mixin.js
  packages/checkbox-group/test/checkbox-group.common.js
  packages/checkbox-group/test/validation.common.js
Labels: target/24.4, target/24.5

#7938 docs: fix popover JSDoc to use correct parameter name
  packages/popover/src/vaadin-popover.d.ts
  packages/popover/src/vaadin-popover.js
Labels: target/24.5

#7939 docs: fix tooltip JSDoc to use correct parameter name
  packages/tooltip/src/vaadin-tooltip-mixin.js
  packages/tooltip/src/vaadin-tooltip.d.ts
Labels: target/24.4, target/24.5

#7988 fix: update form-layout when its parent becomes visible
  packages/form-layout/src/vaadin-form-layout.js
  packages/form-layout/test/form-layout.test.js
Labels: target/24.4, target/24.5

#7995 refactor: clean up keyboard navigation mixin (#7977) (CP: 24.5)
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
Labels: target/24.4

#7980 fix: ensure no focus outline when item is scrolled out of view
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/src/vaadin-grid-styles.js
  packages/grid/test/helpers.js
  packages/grid/test/keyboard-navigation.common.js
Labels: target/24.4, target/24.5

#8017 fix: clear input values when setting value property to null
  packages/custom-field/src/vaadin-custom-field-mixin.js
  packages/custom-field/test/custom-field.common.js
  packages/custom-field/test/validation.common.js
Labels: target/24.4, target/24.5

#8012 fix: prevent possible errors when inputs property is not set
  packages/custom-field/src/vaadin-custom-field-mixin.js
  packages/custom-field/test/validation.common.js
Labels: target/24.4, target/24.5

#8021 fix: use non timezone-aware date APIs in date time picker
  packages/date-picker/src/vaadin-date-picker-helper.js
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-time-picker/src/vaadin-date-time-picker.js
  packages/date-time-picker/test/basic.test.js
  packages/date-time-picker/test/timezone.test.js
Labels: target/24.4, target/24.5

#8034 Revert "fix: add min-width to MenuBar"
  packages/menu-bar/theme/lumo/vaadin-menu-bar-styles.js
Labels: target/24.5

#8037 docs: update default values in upload i18n
  packages/upload/src/vaadin-upload-mixin.d.ts
  packages/upload/src/vaadin-upload-mixin.js
Labels: target/24.5

#8028 fix: exclude items from drag image for large scrollers
  packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
  packages/grid/test/drag-and-drop.common.js
  packages/virtual-list/src/vaadin-virtual-list-mixin.js
  packages/virtual-list/test/drag-and-drop-lit.test.js
  packages/virtual-list/test/drag-and-drop-polymer.test.js
  packages/virtual-list/test/drag-and-drop.common.js
Labels: target/24.4, target/23.5, target/24.5

#8063 fix: import src version of vaadin-tabs in tabsheet
  packages/tabsheet/src/vaadin-tabsheet.js
Labels: target/24.5
