Repository vaadin/web-components, pull requests merged in 2025-06, with the labels that each got.

#9378 fix: do not reopen manual tooltips on overlay mouseenter
  packages/tooltip/src/vaadin-tooltip-mixin.js
  packages/tooltip/test/tooltip.test.js
Labels: target/24.7, target/24.8

#9396 chore: support glob parameter with integration tests
  wtr-utils.js
Labels: target/24.8

#9397 fix: allow popover to close while tooltip is open
  packages/overlay/src/vaadin-overlay-stack-mixin.js
  packages/popover/src/vaadin-popover.js
  test/integration/popover-tooltip.test.js
Labels: target/24.7, target/24.8

#9401 fix: allow popover to close while tooltip is open (#9397) (CP: 24.8)
  packages/overlay/src/vaadin-overlay-stack-mixin.js
  packages/popover/src/vaadin-popover.js
  test/integration/popover-tooltip.test.js
Labels: target/24.7

#9457 fix: set min-width in form-item content
  packages/form-layout/src/styles/vaadin-form-item-styles.js
  packages/form-layout/test/visual/lumo/form-layout-auto-responsive.test.js
  packages/form-layout/test/visual/lumo/form-layout.test.js
  packages/form-layout/test/visual/lumo/screenshots/form-layout-auto-responsive/baseline/min-columns-labels-aside.png
  packages/form-layout/test/visual/lumo/screenshots/form-layout/baseline/colspan-alignment.png
Labels: target/24.7, target/24.8

#9475 fix: scroll focus target into view when row is larger than viewport
  packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
  packages/grid/src/vaadin-grid-scroll-mixin.js
  packages/grid/test/scroll-into-view.test.js
Labels: target/24.7, target/24.8

#9537 docs: fix JSDoc for all-imports entrypoint to use .js
  packages/grid/src/vaadin-grid.d.ts
  packages/grid/src/vaadin-grid.js
Labels: target/24.8
