Repository vaadin/web-components, pull requests merged in 2025-03, with the labels that each got.

#8757 fix: improve context menu positioning when opening menu with keyboard
  packages/context-menu/src/vaadin-contextmenu-event.js
  test/integration/context-menu-grid.test.js
Labels: target/24.6, target/24.7

#8791 fix: avoid removing selected ranges on component initialization
  packages/context-menu/src/vaadin-context-menu-mixin.js
  packages/context-menu/test/overlay.test.js
Labels: target/24.5, target/24.6, target/24.7

#8803 fix: do not prevent closing on backdrop click
  packages/popover/src/vaadin-popover-overlay.js
  packages/popover/test/trigger.test.js
Labels: target/24.5, target/24.6, target/24.7

#8815 fix: close popover immediately on mouseleave while opening
  packages/popover/src/vaadin-popover.js
  packages/popover/test/timers.test.js
Labels: target/24.5, target/24.6, target/24.7

#8816 fix: provide i18n property declaration
  packages/component-base/src/i18n-mixin.js
Labels: target/24.7

#8830 fix: only set has-bounds-set attribute on dialog resize
  packages/dialog/src/vaadin-dialog-overlay-mixin.js
  packages/dialog/src/vaadin-dialog-resizable-mixin.js
  packages/dialog/test/draggable-resizable.test.js
Labels: target/24.6, target/24.7

#8835 chore: upgrade web-test-runner dependency versions
  package.json
  test/test-runner-commands/index.js
  yarn.lock
Labels: target/24.6, target/24.7

#8852 fix: set shiftKey correctly on mousedown + Shift + mouseup
  packages/grid/src/vaadin-grid-selection-column-base-mixin.js
  packages/grid/test/selection.test.js
Labels: target/24.6, target/24.7

#8856 fix: defer scrollToIndex calls until columnTree is available
  packages/grid/src/vaadin-grid-data-provider-mixin.js
  packages/grid/test/scroll-to-index.test.js
Labels: target/24.6, target/24.7
