Repository vaadin/web-components, pull requests merged in 2025-01, with the labels that each got.

#8421 fix: always strip input value to match step interval
  packages/time-picker/src/vaadin-time-picker-mixin.js
  packages/time-picker/test/value-commit.common.js
Labels: target/24.5, target/24.6

#8438 refactor: replace h5 in login error message with strong
  packages/login/src/vaadin-lit-login-form-wrapper.js
  packages/login/src/vaadin-login-form-wrapper.js
  packages/login/test/dom/__snapshots__/login-form.test.snap.js
  packages/login/theme/lumo/vaadin-login-form-wrapper-styles.js
  packages/login/theme/material/vaadin-login-form-wrapper-styles.js
Labels: target/24.5, target/24.6

#8441 refactor: use div with heading role instead of h2 in form title
  packages/login/src/vaadin-lit-login-form-wrapper.js
  packages/login/src/vaadin-login-form-wrapper.js
  packages/login/test/dom/__snapshots__/login-form.test.snap.js
  packages/login/theme/lumo/vaadin-login-form-wrapper-styles.js
  packages/login/theme/material/vaadin-login-form-wrapper-styles.js
  packages/login/theme/material/vaadin-login-overlay-styles.js
Labels: target/24.5, target/24.6

#8374 refactor: add updating-cell part styles
  packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
  packages/grid-pro/test/keyboard-navigation.common.js
  packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
Labels: target/24.5, target/24.6

#8455 fix: do not clear on Esc with clear button visible when readonly
  packages/combo-box/src/vaadin-combo-box-mixin.js
  packages/combo-box/test/keyboard.common.js
  packages/date-picker/src/vaadin-date-picker-mixin.js
  packages/date-picker/test/basic.common.js
  packages/field-base/src/clear-button-mixin.js
  packages/field-base/test/clear-button-mixin.test.js
  packages/multi-select-combo-box/test/basic.common.js
Labels: target/24.4, target/24.5, target/24.6

#8465 test: fix flaky RTE test by moving Tab tests to a separate suite
  packages/rich-text-editor/test/a11y.common.js
Labels: target/24.5, target/24.6

#8461 test: fix local test failures in Firefox
  packages/dialog/test/draggable-resizable.common.js
  packages/field-base/test/field-mixin.test.js
Labels: target/24.5, target/24.6

#8467 fix: also apply focus-ring width custom property to invalid state
  packages/vaadin-lumo-styles/mixins/input-field-shared.js
Labels: target/24.5, target/24.6

#8477 refactor: remove global dashboard widget styles
  packages/dashboard/theme/lumo/vaadin-dashboard-section-styles.js
  packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js
Labels: target/24.6

#8483 fix: add missing hidden attribute styles to board and board row
  packages/board/src/vaadin-board-row.js
  packages/board/src/vaadin-board.js
Labels: target/24.5, target/24.6

#8496 fix: add missing colon in responsive alignment utility classes
  packages/vaadin-lumo-styles/utilities/flexbox-grid.js
Labels: target/24.5, target/24.6

#8500 fix: do not stop ignored dragleave events in grid
  packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
  packages/grid/test/drag-and-drop.common.js
Labels: target/24.5, target/24.6

#8529 fix: avoid content outside grid ending up in drag image
  packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
  packages/virtual-list/src/vaadin-virtual-list-mixin.js
Labels: target/24.6

#8535 fix: prevent grid with all rows visible from shrinking
  packages/grid/src/vaadin-grid-styles.js
  packages/grid/test/min-height.common.js
  packages/grid/test/resizing.common.js
Labels: target/24.6

#8533 fix: check if node is an element when removing slot attribute
  packages/split-layout/src/vaadin-split-layout-mixin.js
  packages/split-layout/test/split-layout.common.js
Labels: target/24.5, target/24.6

#8559 fix: allow all rows visible grid shrink horizontally
  packages/grid/src/vaadin-grid-styles.js
  packages/grid/test/min-height.common.js
  packages/grid/test/resizing.common.js
Labels: target/24.6

#8574 test: wait for possible scroll into view
  packages/grid-pro/test/keyboard-navigation.common.js
Labels: target/24.5, target/24.6

#8585 test: another attempt to stabilize grid-pro test
  packages/grid-pro/test/keyboard-navigation.common.js
Labels: target/24.5, target/24.6

#8536 test: add shortcut for pressing multiple keys simultaneously
  packages/a11y-base/test/focus-trap-controller.test.js
  packages/app-layout/test/helpers.js
  packages/checkbox-group/test/checkbox-group.common.js
  packages/checkbox-group/test/validation.common.js
  packages/checkbox/test/validation.common.js
  packages/component-base/test/virtualizer-reorder-elements.test.js
  packages/context-menu/test/a11y.common.js
  packages/dashboard/test/dashboard-keyboard.test.ts
  packages/date-picker/test/fullscreen.common.js
  packages/date-picker/test/keyboard-input.common.js
  packages/date-picker/test/keyboard-navigation.common.js
  packages/date-time-picker/test/validation.common.js
  packages/field-highlighter/test/field-components.test.js
  packages/grid-pro/test/edit-column.common.js
  packages/grid-pro/test/keyboard-navigation.common.js
  packages/grid/test/disabled.common.js
  packages/grid/test/keyboard-interaction-mode.common.js
  packages/grid/test/selection.common.js
  packages/menu-bar/test/accessible-disabled-buttons.common.js
  packages/menu-bar/test/menu-bar.common.js
  packages/menu-bar/test/sub-menu.common.js
  packages/password-field/test/password-field.common.js
  packages/popover/test/a11y.test.js
  packages/radio-group/test/radio-group.common.js
  packages/radio-group/test/validation.common.js
  packages/rich-text-editor/test/a11y.common.js
  packages/upload/test/file.common.js
  test/integration/dialog-accordion.test.js
  test/integration/dialog-date-picker.test.js
  test/integration/grid-pro-custom-editor.test.js
  test/integration/menu-bar-tooltip.test.js
  test/test-runner-commands/index.js
Labels: target/24.5, target/24.6

#8597 test: do not generate Lit test file for missing-import.test.js
  packages/list-box/test/missing-import-polymer.test.js
Labels: target/24.5, target/24.6

#8596 fix: use the most recent IntersectionObserver entry in form-layout
  packages/form-layout/src/vaadin-form-layout-mixin.js
Labels: target/24.5, target/24.6
