Repository vaadin/web-components, pull requests merged in 2025-05, with the labels that each got.

#9028 fix: reset width on menu-bar buttons when restoring them
  packages/menu-bar/src/vaadin-menu-bar-mixin.js
  packages/menu-bar/test/overflow.test.js
Labels: target/24.6, target/24.7

#9036 fix: set max-width on multi-select-combo-box to fix Chrome 136
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-styles.js
Labels: target/24.6, target/24.7

#9047 chore: use Node 22, switch to ES imports
  .github/workflows/coverage.yml
  .github/workflows/unit-tests.yml
  .github/workflows/verify.yml
  .github/workflows/visual-tests.yml
  package.json
  scripts/buildWebtypes.js
  scripts/check-releases.js
  scripts/cherryPick.js
  scripts/generateLitTests.js
  scripts/generateLumoAutoCompleteCss.js
  scripts/generateReleaseNotes.js
  scripts/prepareDocs.js
  scripts/updateVersion.js
  web-dev-server.config.js
  web-test-runner-firefox.config.js
  web-test-runner-it.config.js
  web-test-runner-lumo.config.js
  web-test-runner-material.config.js
  web-test-runner-snapshots.config.js
  web-test-runner-webkit.config.js
  web-test-runner.config.js
  wtr-utils.js
  yarn.lock
Labels: target/24.6, target/24.7

#9059 fix: do not throw with custom file list, add missing test
  packages/upload/src/vaadin-upload-mixin.js
  packages/upload/test/file-list.test.js
Labels: target/24.6, target/24.7

#9098 chore: workaround WTR tests hanging due to structuredClone
  package.json
  wtr-utils.js
  yarn.lock
Labels: target/24.6, target/24.7

#9124 fix: fire single event when changing accordion opened index
  packages/accordion/src/vaadin-accordion-mixin.js
  packages/accordion/test/accordion.test.js
Labels: target/24.6, target/24.7

#9156 fix: make single end slot aligned properly, add missing tests
  packages/horizontal-layout/src/vaadin-horizontal-layout-styles.js
  packages/horizontal-layout/test/visual/lumo/horizontal-layout.test.js
  packages/horizontal-layout/test/visual/lumo/screenshots/horizontal-layout/baseline/slots-only-end.png
  packages/horizontal-layout/test/visual/lumo/screenshots/horizontal-layout/baseline/slots-only-middle.png
Labels: target/24.7

#9177 fix: collapse all chips to overflow if there is not enough width
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.js
  packages/multi-select-combo-box/test/chips.test.js
Labels: target/24.6, target/24.7

#8962 refactor: update dashboard styles, add Lumo theme variants
  dev/dashboard-layout.html
  packages/dashboard/src/vaadin-dashboard-item-mixin.js
  packages/dashboard/src/vaadin-dashboard-layout-mixin.js
  packages/dashboard/src/vaadin-dashboard-section.js
  packages/dashboard/src/vaadin-dashboard-widget.d.ts
  packages/dashboard/src/vaadin-dashboard-widget.js
  packages/dashboard/src/vaadin-dashboard.js
  packages/dashboard/src/widget-resize-controller.js
  packages/dashboard/test/dashboard-layout.test.ts
  packages/dashboard/test/helpers.ts
  packages/dashboard/test/visual/lumo/dashboard.test.ts
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-default.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-dragged-widget.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-editable.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-focused-widget.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-move-mode.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-no-gap.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-no-title-wrap.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-non-editable.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-resize-mode.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-resized-widget.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-selected-widget.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-theme-elevated-widgets.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-theme-flat-widgets.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-theme-shaded-background.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/ltr-title-wrap.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-default.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-dragged-widget.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-editable.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-focused-widget.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-move-mode.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-no-gap.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-no-title-wrap.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-non-editable.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-resize-mode.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-resized-widget.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-selected-widget.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-theme-elevated-widgets.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-theme-flat-widgets.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-theme-shaded-background.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/rtl-title-wrap.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/theme-elevated-widgets.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/theme-flat-widgets.png
  packages/dashboard/test/visual/lumo/screenshots/dashboard/baseline/theme-shaded-background.png
  packages/dashboard/theme/lumo/vaadin-dashboard-layout-styles.js
  packages/dashboard/theme/lumo/vaadin-dashboard-section-styles.js
  packages/dashboard/theme/lumo/vaadin-dashboard-styles.js
  packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js
Labels: target/24.8

#8994 refactor: consolidate card styles with dashboard widget styles
  packages/card/test/visual/lumo/screenshots/card/baseline/theme-elevated.png
  packages/card/test/visual/lumo/screenshots/card/baseline/theme-media-cover-icon.png
  packages/card/test/visual/lumo/screenshots/card/baseline/theme-outlined-elevated.png
  packages/card/theme/lumo/vaadin-card-styles.js
Labels: target/24.8

#9213 fix: include border width in max-height calculation
  packages/text-area/src/vaadin-text-area-mixin.js
  packages/text-area/test/text-area.test.js
Labels: target/24.7, target/24.8

#9223 fix: defer scrollToIndex until grid is ready
  packages/grid/src/vaadin-grid-data-provider-mixin.js
  packages/grid/test/scroll-to-index.test.js
Labels: target/23.5, target/24.6, target/24.7, target/24.8

#9095 fix: sync top group if necessary even when dropdown is opened
  packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.js
  packages/multi-select-combo-box/test/selecting-items.test.js
Labels: target/23.5, target/24.6, target/24.7, target/24.8

#9254 fix: remove message list markdown outermost margins
  packages/message-list/src/vaadin-message-list.d.ts
  packages/message-list/src/vaadin-message-list.js
  packages/message-list/test/visual/lumo/message-list.test.js
  packages/message-list/test/visual/lumo/screenshots/message-list/baseline/ltr-markdown-margin-overrides.png
  packages/message-list/test/visual/lumo/screenshots/message-list/baseline/ltr-markdown.png
  packages/message-list/test/visual/lumo/screenshots/message-list/baseline/rtl-markdown-margin-overrides.png
  packages/message-list/test/visual/lumo/screenshots/message-list/baseline/rtl-markdown.png
Labels: target/24.8

#9252 feat: add message-list announceMessages API
  dev/messages.html
  packages/message-list/src/vaadin-message-list-mixin.d.ts
  packages/message-list/src/vaadin-message-list-mixin.js
  packages/message-list/test/dom/__snapshots__/message-list.test.snap.js
  packages/message-list/test/message-list.test.js
  packages/message-list/test/typings/message-list.types.ts
Labels: target/24.8

#9261 fix: resize app layout drawer based on content
  packages/app-layout/src/vaadin-app-layout-mixin.js
  packages/app-layout/test/app-layout.test.js
Labels: target/24.6, target/24.7, target/24.8

#9272 chore: remove card feature flag
  dev/card.html
  packages/card/README.md
  packages/card/src/vaadin-card.js
  packages/card/test/accessibility.test.js
  packages/card/test/card.test.ts
  packages/card/test/visual/lumo/card.test.js
Labels: target/24.8

#9283 fix: add missing Lumo color import to vaadin-item
  packages/item/test/visual/lumo/screenshots/item/baseline/ltr-basic.png
  packages/item/test/visual/lumo/screenshots/item/baseline/ltr-checkmark.png
  packages/item/test/visual/lumo/screenshots/item/baseline/ltr-multi-line.png
  packages/item/test/visual/lumo/screenshots/item/baseline/ltr-selected.png
  packages/item/test/visual/lumo/screenshots/item/baseline/rtl-basic.png
  packages/item/test/visual/lumo/screenshots/item/baseline/rtl-checkmark.png
  packages/item/test/visual/lumo/screenshots/item/baseline/rtl-multi-line.png
  packages/item/test/visual/lumo/screenshots/item/baseline/rtl-selected.png
  packages/item/theme/lumo/vaadin-item-styles.js
Labels: target/24.6, target/24.7, target/24.8

#9293 chore: remove dashboard feature flag
  dev/dashboard-layout.html
  dev/dashboard.html
  packages/dashboard/README.md
  packages/dashboard/src/vaadin-dashboard-button.js
  packages/dashboard/src/vaadin-dashboard-layout.js
  packages/dashboard/src/vaadin-dashboard-section.js
  packages/dashboard/src/vaadin-dashboard-widget.js
  packages/dashboard/src/vaadin-dashboard.js
  packages/dashboard/test/helpers.ts
Labels: target/24.8

#9329 fix: hide context menu overlay until rendered
  packages/context-menu/src/vaadin-context-menu-mixin.js
  packages/context-menu/test/overlay.test.js
  packages/menu-bar/test/sub-menu.test.js
Labels: target/24.7, target/24.8

#9332 fix: hide context-menu overlay until rendered (#9329) (CP: 24.8)
  packages/context-menu/src/vaadin-context-menu-mixin.js
  packages/context-menu/test/overlay.test.js
  packages/menu-bar/test/sub-menu.test.js
Labels: target/24.7
