Repository vaadin/web-components, pull requests merged in 2025-04, with the labels that each got.

#8890 fix: use array instead of object in slotStyles by default
  packages/component-base/src/slot-styles-mixin.js
Labels: target/24.6, target/24.7

#8896 fix: add hostConnected to virtualizer, use it in virtual-list and grid
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/src/virtualizer.js
  packages/component-base/test/virtualizer.test.js
  packages/grid/src/vaadin-grid-mixin.js
  packages/grid/test/basic.test.js
  packages/virtual-list/src/vaadin-virtual-list-mixin.js
  packages/virtual-list/test/virtual-list.test.js
Labels: target/24.6, target/24.7

#8907 fix: don't apply `inert` on master if there is no detail
  packages/master-detail-layout/src/vaadin-master-detail-layout.js
  packages/master-detail-layout/test/aria.test.js
Labels: vaadin-master-detail-layout

#8911 fix: do not generate effective i18n if custom i18n reference didn't chance
  packages/component-base/src/i18n-mixin.js
  packages/component-base/test/i18n-mixin.test.js
Labels: target/24.7

#8963 test: flush ignoreTaps debouncer after scroll
  packages/date-picker/test/basic.test.js
  packages/date-picker/test/custom-input.test.js
  packages/date-picker/test/dropdown.test.js
  packages/date-picker/test/events.test.js
  packages/date-picker/test/fullscreen.test.js
  packages/date-picker/test/helpers.js
  packages/date-picker/test/keyboard-input.test.js
  packages/date-picker/test/keyboard-navigation.test.js
  packages/date-picker/test/overlay-content.test.js
  packages/date-picker/test/theme-propagation.test.js
  packages/date-picker/test/validation.test.js
  packages/date-picker/test/value-commit.test.js
  packages/date-time-picker/test/validation.test.js
  packages/field-highlighter/test/field-components.test.js
  test/integration/dialog-date-picker.test.js
  test/integration/grid-pro-custom-editor.test.js
Labels: target/24.6, target/24.7

#8967 chore: ban ES2020-2021 operators only in component files
  .eslintrc.json
  packages/grid-pro/src/vaadin-grid-pro-edit-select-mixin.js
  packages/grid/src/vaadin-grid-column-auto-width-mixin.js
  packages/grid/src/vaadin-grid-helpers.js
Labels: target/24.6, target/24.7

#8912 fix: do not trap focus on item Tab, extract keyboard tests
  packages/menu-bar/src/vaadin-menu-bar-mixin.js
  packages/menu-bar/test/keyboard-navigation.test.js
  packages/menu-bar/test/menu-bar.test.js
  packages/menu-bar/test/sub-menu.test.js
Labels: target/24.6, target/24.7

#8930 fix: defer column with calculation until grid has height
  packages/grid/src/vaadin-grid-column-auto-width-mixin.js
  packages/grid/test/column-auto-width.test.js
Labels: target/24.7
