Repository vaadin/web-components, pull requests merged in 2025-02, with the labels that each got.

#8566 test: add sendMouseToElement test runner command
  packages/button/test/button.test.ts
  packages/button/test/visual/helpers.js
  packages/button/test/visual/lumo/button.test.js
  packages/button/test/visual/material/button.test.js
  packages/checkbox/test/checkbox.test.js
  packages/combo-box/test/visual/lumo/combo-box.test.js
  packages/dashboard/test/dashboard-widget-reordering.test.ts
  packages/date-picker/test/visual/lumo/date-picker.test.js
  packages/date-time-picker/test/basic.test.js
  packages/grid-pro/test/edit-column-renderer.test.js
  packages/grid/test/drag-and-drop.test.js
  packages/menu-bar/test/accessible-disabled-buttons.test.js
  packages/multi-select-combo-box/test/visual/lumo/multi-select-combo-box.test.js
  packages/number-field/test/visual/lumo/number-field.test.js
  packages/overlay/test/interactions.test.js
  packages/popover/test/trigger.test.js
  packages/radio-group/test/radio-button.test.js
  packages/text-area/test/visual/lumo/text-area.test.js
  packages/text-field/test/visual/lumo/text-field.test.js
  packages/time-picker/test/visual/lumo/time-picker.test.js
  packages/virtual-list/test/drag-and-drop.test.js
  test/integration/component-tooltip.test.js
  test/integration/grid-pro-custom-editor.test.js
  test/integration/menu-bar-tooltip.test.js
  test/test-runner-commands/index.js
Labels: target/24.5, target/24.6

#8573 chore: upgrade SauceLabs launcher to the latest version
  package.json
  wtr-utils.js
  yarn.lock
Labels: target/23.5, target/24.5, target/24.6

#8619 fix: fix Material combo box overlay sizing
  packages/combo-box/theme/material/vaadin-combo-box-overlay-styles.js
Labels: target/24.6

#8620 refactor: use _onResize instead of IntersectionObserver
  packages/form-layout/src/vaadin-form-layout-mixin.js
Labels: target/24.5, target/24.6

#8631 chore: upgrade puppeteer version in yarn.lock to 23.11.1
  test/test-runner-commands/index.js
  yarn.lock
Labels: target/24.5, target/24.6

#8655 test: add missing resetMouse to tests using sendMouse
  packages/grid/test/scroll-into-view.test.js
Labels: target/24.5, target/24.6

#8652 chore: upgrade playwright version to ^1.50
  package.json
  yarn.lock
Labels: target/24.5, target/24.6

#8659 test: switch from puppeteer to playwright chrome
  .github/workflows/unit-tests.yml
  .github/workflows/verify.yml
  package.json
  packages/a11y-base/test/active-mixin.test.js
  test/test-runner-commands/index.js
  web-test-runner-it.config.js
  web-test-runner-snapshots.config.js
  web-test-runner.config.js
  yarn.lock
Labels: target/24.5, target/24.6

#8642 fix: restore scroll position when virtualizer host is connected
  packages/component-base/src/virtualizer-iron-list-adapter.js
  packages/component-base/test/virtualizer.test.js
Labels: target/24.5, target/24.6

#8678 fix: place confirm-dialog footer correctly when height is set
  packages/confirm-dialog/src/vaadin-confirm-dialog-overlay-styles.js
  packages/confirm-dialog/test/confirm-dialog.test.js
Labels: target/24.5, target/24.6

#8722 fix: do not set position and max-width when dialog size is set
  packages/dialog/src/vaadin-dialog-base-mixin.js
  packages/dialog/src/vaadin-dialog-overlay-mixin.d.ts
  packages/dialog/src/vaadin-dialog-overlay-mixin.js
  packages/dialog/test/dialog.test.js
Labels: target/24.6

#8727 fix: always close select on outside click when in modeless dialog
  packages/select/src/vaadin-select-overlay-mixin.js
  test/integration/dialog-select.test.js
Labels: target/24.6

#8732 fix: check if popover target has focusElement as focusable
  packages/popover/src/vaadin-popover.js
  packages/popover/test/a11y.test.js
Labels: target/24.5, target/24.6, target/24.7

#8746 test: regenerate snapshots to match order in respective tests
  packages/crud/test/dom/__snapshots__/crud.test.snap.js
  packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
  packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
  packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
  packages/upload/test/dom/__snapshots__/vaadin-upload.test.snap.js
Labels: target/24.6, target/24.7

#8745 fix: do not open popover after focusout during focus delay
  packages/popover/src/vaadin-popover.js
  packages/popover/test/trigger.test.js
Labels: target/24.5, target/24.6, target/24.7
