Repository vaadin/web-components, pull requests merged in 2025-08, with the labels that each got.

#9872 fix: adjust row and col count base on Grid state
  packages/grid/src/vaadin-grid-a11y-mixin.js
  packages/grid/src/vaadin-grid-mixin.js
  packages/grid/test/accessibility.test.js
Labels: target/24.7, target/24.8

#9942 fix: do not throw on closing popover when target is not set
  packages/popover/src/vaadin-popover.js
  packages/popover/test/basic.test.js
Labels: target/24.7, target/24.8

#10031 refactor: use focusVisible: true in FocusTrapController focus
  packages/a11y-base/src/focus-trap-controller.js
  packages/a11y-base/test/focus-trap-controller.test.js
Labels: target/24.9

#10008 feat: add tooltip support to vaadin-side-nav-item
  dev/side-nav.html
  packages/side-nav/src/styles/vaadin-side-nav-item-base-styles.js
  packages/side-nav/src/vaadin-side-nav-item.js
  packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
  packages/vaadin-lumo-styles/src/components/side-nav-item.css
  test/integration/package.json
  test/integration/side-nav-item-tooltip.test.js
Labels: target/24.9

#10091 fix: allow reordering grid columns inside a draggable parent
  packages/grid/src/vaadin-grid-column-reordering-mixin.js
  packages/grid/test/column-reordering.test.js
Labels: target/24.7, target/24.8, target/24.9
